### ISSUE TITLE
Validator Error-Unable to find original language quote in verse text-916 due to punctuation in OrigQuote

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#1005]
Content Validator throws 916-Unable to find original language quote in verse text error due to  comma (,) in the original Quote. Comma does not get highlighted, but rest of the Original quote does. The user cannot fix this error.
![Screen Shot 2021-08-30 at 4.03.57 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/172a8a5e-17f7-4bac-949d-f3279acb8cd4)

![Screen Shot 2021-08-30 at 4.04.38 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/aa7a09b5-d9d1-40a9-9451-a35e1bb8a264)

**Comment by abelpz** [comment]
@elsylambert Not sure that I understand the error. The higlighter does not highlight punctuation but just words. Is this a wrong report from the validator? The highlighting seems correct after checking the alignment.

**Comment by elsylambert** [comment]
translationCore Create - v1.17 build 278-e8671df. Validator no longer reports 916 error when there is a comma in the Original quote.
