### ISSUE TITLE
Refactor support for Content Validation

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/tc-create-app#1008]
Current State: the "datatable" component contains logic and processing that only works for 9 column tN.

Desired State: remove the 9col tN specific support from the datatable component into tc-create itself.

DoD: Content Validation should work the same as prior to the change.

**Comment by ancientTexts-net** [comment]
@Joel-C-Johnson @jincypjose 

We have not reviewed this one yet :(

**Comment by elsylambert** [comment]
Works as expected in translationCore Create - v1.4.0-rc.4 build 108-41a72cb with all the Tn resources .
