### ISSUE TITLE
Katalon:ID required for the close button for Repo on the header bar.

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#1010]
Please add ID for the element: close button for the Repo for Katalon scripts to work.

![Screen Shot 2021-09-02 at 3.14.53 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/71c5138d-c78d-4229-9cb1-015414cfaccf)

**Comment by ancientTexts-net** [comment]
@Joel-C-Johnson @jincypjose 

This is the issue for the "close button" automated testing from @elsylambert 

- close button "works" (kind of 😊)
- BUT there is no attribute to identify the "close" button in Katalon (like Selenium)

**Comment by ancientTexts-net** [comment]
suggest:
- fix in RCL (`gitea-react-toolkit`)
- yalc publish
- yalc add
- test in the app (developer tools)

**Comment by ancientTexts-net** [comment]
@jincypjose @Joel-C-Johnson 

https://app.zenhub.com/workspaces/tc-create-workspace-5f049cdbfa88090016bf043e/board?repos=93856410,122679395,180812604,191973535,196089755,179390258,209859478,265372377,309771140

**Comment by elsylambert** [comment]
@Joel-C-Johnson @jincypjose I am not seeing the change in the xpath. can you please point me to the attribute that you added?

**Comment by Joel-C-Johnson** [comment]
Created a PR -  [#112](https://github.com/unfoldingWord/gitea-react-toolkit/pull/112)

**Comment by Joel-C-Johnson** [comment]
- created a beta version in gitea-react-toolkit (1.11.1-beta.0)
- connected with the tc-create-app
- created a netlify app for testing with the katalon

Demo : https://tc-create-app-test.netlify.app/

**Comment by jincypjose** [comment]
Have approved the PR.Saw you gave id to the button.

**Comment by birchamp** [comment]
@elsylambert use Joel's link above to test.

**Comment by elsylambert** [comment]
looks good in  https://tc-create-app-test.netlify.app/. @Joel-C-Johnson This can be merged to develop.

**Comment by Joel-C-Johnson** [comment]
Hi @elsylambert, The code is merged into develop. Moving this issue into QA

**Comment by elsylambert** [comment]
Looks good in translationCore Create - v1.4.0-rc.4 build 108-06d4807. The Repo close buttons functions correctly.
