### ISSUE TITLE
User Re-login not working from the login Modal

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#1018]
v1.3.0 build 72-a6038d2.
- Login to the app> select org/resource/language and open the file.
- Make some edits to the file but do not save.
- Open another tab and open tccreate app and login. Do not make any edits
- Open the first tab (session 1) opened in step 1. and try to save the edits done in step 2. Note that the "Login to try again" modal appears. 
- Enter username and password. The login button does not work at this point.

This works fine in Production build v1.2.1 build 55-760999c.

**Comment by ancientTexts-net** [comment]
culprit is the line here with the breakpoint

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/56ea973d-7944-4873-969b-938962c45c4d)

**Comment by ancientTexts-net** [comment]
@jincypjose

**Comment by ancientTexts-net** [comment]
![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/e10b64bb-7483-40ec-a3c6-ced81395a417)

**Comment by ancientTexts-net** [comment]
best I can tell, AuthenticationContext is null for some reason

**Comment by ancientTexts-net** [comment]
but looks fine here
![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/635edd2e-8224-46d9-b4a5-c1e0d2923417)

**Comment by ancientTexts-net** [comment]
@Joel-C-Johnson @jincypjose @mannycolon  can anyone help me please ☹😦😦🙁🙁

**Comment by PhotoNomad0** [comment]
@ancientTexts-net I have a suspicion that the exception is inside the method onLoginFormSubmitLogin.  Is that defined in GRT?  From the stack trace it looks like the code has gone through webpack.  Will take a look.

**Comment by PhotoNomad0** [comment]
@ancientTexts-net I looked in the code and don't see anything obvious.  I was suspicious that it may be related to the useMemo and authenticationModal being updated due to authentication being invalidated which would cause the authenticationContext to be regenerated.  Wondering if the useMemo could be removed?

**Comment by elsylambert** [comment]
@ancientTexts-net Is this fixed in https://stage--tc-create-app.netlify.app/ ? I see the build number is the same old one.

**Comment by ancientTexts-net** [comment]
@elsylambert 

Fixed, thank you:
https://v1-3-0--tc-create-app.netlify.app/

😊😊

CC: @Joel-C-Johnson @jincypjose

**Comment by elsylambert** [comment]
Works fine in translationCore Create - v1.3.0 build 73-f59f312. Uesr re-login works and saves the edit from previous logged in session.
