### ISSUE TITLE
Unable to undo the highlight in scripture pane 

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#103]
Steps to replicate:
1.  Select a Greek text from the Scripture pane, copy and paste in the OriginalQuote. This made the greek text highlight(yellow) in the scripture pane. 
2. Remove the text from the OriginalQuote, the highlight in the scripture pane would not go away.
3. Save the file. The Highlight from step 1 persists even after the OriginalQuote is deleted.

**Comment by RoyalSix** [comment]
@elsylambert tested in v0.9.0-beta.13

**Comment by elsylambert** [comment]
Beta-13. When the greek text is pasted in OriginalQuote section, it is now removing the Previous Greek highlight in the verse.
1. copy and paste one non-highlighted greek word in the OriginalQuote section.
2. Hit enter, Note that the previously highlighted greek words are no longer highlighted.

**Comment by birchamp** [comment]
DoD: The previous highlight does not get reset in the scenario above.

**Comment by RoyalSix** [comment]
@elsylambert , I am testing this one and it seems like the expected behavior is to unhighlight the words in the scripture pane because the highlighted words are based on whats in the original quote section not based on what the scripture pane shows.

**Comment by elsylambert** [comment]
Verified in Beta-14. Both the cases as reported for highlighting are fixed. 
- able to undo the highlight when the greek word is removed from OriginalQuote.
- Previous highlights are retained. The OriginalQuote should be legit and should match the Greek in the Parallel Scripture viewer. This works as expected.
