### ISSUE TITLE
Add OBS Study Notes

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#1030]
Add OBS Study Notes as a source resource to be translated.

**Comment by elsylambert** [comment]
translationCore Create - v1.4.0-rc.3 build 104-85b41fb.
sn_OBS.tsv opens up fine and shows the columns.  The header is missing which is written up separately in #1103.

**Comment by elsylambert** [comment]
Looks good in translationCore Create - v1.4.0-rc.4 build 108-41a72cb. Notes is shown as default and Header is displayed correctly.
