### ISSUE TITLE
warn users that their branch is out of date

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#1066]
Issue:
===
Users can create branches easily in tC Create, so often they don’t remember that they opened a file many weeks or months before. This typically means that the file is out of date and changes will create conflicts.  Users want to be warned if this is the case.   They want to know if their branch is more than 14 days out of date.  A popup with an ok button shows up on file open. 

"Your branch is more than 2 weeks out of date. Older branches are more likely to conflict with newer work. Please contact your administrator to update your branch."   [OK]

DoD:
===
Users are warned if their branch is out of date when compared to the date of the master branch. 

Details:
===
from 10/20/21 Sprint Review

**Comment by birchamp** [comment]
Discussion about this issue is here: https://unfoldingword.zulipchat.com/#narrow/stream/207526-Tools---UR/topic/tC.20Create.20branches/near/277947395

**Comment by superdav42** [comment]
This will require changes in gitea-react-toolkit and tc-create-app. The method added in https://github.com/unfoldingWord/gitea-react-toolkit/pull/140 will let us see the time the branch was last updated. Although showing the amount of commits and line changes between to branches might be more informative there does not seem to be a gitea api endpoint to easily fetch this information so I suggest we stick with comparing timestamp to show how old a branch might be.

**Comment by superdav42** [comment]
This is not actually ready for release just the gitea portion has been [merged](https://github.com/unfoldingWord/gitea-react-toolkit/pull/140#event-6975839714) but tc-create-app will need to actually call the new method introduced there and show a notice. Someone else could pick this up if they want.

**Comment by elsylambert** [comment]
@jincypjose translationCore Create - v1.6.0 build 161-1f4e570 I do not see the pop-up when I open the file, for my 4 week old branch for en_tq for GEN file. Also checked for en_ta for my 2 month old branch. Can you please provide more information on how to test it? or which Repo did you used to test this one?

**Comment by elsylambert** [comment]
translationCore Create - v1.6.0 build 164-06992b7.
Seeing a warning message when user branch is older than 2 weeks.
![Screen Shot 2022-08-31 at 9.24.04 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/e5f92333-47d4-4f1c-afa1-b91bb1e19b9d)
Note: It does not stop user from continuing the work on the older branch, but does warns as per the DOD.
