### ISSUE TITLE
Jump to last clicked position after closing search

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#1088]
Issue:
---
Currently, when a user searches and then closes the search it returns to the first record.  

The new behavior should be that a user searches and then clicks the X for the search bar and returns to the last edited record in a TSV.  This means that if during the search the user doesn't click inside any row, they will return to where they were working previously.  It also means that if they click inside a record during the search they will remain at that location in the file. 

DoD:
---
Closing the search bar will return the user to the last edited record.

Details:
---

**Comment by birchamp** [comment]
@Joel-C-Johnson demonstrate the problem in the RCL and then add the functionality to retain the position of the last used row.

**Comment by birchamp** [comment]
@Joel-C-Johnson do you know if you are planning to return to the last row *clicked* or the last row *edited*?

**Comment by Joel-C-Johnson** [comment]
@birchamp I am sorry for the late reply, I didn't get the notification for it. 
Yeah what I have done was, when we click on a row(for editing/normal click ) I am saving the row ID and return to that row using the rowID

**Comment by elsylambert** [comment]
Works as expected in translationCore Create - v1.6.0 build 160-94d5496. App returns to the last clicked row on closing search.

**Comment by elsylambert** [comment]
Thanks David.
@eliaspinero Can you please review the PR and merge to develop?
