### ISSUE TITLE
Return to last clicked row on closing filter

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#1089]
Issue:
---
Similar to #1088
When the user clicks on the close X for a filter the file will return to the last clicked row.  If the user doesn't click on a row then the file will return to the place they were editing prior to the filter operation. If the user clicks in a row that was returned by the filter, then the file will return to that row.

DoD:
----
The file returns to the last clicked row when the filter is closed. 

Details:
----

**Comment by elsylambert** [comment]
Works as expected in translationCore Create - v1.6.0 build 160-94d5496. App returns to the last clicked row on closing the filter.
