### ISSUE TITLE
"Unsupported file..." message comes up everytime a .tsv or .md file is opened

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#109]
The purpose of showing the message  was for the unsupported file types but it seems it now shows for the supported files as well.

The message should not be displayed for the .tsv or .md files.

**Comment by mandolyte** [comment]
Here is source of error: 
https://github.com/unfoldingWord/tc-create-app/blob/develop/src/components/translatable/Translatable.js#L30

Simply making a change to not assign the error message until later doesn't work. Needs to have a hook ... more complicated than first appears.

**Comment by mandolyte** [comment]
Visual change:
a) put spinner nearer to middle of page, at least width-wise
b) put error text in middle of page

**Comment by klappy** [comment]
Should be QA testable in `v0.9.0-rc.2`.

**Comment by elsylambert** [comment]
Looks good in v0.9.0-rc.2. Not seeing the unsupported file message for .tsv and .md files but only for the other types of files.

**Comment by klappy** [comment]
Should be testable in app `0.9.0-rc.6`

**Comment by elsylambert** [comment]
Looks good in 0.9.0-rc.6. Works as expected.
