### ISSUE TITLE
Repo Icons for the Resources are missing

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#110]
Repo icons which were changed in #63 are missing from the Beta-10 version.  
<img width="1706" alt="Screen Shot 2020-04-01 at 10 07 15 AM" src="https://user-images.githubusercontent.com/51806180/78146809-aa0ca980-7400-11ea-86a2-23dfbf84a6f7.png">

**Comment by klappy** [comment]
Looks like the bg.door43.org server did not have repo icons setup for the repos. I just updated the repo's settings on that server. 

They should show up now.

**Comment by elsylambert** [comment]
Works fine now.
