### ISSUE TITLE
Validator reports errors in Tags as unexpected for OBS-sq

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#1112]
Validator reports errors in Tags  column for "Meaning" and "Application "as unexpected for OBS-sq while this seems like a valid entry in the DCS file.
![Screen Shot 2021-12-21 at 9.03.31 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/a0817104-fb2e-47ac-9438-c15363c23e54)

@mandolyte  @birchamp   Is this a bug  in CV or a content issue?

**Comment by RobH123** [comment]
I would guess a CV bug. Will check out....

**Comment by mandolyte** [comment]
May be the verse ranges are a problem? We should upgrade to 3.1 for this
alone, right?

**Comment by RobH123** [comment]
Yes, I see that the CV code to handle this properly was added for v3.0 (never released) but in v3.1.

**Comment by elsylambert** [comment]
Not seeing the problem in translationCore Create - v1.4.0-rc.6 build 112-319dd6a with the latest CV3.1.1.
