### ISSUE TITLE
Upgrade content validation to v3.1.0

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/tc-create-app#1118]
This will add support for verse range checking (already used in some of the new resource types, such as SQ).

Plus, it add convenience functions that are aligned by resource type. These make it simpler to use the CV package.

They are found in the CV `src/core/wrapper.js` file. They are:
- export async function checkTN_TSV7Table(username, languageCode, bookID, filename, tableText, checkingOptions) 
- export async function checkSN_TSV7Table(username, languageCode, bookID, filename, tableText, checkingOptions) 
- export async function checkTQ_TSV7Table(username, languageCode, bookID, filename, tableText, checkingOptions) 
- export async function checkSQ_TSV7Table(username, languageCode, bookID, filename, tableText, checkingOptions) 
- export async function checkTWL_TSV6Table(username, languageCode, bookID, filename, tableText, checkingOptions) 
- export async function checkTA_markdownArticle(username, languageCode, articleFilepathInRepo, articleFileContent, checkingOptions) 
- export async function checkTW_markdownArticle(username, languageCode, articleFilepathInRepo, articleFileContent, checkingOptions) 
- export async function checkDeprecatedTN_TSV9Table(username, languageCode, bookID, filename, tableText, checkingOptions) 

Further, note that Scripture and OBS share the same wrapper for a given type.

**Comment by elsylambert** [comment]
![Screen Shot 2022-01-04 at 12.32.28 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/e8dc9e5d-7608-4ac3-af9e-517a574c34ec)
Row ID should start with a Lowercase letter. IDs are generated automatically. We cannot expect the users to fix this error. Priority of this error is 176-very low.

**Comment by elsylambert** [comment]
Looks good in translationCore Create - v1.4.0-rc.6 build 112-319dd6a.
