### ISSUE TITLE
Turn off editing in preview mode on TSVs

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#1127]
Issue:
---
There are a number of complications to editing the text in preview mode. Users have said that they would prefer not to use it.  Editing in preview mode should be disabled. Markdown mode should be the default view on opening a file. 

DoD:
----
Preview mode should be view only.

**Comment by birchamp** [comment]
@jincypjose per Zach and Klappy, when the preview button is clicked, set Preview: true and Editable: false.

**Comment by elsylambert** [comment]
Looks good in translationCore Create - v1.4.4 build 153-d1b4fc1.
