### ISSUE TITLE
Release 1.4

### ISSUE THREAD

**Issue by ancientTexts-net** [unfoldingWord/tc-create-app#1131]
#### Prepare Staging 
- [x] PR to remove RC from the version number
  - start in new branch (e.g., `zpp-remove-rc-1.4`); 
  - edit `package.json` for version (e.g., v1.4); commit; publish
  - `git tag` (e.g., v1.4);    `git push --tags`
  - create PR from `remove...` branch --> `develop`;  connect this PR to the "RELEASE" issue
  - merge this PR (even if you merge it yourself, please use PR and do not commit directly to the develop branch)
- [x]  Release Branch:
  - pull latest develop changes
  - create new branch: release branch for version 1.4 from develop
  - publish release branch to github
- [x] Create staging Netlify link (PROD Data)
  - create new PR from `v1.4` --> `STAGE`; connect to the release issue
  - walk through happy path on deploy preview
  - merge 
  - Monitor build: wait 20 minutes?  https://stage--tc-create-app.netlify.app/
    Verify version & build number are updated.
    (If the DEPLOY PREVIEW encountered NO errors, then STAGE should build fine.)
#### QA Release and Staged 
  - [x]  Ping QA that release branch for version 1.4.0 is ready for testing  
  - [x] Release notes are drafted
  - [x] QA approves release notes
  - [x] QA gives go-ahead to release to production
#### Release and Publish
  - [x] PR from release branch for version 1.4.0 to Master
    - create new PR from `STAGE` --> `master`; connect to the release issue
    - walk through happy path on deploy preview
    - merge 
    - Monitor build: wait 20 minutes?  
       - https://app.netlify.com/sites/tc-create-app/deploys/
       - https://create.translationcore.com/
       - Verify version & build number are updated.
          (If the DEPLOY PREVIEW encountered NO errors, then PROD should build fine.)
  - [x] Ping QA that production release is released
  - [x] Final Go ahead  from QA to notify the users of the new release
  - [x] tag release on Github v1.4.0
  - [x] publish release note
  - [x] Announce on forum.door43.org https://forum.door43.org/t/tc-create-1-x-release-notes/661

**Comment by ancientTexts-net** [comment]
![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/c0a9d40c-9946-4c0b-a909-1af298c9f31f)

**Comment by ancientTexts-net** [comment]
https://github.com/unfoldingWord/tc-create-app/tags

**Comment by ancientTexts-net** [comment]
![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/84db0238-6ad7-4b5b-b0a2-0c749e372d05)

**Comment by ancientTexts-net** [comment]
![image](https://user-images.githubusercontent.com/61445099/148706842-25aea042-5b75-480e-aaa2-94d05e2c1a4f.png)

**Comment by ancientTexts-net** [comment]
![Uploading image.png…]()

**Comment by elsylambert** [comment]
1.4 is live in Production.
