### ISSUE TITLE
Create new Cypress Tests

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/tc-create-app#1146]
MD
  1. Edit, Save and Load changes
    - (bootstrap by repeating stepper or does it resume?)
    - Edit a .md file
    - Save a change to a .md file
    - Load a saved change to a .md file

TSV
  1. Pagination on .tsv file
    - (load a translation notes file such as titus)
    - switch to 100 rows
    - change to page 2
    - change to page 3
    - Look for expected content on screen such as scripture
  2. Column filter
    - click column filter button
    - select/deselect columns
    - Look for expected content on screen

**Comment by ancientTexts-net** [comment]
I notice this issues has PRs for `datatable-translatable` attached.
SEEMS LIKE we need to PUBLISH RCL ++ bump version in dependency.

I can help with that 👌 I think I will look at new QA fails first 👌

@Joel-C-Johnson @jincypjose @klappy @elsylambert 
@birchamp @BincyJ

**Comment by ancientTexts-net** [comment]
![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/c1559a68-195b-4edf-933a-57c73c92b454)

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/db353bc1-de23-4a94-9eef-a7a226d1b852)
