### ISSUE TITLE
Change Hebrew scripture to a larger serif font

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#1151]
Benjamin uses a serif font and increases the font size so that the Hebrew is more readable. We should use this by default for Hebrew scriptures.  

DoD
===
Hebrew scripture is displayed in a font that is larger and more readable.

Details
---
tC uses: 
1.2 em - 20% bigger for Greek with the default font.  
1.7 em - 70% bigger for Hebrew with the 'Ezra' font (possibly in bold)

**Comment by mandolyte** [comment]
In markdown-translatable within `/src/components/block-editable/BlockEditable.js`:
```js
  const _style = useMemo(
    () =>
      isHebrew(markdown) ? { ...style, fontSize: '1.5em' } : style,
    [style, markdown]
  );
```

**Comment by mandolyte** [comment]
In scripture-resources-rcl...

in `/src/components/verse-objects/AlignedWordObjects.js`:
```js
        if (lexiconData) {
          const isHebrew = lexiconData['uhl'];
          return (
            <WordLexiconDetails
              lexiconData={lexiconData}
              wordObject={wordObject}
              translate={translate || translate_}
              isHebrew={!!isHebrew}
            />
          );
        }
```

in `/src/components/verses/Verses.js`:
```js
  useEffect(() => {
    if (!direction) {
      const verseText = verses['1'].verseObjects.map(verseObject => verseObject.text).join('');
      const hebrew = isHebrew(verseText);
      if (hebrew) setDir('rtl');
      else setDir('auto');
    }
  }, [verses, direction]);
```

in `/src/core/language-detection.js`:
```js
export const isHebrew = (string) => {
  const hebrewChars = string.match(/[\u0590-\u05FF]/g) || [];
  const percent = hebrewChars.length / string.length;
  return percent > 0.75;
};
```

**Comment by elsylambert** [comment]
@mandolyte I know that this issue is in Progress, but I wanted to point out that I see larger Hebrew fonts in translationCore Create - v1.6.0 build 164-06992b7, but it looks like it owerflows into ULT text.
![Screen Shot 2022-08-31 at 9.18.33 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/26aae073-71a3-49b2-91fc-0fe8e5d5fe90)

**Comment by mandolyte** [comment]
Based on the image, I think this is the nature of juxtaposing a rtl
language next to ltr language

**Comment by elsylambert** [comment]
translationCore Create - v1.7.0 build 165-900bcf1. Hebrew font looks bigger and bolder as in the screenshot.
![Screen Shot 2022-09-14 at 1.24.20 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/10e8e778-b7a7-4117-a8e9-db100996d860)

But the ULT and UST scripture fonts are smaller(different ) than previous (Production).
Also the Greek font looks smaller, please see the comparison with v1.6.

**Comment by elsylambert** [comment]
Looks good in translationCore Create - v1.7.0 build 167-c63d59b. Hebrew font looks bigger than before so are the Greek and English fonts in the scripture pane.
