### ISSUE TITLE
tCC refactor

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#1154]

**Comment by mandolyte** [comment]
**On uw-tsv-parser...**

At the end, there are two lines that can be changed to fix things up...

- Repo: https://github.com/unfoldingWord/uw-tsv-parser
- Demo: https://unfoldingword.github.io/uw-tsv-parser/
- Specification for code:
  - Requirements at: https://forum.door43.org/t/parascriptural-tab-separated-value-format-specification-v2/870
  - Detailed Reference: https://en.wikipedia.org/wiki/Tab-separated_values


**Usage:**

*Note! the usage below is taken from the master branch.*

In tc-create, this parser is used in these places:
- to correctly *decode* for the "on open validation" function. See `src/core/onOpenValidations.js`
- to correctly *encode* for the content validation function. See `src/core/contentValidate.js`
- in all the Translatable*TSV files, where it is passed to datatable-translatable. For example, the parser propterty:
```js
  const datatable = useMemo(() => {
    _config.rowHeader = rowHeader;
    return (
      <DataTable
        sourceFile={sourceFile.content}
        targetFile={targetFile.content}
        onSave={onSave}
        onEdit={onEdit}
        onValidate={onValidate}
        onContentIsDirty={onContentIsDirty}
        delimiters={delimiters}
        config={_config}
        generateRowId={generateRowId}
        options={options}
        parser={parser}
      />
    );
  }, [sourceFile.content, targetFile.content, onSave, onEdit, onValidate, onContentIsDirty, generateRowId, options, rowHeader]);
```

**NOTE: the parser is not present in the refactored code**

Then in datatable-translatable, it shows first in the properties for
`src/components/datatable/DataTable.context.js`
```js
export function DataTableContextProvider({
  children,
  sourceFile,
  targetFile,
  delimiters,
  parser,
  config: {
    compositeKeyIndices,
    columnsFilter,
  },
}) 
```

Thru out the above file, the existence of the parser is checked for and is used
when present. Here is just one example of many:
```js
  // parse sourceFile when updated
  useEffect(() => {
    if (parser && parser.tsvStringToTable) {
      console.log("DataTable.context() using tsv parser for source")
      const { data: rows } = parser.tsvStringToTable(sourceFile);
      setSourceRows(rows);
    } else {
      if (delimiters) {
        const { rows } = parseDataTable({ table: sourceFile, delimiters });
        setSourceRows(rows);
      }
    }
  }, [sourceFile, delimiters, parser]);
```


**To update refactored code**
1. Add this import back into TranslatableTSV.js:
```
import * as parser from 'uw-tsv-parser';
```

2. Add this property to `<DataTable />`
```
        parser={parser}
```

**Comment by klappy** [comment]
@mandolyte Just implemented and works like a charm!!! Thanks!!

**Comment by klappy** [comment]
OBS row header/toolbars now display!

**Comment by klappy** [comment]
bumped minor version to v1.5.0
