### ISSUE TITLE
Extra '\' in rc links for tWLs while adding a new row

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#1155]
![Screen Shot 2022-02-03 at 1.25.32 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/0cf7f879-c30f-4ea0-a70b-aa16450ca6e1)

Steps:
- Open any book/file in tWl Resource.
- add a new row. Note that the Modal shows RC links with an extra '\\'.

DoD:
---
New rows are displayed and created with a properly formatted RC link.

**Comment by birchamp** [comment]
@elsylambert can you confirm if the incorrect / ends up in new row?

**Comment by elsylambert** [comment]
@birchamp , @mandolyte  and I saw this problem happening about 6days ago but I no longer see \ backslash inserted in  a new row or after editing the RC link in an existing row. However, it shows on the ADD and DELETE modal as in the snapshot in the issue description.
Interestingly, the problem is not seen in Production as well now.

**Comment by elsylambert** [comment]
translationCore Create - v1.4.2 build 145-8501031.
@birchamp Seeing this issue in raw markdown. When TWLink is edited an extra \ is added in the markdown mode. CV also reports the TWLink is not formatted correctly. ![Screen Shot 2022-04-28 at 1.59.39 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/ba606c37-f3e8-4bb9-84aa-f6ae242601c2)

**Comment by birchamp** [comment]
@elsylambert are you still seeing this?

**Comment by elsylambert** [comment]
As I mentioned in my previous comment, "\" is visible in markdown mode.![Screen Shot 2022-05-11 at 2.46.30 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/c54db3f7-2503-40eb-9e6b-ae810f35d1f4)
- Open tWL file, 
- Make an edit to twl link and save.
- toggle on markdown button and you will note the "\" in the TWLlink.

**Comment by superdav42** [comment]
I may need more context but it seems like it is behaving as it should. 
`rc://\*/tw/dict/bible/other/water` is the correct markdown for `rc://*/tw/dict/bible/other/water` the \* is escaped so it will be rendered as a literal `*`. 
The https://markdown-translatable.netlify.app/ site behaves the same way. 

Paste `rc://*/tw/dict/bible/other/water` in one of the fields then toggle off the preview and you'll see the slash.

It appears the TWLink just contains a url with an rc:// scheme. Maybe it should not contain any markdown but be treated as plain text?

**Comment by birchamp** [comment]
@superdav42 I think it works correctly in the TN resource for the 9 column tsv. So you could check there what it should be. @elsylambert is that correct?

**Comment by elsylambert** [comment]
rc://*/tw/dict/bible/other/water

**Comment by elsylambert** [comment]
rc://*/tw/dict/bible/other/water

**Comment by elsylambert** [comment]
Another problem is that because of the twl links, the articles related to that are not opening in gatewayEdit app.

**Comment by elsylambert** [comment]
![BE47BFC5-91A6-45C7-88C3-D96ED345311D](https://user-images.githubusercontent.com/51806180/168312123-258c607f-4307-48ed-a126-80be387e868a.jpeg)

**Comment by birchamp** [comment]
> @birchamp I did not get your question about TN tsv. I pasted the rc link in tn tsv and on toggle found that backslash was added in markdown view. @superdav42 https://markdown-translatable.netlify.app/ is the RCL so I expect the behaviour there, that means it needs fixing there. To be clear on the correct markdown format, we can verify here on the issue comment.

So I must have remembered wrong because I thought this was a TWL only issue. Did this ever work in previous versions?

**Comment by elsylambert** [comment]
Not sure about that. I think it got introduced when rc link started to contain * in place of language code like en.

**Comment by birchamp** [comment]
Oh yeah. I forgot about the language code.  Good thing I have you to remember these things!!
