### ISSUE TITLE
Release v 1.4.2

### ISSUE THREAD

**Issue by BincyJ** [unfoldingWord/tc-create-app#1156]
#### Prepare Staging 
- [x] PR to remove RC from the version number
  - start in new branch (e.g., `zpp-remove-rc-1.4.2`); 
  - edit `package.json` for version (e.g., v1.4.2); commit; publish
  - `git tag` (e.g., v1.4.2);    `git push --tags`
  - create PR from `remove...` branch --> `develop`;  connect this PR to the "RELEASE" issue
  - merge this PR (even if you merge it yourself, please use PR and do not commit directly to the develop branch)
- [x]  Release Branch:
  - pull latest develop changes
  - create new branch: release branch for version 1.4 from develop
  - publish release branch to github
- [x] Create staging Netlify link (PROD Data)
  - create new PR from `v1.4.2` --> `STAGE`; connect to the release issue
  - walk through happy path on deploy preview
  - merge 

Definition of Done
- [x]  QA signs off on specific build in regression testing: current for v4.1.0, build number: 
- [x]  Update changelog
- [x]  create draft release on github for translationCore
- [x]  Attach the github action builds (same build as QA signed off) to the draft release as assets
- [x]  Update Release Notes to the draft release
 after everyone has reviewed translationCore draft release, make it an official release.
- [ ]  Confirm all links to the release
-  github release page - https://github.com/unfoldingWord/translationCore/releases
-  door43 forum

**Comment by Joel-C-Johnson** [comment]
Production is updated with **v1.4.2**
https://create.translationcore.com/

**Comment by Joel-C-Johnson** [comment]
![version](https://user-images.githubusercontent.com/25791348/166052668-8822ee9f-f41c-4c18-acb1-d845750eea79.png)

**Comment by Joel-C-Johnson** [comment]
![release](https://user-images.githubusercontent.com/25791348/166054887-d0337124-05df-43b5-9d88-633616a9a8b1.png)

**Comment by elsylambert** [comment]
translationCore Create - v1.4.2 build 145-8501031 is live in Production is looks good.
