### ISSUE TITLE
Slow rendering of scripture viewer in tN's.

### ISSUE THREAD

**Issue by lrsallee** [unfoldingWord/tc-create-app#116]
When working on tN's for Titus, the scripture viewer takes a long time to render. In a larger book such as Luke, it seldom completes the rending for a 25-note section. I have waited up to 15 minutes before giving up on editing notes. It is not just the highlighting that is the problem—the scripture viewer does not appear at all so that I can do any work on the note.

**Comment by elsylambert** [comment]
Beta-13. Not seeing this issue.  Parallel scripture viewer loads up faster in my machine. However, I am keeping this on watchlist. It may be happening after a series of actions /edits on the app. Need to keep an eye.

**Comment by klappy** [comment]
This issue is testable on both RCL and App
- RCL: https://1-0--scripture-resources-rcl.netlify.app/#!/ParallelScripture/0
- App `0.9.0-rc.5`: https://develop--tc-create-app.netlify.app/

Overall functionality should be identical but more performant when scrolling through a TSV.

**Comment by elsylambert** [comment]
Looks good in 0.9.0-rc.6. Titus loads up scripture pane in less than a second.
