### ISSUE TITLE
Performance is degraded because of multiple file downloads

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#1161]
This fixes the bug of multiple downloads of the files. 

**For testing:**
Determine if app works as expected. 
App should not load 100 rows of a TSV slower than 1.4.0 on the production server.

**Comment by elsylambert** [comment]
+++++++++++ Test Cases/tCC Test Cases/tCC tN Test Paging Performance on translationCore Create - v1.4.0 build 113-e01d8f1 running on chrome in tCC Production PASSED +++++++++++ 

## Processing Times ##
Timings test on 10 rows.
Paging 10 rows took 1.542 seconds.
 
Timings test on 25 rows.
Paging 25 rows took 1.784 seconds.
 
Timings test on 50 rows.
Paging 50 rows took 4.16 seconds.
 
Timings test on 100 rows.
Paging 100 rows took 17.258 seconds.
 
Average time to page 10 rows is 1.54 seconds, and 0.15 seconds/row.
Average time to page 25 rows is 1.78 seconds, and 0.07 seconds/row.
Average time to page 50 rows is 4.16 seconds, and 0.08 seconds/row.
Average time to page 100 rows is 17.26 seconds, and 0.17 seconds/row.

STAGING SERVER 
 +++++++++++ Test Cases/tCC Test Cases/tCC tN Test Paging Performance on translationCore Create - v1.4.1 build 118-a9b2333 running on chrome in tCC Stage PASSED +++++++++++ 

## Processing Times ##
Timings test on 10 rows.
Paging 10 rows took 1.494 seconds.
 
Timings test on 25 rows.
Paging 25 rows took 1.66 seconds.
 
Timings test on 50 rows.
Paging 50 rows took 4.045 seconds.
 
Timings test on 100 rows.
Paging 100 rows took 16.386 seconds.
 
Average time to page 10 rows is 1.49 seconds, and 0.15 seconds/row.
Average time to page 25 rows is 1.66 seconds, and 0.07 seconds/row.
Average time to page 50 rows is 4.04 seconds, and 0.08 seconds/row.
Average time to page 100 rows is 16.39 seconds, and 0.16 seconds/row.

**Comment by elsylambert** [comment]
translationCore Create - v1.4.1 build 118-a9b2333 on Staging looks good and works as expected. Waiting on @mandolyte to provide feedback on #1209.

**Comment by elsylambert** [comment]
translationCore Create - v1.4.1 build 118-a9b2333 on Staging looks good. #1209 was content issue and is fixed after I deleted old files.
