### ISSUE TITLE
Allow users to edit the fields for new row in a TSV

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#1166]
Issue
---
When users add a record in a TSV the dialog should allow users to change all the fields. Fields that are dropdowns in the Filter tool should be dropdowns in the new row dialog.  [Mockup video](https://drive.google.com/file/d/1v0dh_NaDWJxJyIgU_8PGKRcVNRE6aIO9/view?usp=sharing)

DoD:
---
Users can edit the fields in a new record and the record is created with that chapter verse.

Details:
---
![CleanShot 2022-04-12 at 17.10.05.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/85518d66-501c-4686-8194-d796d79c573a)
All fields in the new record dialog need to be editable text fields. This was originally mentioned #205.

**Comment by elsylambert** [comment]
Works as expected in translationCore Create - v1.5.0 build 154-e836e43. Able to add a row with editable fields. The issue for sort order of the new rows is written separately in #1309.
