### ISSUE TITLE
Create stage branch for 1.4.1

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#1176]
Create a branch that can be used to test speed with the production server

**Comment by ancientTexts-net** [comment]
Here's the steps we did to publish to `stage`

1. bump version (use new branch)
2. commit/push to the new branch; create PR for "bump version"
3. merge PR --> `develop`

---
Netlify is setup to recognize the `stage` branch with its own build & environment variables.
These environment variables are defined in `netlify.toml` (`[context.stage]`).
In this case, tC Create will use PROD for DCS.

4. create PR to `stage` <-- `develop`
5. monitor netlify link

**Comment by ancientTexts-net** [comment]
@elsylambert @birchamp @BincyJ @jincypjose @Joel-C-Johnson 

stage is updated with bumped version label:

https://stage--tc-create-app.netlify.app/
