### ISSUE TITLE
New note with single-word OrigL snippet does not highlight

### ISSUE THREAD

**Issue by lrsallee** [unfoldingWord/tc-create-app#118]
I created a new test tN for Titus with a single Greek word as a snippet. The highlighting for the word would not appear, even after waiting for a considerable period of time. I finally added another word to the snippet, and the highlighting appeared very quickly. I noticed previously-created notes with single-word OrigL snippets that worked correctly. But the new one I created did not work.

**Comment by elsylambert** [comment]
This issue has been reported in #102.
Adding another word does not do highlight either for me.
