### ISSUE TITLE
Highlighting does not work when there are repeated words in an ellipsis

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#1183]
Problem: When there is an ellipsis in OrigQuote, all the words should be highlighted, but when there is a repeated word in the ellipsis, the second Occurrence of the repeated word does not highlight. For example: if the OrigQuote is σοῦ…σου…σου, The highlight is shown as below:
![Screen Shot 2022-10-26 at 10.58.22 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/ba3b900a-a0f1-4dd2-9036-1385af591bf0)
tCC does not show highlight for the second occurrence of σου.

Example II: Open TCC and select org>unfoldingword, lang- en , resource- tN and select file PHP.tsv. Navigate to id b1q7 for the below mentioned example: εἴ τις…εἴ τι…εἴ τις…εἴ τις will not highlight properly in tCC in note "b1q7" for Phil 2:1
![image.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/143b4a26-3d0f-4e5b-ae9c-02d941e630c6)

The discontiguous words should be highlighted as specified.  So all 4 phrases should be highlighted. 

DoD:
---
Multi ellipsis original quotes show correctly. Specifically b1q7 in Php 2:1

Details:
---
link to Zulip discussion
https://unfoldingword.zulipchat.com/#narrow/stream/209457-SOFTWARE---UR/topic/tC.20Create/near/274619423

**Comment by birchamp** [comment]
This highlights correctly in tC so it should be fixed in tC Create.

**Comment by elsylambert** [comment]
Need clear definition of highlighting with Ellipsis:
- As per the current implementation, when there is ellipsis in the OrigQuote, the highlights do not show up with occurrence -1. And with Occurrences 1, 2 and 3, the highlights are shown correctly for the word in the above example(PHP 2:1)
- How should the highlight show when there is ellipsis or ampersand in the OrigQuote? To show all the occurrences of the word, what should be the Occurrence number?
@birchamp

**Comment by elsylambert** [comment]
Larry: Here is another similar example to add to that issue. tCC only highlights the first two of the tree word in the snippet for Mat 6:3. They are properly, individually aligned. FWIW, there is a comma after the third word.
![image.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/b23b517f-6477-41a0-9121-b82190ad38d2)
[image.png](/user_uploads/15437/v2IjryK4DcXLEBhSmH1evu0X/image.png) 
![image.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/0032d589-26f9-4a78-bb5c-636df38f4d97)
[image.png](/user_uploads/15437/hzMpU8BH-3wTF7x-tlWD8Vc0/image.png)

**Comment by elsylambert** [comment]
TC shows the above example as shown below:
![Screen Shot 2022-10-26 at 11.07.36 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/d8c71b76-b966-4878-af5d-8e5ad449c14c)
tC does highlight it correctly.

**Comment by elsylambert** [comment]
@birchamp I changed the description of the issue and added more details in the  issue ^^. Kindly validate my observations.

**Comment by jincypjose** [comment]
@elsylambert  The issue has been fixed the highlighting is working fine for ![Screenshot from 2022-11-02 22-00-51.png](https://images.zenhubusercontent.com/5f8fb2e83cdc9276e3df86d3/997094ed-e1b6-4ca0-9601-82bb633b67e2)εἴ τις…εἴ τι…εἴ τις…εἴ τις
Build number: 171-d6e20b8

**Comment by elsylambert** [comment]
Verified in translationCore Create - v1.7.1 build 171-d6e20b8. Highlighting works fine when there are repeated words in an ellipsis. All the words in the QriQuote are highlighted with Occurrence number being 1.
