### ISSUE TITLE
On Open Validation - extend to other TSV types

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/tc-create-app#1195]
Based on some testing, I believe on-open validation was only done for TN files (which was the only TSV formatted file back in the day). But now we have many TSV resources. The "on open" validation was intended to be a fast check of certain features to prevent it from being used, since it would likely crash tc-create. Those checks are:
- Does it have the correct header?
- Does every row have the correct number of columns? If not report whether too few or too many.
- Are all ID values unique? Report all duplicates and their row numbers.

It *may* check for:
- empty rows (which would be also be a too few columns issue, but perhaps a different root cause worth reporting)

The existing code should be read to be sure I've captured all that it does.
@birchamp

**Comment by birchamp** [comment]
@mandolyte test after refactor

**Comment by elsylambert** [comment]
Works for tN and tWl.
Does not work for tQ.

**Comment by elsylambert** [comment]
Looks good in translationCore Create - v1.4.4 build 153-d1b4fc1 on develop branch.
