### ISSUE TITLE
Content Validation for Translation Words Lists

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/tc-create-app#1199]
Steps:
- login
- org = unfoldingWord
- resource = TWL
- file = Titus

Next:
- Click the CV button (document with check mark)
- Validation running dialog with Spinner and Close button appears (see below)
- Once complete, the dialog will go away and there will be one of two results:
  - An alert stating that no Validation Errors were found (see below)
  - A spreadsheet will be downloaded containing all the validation errors found.

![image.png](https://images.zenhubusercontent.com/5e8cb99214ac08760f0cb72b/ec76ab10-1881-403a-976f-49faba47420c)

![image.png](https://images.zenhubusercontent.com/5e8cb99214ac08760f0cb72b/7e24d785-681d-48a2-8fe0-a849105c247f)

**Comment by elsylambert** [comment]
I mangled an RCLink in RUTH.twl file, and CV reported the change![Screen Shot 2022-04-08 at 8.52.01 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/7ecc05e4-3abc-4d1d-8f15-30bd6109ce06)
I fixed the same link and ran CV again, it is still reporting the error.
