### ISSUE TITLE
Save Action refinement: App needs to refresh the Save action.

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#120]
Case 1- 
Steps:
1. Edit or add text in the OriginalQuote section and tab out. The Greek word is highlighted in the scripture pane.
2. Remove the greek word from OriginalQuote added in step 1. Note that the highlight on that word was not removed. Click Save.
3. Refresh the page and Note that the  Edit in step 1. is Saved not the edit in step2. In UI, it shows Save button gets enabled and disabled but the actual save was not not the second time. The highlight which appeared in step 1, did not go away with edit in step 2.
Here is my screen recording:
[Issue-120 case 1.zip](https://github.com/unfoldingWord/tc-create-app/files/4670129/Issue-120.case.1.zip)

Case 2-
1. Edit or add text in the OriginalQuote section that has highlight and tab out. The highlight is removed.
2. Fix the OriginalQuote to bring back the highlight. Error: It does not highlight, unless the page is refreshed.
Here is my screen recording:
[Issue-120 case 2.zip](https://github.com/unfoldingWord/tc-create-app/files/4670130/Issue-120.case.2.zip)
This is my branch tit.tsv
![image](https://user-images.githubusercontent.com/51806180/82705590-e8c32100-9c45-11ea-8098-1fd89ffc3cf6.png)

At one instance I saw this working correctly,Here is my screen recording:
[Expected behaviour.zip](https://github.com/unfoldingWord/tc-create-app/files/4670135/Expected.behaviour.zip)

**Comment by mandolyte** [comment]
@elsylambert Here are the steps (in detail) that I did. Did not reproduce the problem. After page refresh, the second persisted.

1. login
2. select tN resource
3. select 2jn
4. in another tab, open bg.door43.org, switch to my branch, then in 2jn,
look at verse 3 (line 7):
```
2JN	1	3	vpl9	guidelines-sonofgodprinciples	Πατρός…Υἱοῦ	1	Father…Son
```
5. find OrigQuote with Πατρός…Υἱοῦ
6. replace this with χάρις and click out of the field
7. after several seconds the save button is enabled. click it. The highlighted
word changes ok.
8. verify change in repo -> (have to refresh page) Yes:
```
2JN	1	3	vpl9	guidelines-sonofgodprinciples	χάρις	1	Father…Son
```
9. change it again, this time with: ἔλεος; button returns to disabled and
highlight moves to new word ok.
10. verify repo --> looks good:
```
2JN	1	3	vpl9	guidelines-sonofgodprinciples	ἔλεος	1	Father…Son
```
11. Now refresh page per steps above and scroll down to verse 3.
12. Results are good.

**Comment by elsylambert** [comment]
@mandolyte I have updated the issue description and added two screen recordings.

**Comment by elsylambert** [comment]
Verified in translationCore Create - v1.0.0-beta.2. Case 2 is fixed. Removing the existing highlights and highlighting it back on editing the Original Quote works fine.

However, Case -1 is still and issue. Once Highlighted and then removed from the Original Quote, does not remove the highlight on the word unless the page is refreshed. 
- Copy and paste a Greek word into Original Quote. The word is highlighted in the scripture pane.
- Remove the Greek word from the Original Quote. The highlight stays.
At this point, if the user refreshes the page, the highlight is gone. But if the user saves the changes(Save button is enabled), the Changes at step 1 are saved.

**Comment by mandolyte** [comment]
**First test:**
_NOTE: All pastes done with ctrl-shift-v_

1. I start here https://develop--tc-create-app.netlify.app/ 
2. login, etc. select UTN, then Titus
3. scroll down to 1:1
4. expand the scripture pane
5. compare source branch with actual repo, they match
```
TIT	1	1	rtc9	figs-abstractnouns	κατὰ πίστιν ἐκλεκτῶν Θεοῦ
```
6. remove last two words from Original Quote and click out; wait until text border goes away (it isn't done until then)
7. hightlighting is changed correctly (this does *not* match your testing)
8. refresh page to effectively undo my changes (did not save yet)
9. do steps 3, 4, and 5: looks good
10. removed last two words (again); highlighting is correct; click save
11. waited about 4s until save button becomes disabled again.
12. check my branch, it is correct:
```
TIT	1	1	rtc9	figs-abstractnouns	κατὰ πίστιν
```
13. removed all words from original quote; highlighting correct (nothing is highlighted)
14. clicked save and checked my branch, it is correct.
```
TIT	1	1	rtc9	figs-abstractnouns		
```



**Second Test**

1. Starting from where test 1 left off, I refreshed page
2. everything is correct (orignal quote, OQ hereafter, is empty and nothing is highlighted)
3. copy/pasted κατὰ πίστιν into OQ
4. highlighting OK
5. click save; check repo branch... all OK
6. removed πίστιν  from OQ and clicked out; everything updated OK
7. clicked save; repo updated; everything looks good

**Comment by elsylambert** [comment]
he  Only difference we have in our test is that I am trying to highlight a greek word that was not highlighted previously.
-Copy and paste a Greek word into Original Quote that was not earlier highlighted in the scripture pane. The word gets highlighted in the scripture pane.
-Remove the Greek word from the Original Quote. The highlight stays.
At this point, if the user refreshes the page, the highlight is gone. But if the user saves the changes(Save button is enabled), the Changes at step 1 are saved(which is wrong cause the Greek word is not in the Original Quote section but gets saved)

So in your test steps no 5. if you add a greek word after "κατὰ πίστιν ἐκλεκτῶν Θεοῦ", the word will highlight. Then you remove the same word so that the Quote stays "κατὰ πίστιν ἐκλεκτῶν Θεοῦ".
Note that the Highlight on the Greek word stays and at this point, if you Click Save, The New greek word is added in the Original Quote.

**Comment by mandolyte** [comment]
Note 1: the data saved matches the value in the Original Quote text box, not the selection itself (which in this case does not match the value). So I think this is a "good thing" - that is, the data on the server that is saved is correct.

**Comment by mandolyte** [comment]
**Comment** @klappy 
The oddity I noticed is due to this line:

        // onQuote={onQuote} // disable until round trip is working

Since onQuote is undefined the second hook in useSelections.js never does anything (there's an if statement that checks if onQuote is defined).

I really don't know if this is related to issue 120, but thought it looked odd enough to mention.

**Comment by mandolyte** [comment]
**More** @klappy 

Today after replicating the problem, I further observed that adding or removing a space to the OrigQuote (OQ) text box and then clicking out does not fire any hooks.
This also happened when I removed Θεοῦ and clicked out. I expected the `useSelections` hook to do something, but nada.

Trace:
- onQuote is invoked in second useEffect in useSelections; but since undefined, it is never used:
```
  useEffect(() => {
    if (verseObjects && onQuote) {
      const _quote = helpers.quoteFromVerse({selections, verseObjects});
      onQuote(_quote);
    }
  }, [selections, onQuote, verseObjects]);
```
- onQuote passed to useSelections in SelectionContext.
- SelectionContext is used in ScriptureTable; but onQuote as a parameter is commented out. 
- onQuote is passed to ScriptureTable by ParallelScripture, but is commented out there as well.
- onQuote is passed to ParallelScripture by QuoteSelector (TCC) and is _not_ commented out.
- onQuote is passed to QuoteSelector by RowHeader (TCC).
- In RowHeader:
```
  const [quote, setQuote] = useState(_quote);
  useEffect(() => {
    setQuote(_quote);
  }, [_quote]);
```

**Looks like there are two hooks that will manage the quote state value. Since one is never invoked there are not two of them competing. However, they are defined much differently. Which is correct?**

**Comment by ancientTexts-net** [comment]
all RCL updated.  now, testable in the app:

testable in `1.1.1-beta.1`

https://deploy-preview-179--tc-create-app.netlify.app/

**Comment by ancientTexts-net** [comment]
Testable in `v1.0.0-beta.7`

https://deploy-preview-188--tc-create-app.netlify.app/

Features in this build:
- #148 Add resource
- #78 Scroll to new row after add/delete
- #171 Unable to save file in tW, tA, and OBS
- #120 Save action: app  needs to refresh the save action

.

**Comment by elsylambert** [comment]
Save works fine with Highlighting and un-highlighting the OriginalQuote.

**Comment by ancientTexts-net** [comment]
Testable on `develop`!  `v1.0.0-beta.7`

https://develop--tc-create-app.netlify.app/

Features in this build:

#148 Add resource
#78 Scroll to new row after add/delete
#171 Unable to save file in tW, tA, and OBS
#120 Save action: app needs to refresh the save action

**Comment by elsylambert** [comment]
Verified on translationCore Create - v1.0.0-beta.7. Save Action works as expected. Able to Highlight the OriginalQuote and remove the highlight when the OriginalQuote does not match. Looks good.
