### ISSUE TITLE
Content Validation for Translation Questions

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/tc-create-app#1201]
Similar to #1199 except for TQ resources

**Comment by elsylambert** [comment]
![Screen Shot 2022-04-06 at 4.32.40 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/abaac313-22e7-4b96-aab8-a94aa0b5dac9)

**Comment by elsylambert** [comment]
Works as expected in translationCore Create - v1.4.2 build 132-29815c0.

**Comment by elsylambert** [comment]
Tested in translationCore Create - v1.4.2 build 132-6493c98. Works fine.
