### ISSUE TITLE
Content Validation for Study Questions

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/tc-create-app#1202]
Similar to #1199 except for SQ resources

**Comment by elsylambert** [comment]
translationCore Create - v1.4.2 build 132-6493c98
![Screen Shot 2022-04-14 at 2.38.36 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/2b752bc1-7116-4ed7-9c73-d63f9474a2b8)

**Comment by mandolyte** [comment]
@elsylambert The "decoding" of the TSV was not being done per the TSV spec at https://forum.door43.org/t/parascriptural-tab-separated-value-format-specification-v2/870

**Comment by elsylambert** [comment]
Looks good in translationCore Create - v1.4.2 build 134-b098d13. Not seeing the Wrong number of tabbed fields error.
