### ISSUE TITLE
Content Validation for OBS Study Questions

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/tc-create-app#1207]
Similar to #1199 except for OBS-SQ resources.

Note that as of this writing, this one had validation errors and below is what the download looks like in Chrome.

![image](https://user-images.githubusercontent.com/1289437/158202339-62479b12-cd95-4685-9ea2-95ca1dc66bbf.png)

**Comment by elsylambert** [comment]
[https://app.zenhub.com/files/191973535/b13b3c63-bf09-4fd2-bc28-50860444196f/download](https://app.zenhub.com/files/191973535/b13b3c63-bf09-4fd2-bc28-50860444196f/download)

Wrong number of tabbed fields (expected 7)

**Comment by mandolyte** [comment]
Fix for 1202 also fixes this.

**Comment by elsylambert** [comment]
Looks good in translationCore Create - v1.4.2 build 134-b098d13. Not seeing the Wrong number of tabbed fields error.
