### ISSUE TITLE
Incomplete Information in CV file for PHP/COL en_tn

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#1209]
https://stage--tc-create-app.netlify.app/
Org- uW, lang- en, Resource- tN, file/Book- PHP and COL
Ran CV on Philippians and the CV file shows missing fields (book/chapter/OrigQuote etc) but user cannot figure out the location of the error as id and other Information is missing in the CV file.
![Screen Shot 2022-03-15 at 8.30.43 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/f7a9eaa7-5dbf-4318-95f5-a4afc0cc1905)

[https://app.zenhub.com/files/191973535/9fb8eb07-8dc7-46c5-9c3d-2572ecbdc917/download](https://app.zenhub.com/files/191973535/9fb8eb07-8dc7-46c5-9c3d-2572ecbdc917/download)
@mandolyte  Can you please take a look?

This is happening in Colossians as well.[https://app.zenhub.com/files/191973535/4869def0-188a-466f-94eb-1647f81bc95a/download](https://app.zenhub.com/files/191973535/4869def0-188a-466f-94eb-1647f81bc95a/download)

**Comment by mandolyte** [comment]
As for Colossians, I get no validation errors in prod, but I do get a couple in staging.

![image](https://user-images.githubusercontent.com/1289437/158438685-19af1a84-44a1-49f7-8271-007dc89a64d9.png)

**Comment by elsylambert** [comment]
@mandolyte Staging is also using the Prod server(git.door43.org), Then how come the CV file is different if its running on the same user branch?

**Comment by elsylambert** [comment]
Here is my user branch: https://git.door43.org/unfoldingWord/en_tn/src/branch/ElsyLambert-tc-create-1/en_tn_51-PHP.tsv
https://git.door43.org/unfoldingWord/en_tn/src/branch/ElsyLambert-tc-create-1/en_tn_52-COL.tsv
