### ISSUE TITLE
Data file corruption when opened from the drawer- switching files

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#1211]
- Open tN, select a book.
- From the drawer, select a book that does not exist in your user branch(which is not opened before)
- The file selected in step 2 is corrupted with the data(contents) from the previously opened file.![Screen Shot 2022-03-15 at 1.57.34 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/59a5bc0c-51e9-4b75-b878-9f7243b926bd)

**Comment by birchamp** [comment]
@elsylambert Looks like you saw this back in March, but this is for TN.  We'll wait and retest after #1243 has be tested.
