### ISSUE TITLE
Add Resource License Information

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/tc-create-app#122]
Before we go into external production we need to add an information pop up that shows the license of each resource, particularly the reference sources pulled in, like the Scripture Pane.  For example, see the terrible mockup below:
![Screen Shot 2020-04-15 at 10 31 04 AM](https://user-images.githubusercontent.com/107731/79349946-d8ac7900-7f04-11ea-9e43-b1dead2ac553.png)

I think a little information icon next to each resource name would work, that could either link *directly to the LICENSE* file on DCS, or it could pull the data in and render it in a pop up.

**Comment by birchamp** [comment]
Could get the name of the license from the manifest file.  And then the file itself.

DoD: When user hovers over icon, license title is shown in a tool tip. Clicking it will take the user to the license file on DCS.

**Comment by mandolyte** [comment]
Just to flesh out the requirements...
There is an MUI icon for information, I'll use it (assuming we can size it appropriately):
![image](https://user-images.githubusercontent.com/1289437/79747855-68be3a00-82da-11ea-97f7-0e3397f9d456.png)

There is an MUI chip that has the behavior described and I can use the above icon as its visual:
![image](https://user-images.githubusercontent.com/1289437/79748023-ae7b0280-82da-11ea-8b30-617cd75c1f5f.png)

I can add a tooltip that says something like: `License: CC BY-SA 4.0` -- in this case from [here](https://git.door43.org/unfoldingWord/en_tn/src/branch/master/manifest.yaml#L382).

And which, when clicked, will open in a new browser tab:
https://git.door43.org/unfoldingWord/en_tn/src/branch/master/LICENSE.md
@birchamp @jag3773 Look OK?

**Comment by mandolyte** [comment]
@klappy and I worked on a different approach this morning... here is a proposal.
1. First, note that the bar at the top has a translation icon to the left and the name of the repo as the centered text.
![image](https://user-images.githubusercontent.com/1289437/79981780-401d7800-8473-11ea-9ff2-9ec00b1b7ac9.png)
2. Second, notice that whether you click the translate icon or the text, they both link to the article. In other words, they both do the same thing.
3. So our proposal is that we replace the translate icon with a license icon.
4. This icon would be the one that corresponds to the manifest rights strings. The icons would be taken from [here](https://creativecommons.org/about/downloads).
5. Thus if the manifest has `rights: 'CC BY-SA 4.0'`, then icon shown might be 
![image](https://user-images.githubusercontent.com/1289437/79982419-4cee9b80-8474-11ea-8a17-811944d62ab7.png) and the tooltip would say something like "View CC BY-SA 4.0 License".

_This would be done by creating a new component in the `scripture-resources-rcl` project, making it available to any of our projects._

This approach does assume that all of our licenses are some Creative Commons variant.
@jag3773 @birchamp @elsylambert

**Comment by jag3773** [comment]
Sounds good but I would still prefer the (i) icon as it's maximally flexible...

**Comment by klappy** [comment]
This should be available to QA test in release `0.9.0-rc.1` on the develop deployment.
https://develop--tc-create-app.netlify.app/

**Comment by elsylambert** [comment]
Verified in the release 0.9.0-rc.1.

**Comment by elsylambert** [comment]
Passing this issue, #138 will resolve the Licence Tool tip issue.
