### ISSUE TITLE
 Unable to switch files from the drawer

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#1225]
Open tCC>select org/Choose any resource/language.
Open a file.
From the drawer, choose another file. Note that: the file does not gets switched.

**Comment by ancientTexts-net** [comment]
@Joel-C-Johnson @jincypjose 
Can we please review on Monday?

I will tag you as reviewer please :))) 😊

CC: @klappy @birchamp

**Comment by ancientTexts-net** [comment]
@birchamp @Joel-C-Johnson @jincypjose 

Did ya'll see I was able to make progress with this last Friday?
Should be ready for review please :)))

**Comment by klappy** [comment]
Thanks @ancientTexts-net!! Reviewed the Pr and tested the deploy preview! Looks like you caught and squashed the bug! 🪳🪰

**Comment by klappy** [comment]
@elsylambert Looks like this is addressed via the attached PR. The build should be updated on Develop soon for you to retest.
