### ISSUE TITLE
Failing to create a new file in the user branch

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#1243]
translationCore Create - v1.4.1 build 118-a9b2333
Open tCCreate, Select org- translate_test and lang- es-419, select resource tN.

Select any book/.tsv file for which you do not have a file already created in your master. eg if you do not have Gen.tsv in your existing user branch, select Gen. 
![Screen Shot 2022-04-14 at 6.21.13 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/cfe25280-16d3-4568-bf22-b8c44cf2f21c)

**Comment by birchamp** [comment]
@richmahn we're probably going to need your help on this.

**Comment by elsylambert** [comment]
@Joel-C-Johnson @klappy  Testing on translationCore Create - v1.4.2 build 142-498b6eb. After I deleted my user branch on es-419_tn and en_tn, I was able to open Gen.tsv but Not able to open tA or TW. Not working for ru GL, even after deleting the branch(except for tit.tsv).
Worked for the following:![Screen Shot 2022-04-26 at 9.12.37 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/158e8bed-fb77-4073-8a49-5ef72d2634c8)
and TITUS![Screen Shot 2022-04-26 at 9.18.00 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/e8bb7061-31c6-4ddc-bc2a-74c3c10756c3)
Failing for the following :
![Screen Shot 2022-04-26 at 9.20.33 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/eb7525f4-b628-4b7c-b9fc-c6c13468693b)
Seeing this behaviour when target is copied from the previous file:
![Screen Shot 2022-04-26 at 9.25.58 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/d633c5a3-373c-4925-992c-4ecf45ac746e)
![Screen Shot 2022-04-26 at 9.38.36 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/a5b6445a-dfc8-42b2-a7a3-e95a22deeecb)

**Comment by Joel-C-Johnson** [comment]
The empty source content is solved in this PR- (https://deploy-preview-1257--tc-create-app.netlify.app/)
Works as expected

**Comment by elsylambert** [comment]
Issue is resolved in translationCore Create - v1.4.2 build 143-d3d292a.
Now, GL user can create a new file in the user branch. Tested with es-419 and ru GLs and TSVs and MD Resources (tA and tW) works fine as expected.
