### ISSUE TITLE
Study Notes files are not opening in tCCreate

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#1248]
Found that except for Titus, other books are not opening(endless spinner) or getting corrupted on the target side with content from previously opened book(Titus)
Org-unfoldingword, en_sn
This is happening in Production as well translationCore Create - v1.4.1 build 118-a9b2333![Screen Shot 2022-04-19 at 3.14.35 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/cdac470b-b111-4a43-99a1-20afb73f0b8c)
Steps:
- Open tC create, select Org-unfoldingword, resource- en_sn ,lang -en and select any book. 
- Note that you ll see a blank screen with a spinner. 
Titus works. If you open any other book from the drawer, the book opens with TIT content overwritten on the target side.
![Screen Shot 2022-04-19 at 3.15.50 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/128c5bdf-1eca-417b-b682-fa8c68092016)

User branch after opening 3JN:
https://git.door43.org/unfoldingWord/en_sn/src/branch/ElsyLambert-tc-create-1/sn_3JN.tsv 
![Screen Shot 2022-04-20 at 11.03.50 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/39a15daf-2866-416a-8987-e1ce7c144810)

**Comment by mandolyte** [comment]
Notes:
- Selected Matthew (works... no endless spinner)
- Switched to Mark (worked as expected)

@birchamp  @elsylambert I think this is fixed now...

**Comment by elsylambert** [comment]
Works fine in Production translationCore Create - v1.4.2 build 145-8501031 as well as in Develop.
