### ISSUE TITLE
Add User's Organizations to Gitea RCL 

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/tc-create-app#125]
- [x] Implement core functions for user's organizations.
    - API endpoint https://git.door43.org/api/swagger#/organization/orgListCurrentUserOrgs
    - filepath for code: `src/core/gitea-api/users/orgs.ts`
    - Function name: `getCurrentUserOrgs()`
    - Add `orgs.md` to document example code.
- [x] Implement components for organizations list/selection (with create new link).
    - Organization.js: Component to render a single organization object.
        - port the code from `Repository.js`.
        - accepts link or organization object.
        - if link is provided fetches like repository url does.
        - onOrganization callback on click like onRepository.
        - Add .md to document example code.
    - Organizations.js: Component to render a list of organization objects.
        - port the code from `Repositories.js`.
        - Add .md to document example code.
    - CurrentUserOrganizations.js: Component to fetch and render the user's organizations.
        - Similar to `repositories/Search.js`.
        - requires `authentication` in config somehow, renders empty array if not logged in.
        - fetch `currentUsersOrganizations` from core.
        - Renders `Organizations` component once user's organizations are fetched.
        - Add .md to document example code.

**Comment by birchamp** [comment]
DoD: Core functionality and components to see the logged-in user's organization(s).

**Comment by klappy** [comment]
Should be QA testable via gitea-react-toolkit `1.0.0-rc.4`
### Testable Components
- [Organization](https://gitea-react-toolkit.netlify.app/#!/Organization%20/Organization)
- [Organizations](https://gitea-react-toolkit.netlify.app/#!/Organizations%20/Organizations)
- [CurrentUserOrganizations](https://gitea-react-toolkit.netlify.app/#/Organizations%20?id=currentuserorganizations)

**Comment by elsylambert** [comment]
@klappy Would the changes be reflected on https://develop--tc-create-app.netlify.app/ ?

**Comment by klappy** [comment]
Not yet, all of these changes were building the features into the RCL.

**Comment by elsylambert** [comment]
Tested User Organization on the RCL. User with organization looks good. Need some refinement written up in separate issues.

**Comment by elsylambert** [comment]
Verified in 0.9.0-rc.4.
