### ISSUE TITLE
Parallel Scripture viewer is not opening up in RowHeader for OBS-Helps TSVs

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#1265]
translationCore Create - v1.4.2 build 145-8501031.
Parallel scripture is not loading up for TSV Resources except for tN, tWl and tQ. So basically OBS helps(TSV format),

![Screen Shot 2022-04-29 at 10.19.13 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/97c9f98f-4f63-4c02-86ba-6b095c9058b8)

![Screen Shot 2022-04-29 at 10.19.20 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/fa4f6c07-ed05-4545-a899-1ec7b6432cfa)

**Comment by mandolyte** [comment]
@elsylambert why would you expect scripture references to be shown for OBS resources? AFAIK, there are no scripture references that could be used to facilitate that.
