### ISSUE TITLE
SPIKE: Allow editing within the new row dialog

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#1277]
What tasks will be needed to implement editing within the new row dialog 
Will taking this approach increase tech debt rather than working within the edit fields in the row presently?

**Comment by BincyJ** [comment]
@superdav42

**Comment by superdav42** [comment]
With [the change ](https://github.com/unfoldingWord/datatable-translatable/pull/99/files#diff-e9f6ca41435197af0d63e9b5e82c88a422ddea9e23b8f972f771f7903532be91R79)to add the autoloader component being about 20 lines of code, I would say the tech debt is trivial and not a concern. Making the other fields editable will be straightforward.
