### ISSUE TITLE
Delay autosave until first save/branch created

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#1278]
In order to reduce unnecessary branches we want to delay creating the branch until the user make the first save to their changes.  This means that autosave won't be available until the user makes a successful save. That is an acceptable compromise.  Adjustments will need to be made to check that a branch exists and not do an autosave until it does.

DoD:
--- 
Branch isn't created until saved. Autosave doesn't give errors even though the branch doesn't exist.

**Comment by birchamp** [comment]
@superdav42 is this basically a dup of 1330 now?

**Comment by birchamp** [comment]
OH! I just noticed the 'Autosave' piece of this.  So has this been implemented?

**Comment by superdav42** [comment]
> OH! I just noticed the 'Autosave' piece of this. So has this been implemented?

Yes

**Comment by elsylambert** [comment]
This works fine in translationCore Create - v1.6.0 build 159-84e2b7a.
