### ISSUE TITLE
Properly Handle U+2019 in Greek text

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#128]
U+2019 right single quote ` ’ ` is used in Greek text to signify "elison" (dropping the final vowel before a leading vowel in the next word).  Currently, the right single quote breaks highlights because it's typically stripped out in English.  
*Note:* [This article ](http://www.opoudjis.net/unicode/gkdiacritics.html#apostrophe)mentions that you'd "you have to be pretty brain-damaged to use single quotes in polytonic Greek"

**Comment by birchamp** [comment]
Confirm that U+2019 is the character used in the UGNT. 
Titus 1:13 TW check exhibits this @birchamp

**Comment by klappy** [comment]
This may have to sit in QA watch for sometime but this is currently functioning as described in `0.9.0-rc.1`

<img width="1764" alt="Screen Shot 2020-05-19 at 12 57 49 PM" src="https://user-images.githubusercontent.com/118073/82355682-8b726a00-99d0-11ea-952c-38df6b6eb5d1.png">
