### ISSUE TITLE
Release 1.5.0

### ISSUE THREAD

**Issue by BincyJ** [unfoldingWord/tc-create-app#1302]
- [x] bump the version the PRs 
- [x] tag the version when merged. 

#### Prepare Staging 
- [x] PR to remove RC from the version number
  - start in new branch (e.g., `zpp-remove-rc-1.5.0`); 
  - edit `package.json` for version (e.g., v1.5.0); commit; publish
  - `git tag` (e.g., v1.5.0);    `git push --tags`
  - create PR from `remove...` branch --> `develop`;  connect this PR to the "RELEASE" issue
  - merge this PR (even if you merge it yourself, please use PR and do not commit directly to the develop branch)
- [x]  Release Branch:
  - pull latest develop changes
  - create new branch: release branch for version 1.5.0 from develop
  - publish release branch to github
- [x] Create staging Netlify link (PROD Data)
  - create new PR from `v1.5.0` --> `STAGE`; connect to the release issue
  - walk through happy path on deploy preview
  - merge 

Definition of Done
- [x]  QA signs off on specific build in regression testing: current for v1.5.0, build number: 
- [x]  Update changelog
- [ ]  create draft release on github for translationCore
- [x]  Attach the github action builds (same build as QA signed off) to the draft release as assets
- [x]  Update Release Notes to the draft release
 after everyone has reviewed translationCore draft release, make it an official release.
- [x]  Confirm all links to the release
-  github release page - https://github.com/unfoldingWord/tc-create-app/releases
-  door43 forum

**Comment by BincyJ** [comment]
@mandolyte @Joel-C-Johnson @elsylambert , fyi

**Comment by birchamp** [comment]
Release notes @elsylambert :

## What's New? 
We are pleased to announce that tC Create 1.5 is now available online at https://create.translationcore.com/.

## Features and Enhancements:
- The repeated fields for Chapter, Verse, and Support Reference now have dropdowns with the ability to look up the previously used data. Users can enter custom text as well. [#76](https://github.com/unfoldingWord/tc-create-app/issues/76)
- Users can now make changes within the dialog for a new row. [#1166](https://github.com/unfoldingWord/tc-create-app/issues/1166)
