### ISSUE TITLE
Reference drop-down in TWL 

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#1307]
Issue
---
Currently when a user changes the chapter, verse, or reference (tsv7) field, the source side turns empty, but the target side retains the ID of the original record. I believe that we switched IDs to be unique per file a while back.  Records should be aligned on ID only, not on verse reference and ID.  This way if a GL needs to change what verse a note is in they will see the English source record even though it is in a different verse. 

DoD
---
Changing the chapter or verse in any TSV shouldn't cause the source side to be empty. It should parallel with the original source record. 

Details
---
It appears that the source is matched according to both the reference and the ID.  It should _only_ be matched by the ID.  The reference needs to be removed as a keyed field.

For TWL, there is a drop-down for Reference Field,
I selected a different reference from the list. Note that the source side goes empty![Screen Shot 2022-06-09 at 4.53.47 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/0845bc6f-1589-4093-957e-1f85f8db1fb5)

**Comment by mandolyte** [comment]
@birchamp @klappy @elsylambert 
This demonstration sort of implies that we should not permit updates to the "key" files in the TSV files. Same things happens in TN:
![image](https://user-images.githubusercontent.com/1289437/173350482-10858439-0c33-443c-a974-117ddeae1be8.png)

Without pouring over the code, I seem to remember that the "key" is BCV+ID (for TN); for TWL, I suppose that would be REF+ID.

Does this need to be addressed before we release 1.5?

**Comment by mandolyte** [comment]
Interesting... it does **NOT** create a new row. But is placed where it was added, retaining the values that were unchanged on the target side.
![image](https://user-images.githubusercontent.com/1289437/173352588-84d72dcd-8deb-4045-9888-809a651c2f59.png)

**Comment by mandolyte** [comment]
Then if I revert it back, it re-aligns perfectly with the source side again:
![image](https://user-images.githubusercontent.com/1289437/173353067-4351b059-d732-4359-bca0-c22b3b1b613d.png)

**Comment by mandolyte** [comment]
But, of course, empty rows in the target are not written out. So no harm done.

**Comment by birchamp** [comment]
@elsylambert This does need to be fixed in future for GLs, but it isn't necessary for us to fix before the 1.5 release.  I'm moving this issue to the team backlog

**Comment by elsylambert** [comment]
translationCore Create - v1.7.0 build 165-900bcf1.
Not seeing this issue in twls on editing the Reference from the drop down. Note that the reference changes to the selected verse and updates the file with it and the same id.
![Screen Shot 2022-09-14 at 1.34.34 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/7c35dab6-3667-46ba-9601-ec87eb5e9018)
