### ISSUE TITLE
Implement Custom Hook and ContextAPI for Organization

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/tc-create-app#132]
## Gitea React Toolkit

- [x] `useOrganization.js`: Custom hook to use when needing an organization.
    - port the code from `useRepository.js`.
    - create helpers (if needed) similar to `repository/helpers.js`.
    - `props`: the expected input.
        - `organization`: the externally managed state passed in.
        - `onOrganization`: the external function to update organization state.
        - `config`: the config object used,
        - `authentication`: the authentication object used for the fetch requests.
    - `state`: the current `organization` (not internal state but passed in).
    - `actions`: actions array for the custom hook to change state.
        - `update`: which passes this on to onOrganization.
        - `list`: async request that returns organizations of the user w/ `getCurrentUserOrgs`.
        - `close`: updates the current `organization` to nothing w/ empty `update()`.
    - `PropTypes`: list the props, types and comments.
    - `useOrganization.md`: document and example.

- [ ] `Organization.context.js`: Context API Provider and Consumer for Organization.
    - Mimic thin wrapper approach of `Repository.context.js`.
    - Same props, return, and PropTypes as custom hook in `useOrganization.js`.
    - `Organization.context.js`: document and example.

**Comment by klappy** [comment]
@RoyalSix When preparing `1.0.0-rc.4`I noticed that this demo doesn't appear to render anything. I'm wondering what we can do to make this testable by QA:
https://gitea-react-toolkit.netlify.app/#!/Organization%20/UseOrganization

**Comment by klappy** [comment]
This should be QA testable with release `1.0.0-rc.5`

### Testable Components:
- [OrganizationContextProvide](https://gitea-react-toolkit.netlify.app/#!/Organization%20/OrganizationContextProvider)
- [UseOrganization](https://gitea-react-toolkit.netlify.app/#!/Organization%20/UseOrganization)

**Comment by elsylambert** [comment]
Looks good at the RCL level,
