### ISSUE TITLE
Implement Organization in App State/Reducer/Actions

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/tc-create-app#133]
- `state.reducer.js`
    - case for `set_organization`
    - add `organization` to case `resume_state`
- `useStateReducer.js` add prop `organization` to:
    - props
    - _defaults
    - `setOrganization`: create action to handle dispatch
    - `setTargetRepoFromSourceRepo`
        - add `organization` to props
        - remove conditional and use `editSource`'s logic
        - `owner` set to `organization.username`
    - add `setOrganization` to `actions` array
- `App.context.js`
    - add `organization` to `AppContextProvider`'s props
    - pass to `useStateReducer`
    - add to deconstructed state
    - pass into `setTargetRepoFromSourceRepo`
- `App.js`
    - add `OrganizationContextProvider` between authentication and repository providers.
    - add to `resumeState()`

The above should be >90% of the work there are likely a few places that might need updating.

**Comment by klappy** [comment]
Should be testable via `0.9.0-rc.3`

**Comment by elsylambert** [comment]
0.9.0-rc.4. Looks good. Organization related issues are written up separately.
