### ISSUE TITLE
Implement Branch Workflow in Stepper 

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/tc-create-app#134]
- [x] Swap Resource and Language selection steps in Stepper.
    1. Login/User
    2. Organization Selection
    3. Resource Selection
    4. Language Selection
    5. File Selection
- [x] Implement Organization selection in Stepper.
    - add `state, actions, component` from `useContext(OrganizationContext)`.
    - add step and condition for `organization` just like resource/repository.

**Comment by RoyalSix** [comment]
#137

**Comment by klappy** [comment]
Should be testable via `0.9.0-rc.3`.

**Comment by elsylambert** [comment]
Stepper works fine if the user starts with the login> can see the Organization >select the resource> and then language >and finally the file.

Fails when the user clicks on the stepper itself and surpasses one or two steps in the stepper.
Please review the screen recording:
[Stepper-organisation.mp4.zip](https://github.com/unfoldingWord/tc-create-app/files/4718125/Stepper-organisation.mp4.zip)

**Comment by elsylambert** [comment]
Passing this issue for Positive testing (Happy Path).
