### ISSUE TITLE
Release v1.6.0

### ISSUE THREAD

**Issue by BincyJ** [unfoldingWord/tc-create-app#1346]
#### Prepare Staging 
- [x] PR to remove RC from the version number
  - start in new branch (e.g., `zpp-remove-rc-1.6.0`); 
  - edit `package.json` for version (e.g., v1.6.0); commit; publish
  - `git tag` (e.g., v1.6.0);    `git push --tags`
  - create PR from `remove...` branch --> `develop`;  connect this PR to the "RELEASE" issue
  - merge this PR (even if you merge it yourself, please use PR and do not commit directly to the develop branch)
- [x]  Release Branch:
  - pull latest develop changes
  - create new branch: release branch for version 1.4 from develop
  - publish release branch to github
- [x] Create staging Netlify link (PROD Data)
  - create new PR from `v1.6.0` --> `STAGE`; connect to the release issue
  - walk through happy path on deploy preview
  - merge 

Definition of Done
- [x]  QA signs off on specific build in regression testing: current for v4.1.0, build number: 
- [x]  Update changelog
- [x]  create draft release on github for translationCore
- [x]  Attach the github action builds (same build as QA signed off) to the draft release as assets
- [x]  Update Release Notes to the draft release
 after everyone has reviewed translationCore draft release, make it an official release.
- [x]  Confirm all links to the release
-  github release page - https://github.com/unfoldingWord/translationCore/releases
-  door43 forum
- [ ] Inform Sam, Vipin, Abel, Dima about release 
- [ ] Announce on Zulip

**Comment by BincyJ** [comment]
@birchamp , @Joel-C-Johnson , @elsylambert fyi

**Comment by BincyJ** [comment]
## What's New?
We are pleased to announce that tC Create 1.6 is now available online at https://create.translationcore.com/.
## New Features:
- User branches used to be created immediately when a user opened a file. Now branches in DCS will not be created until a user saves their work. [1320](https://github.com/unfoldingWord/tc-create-app/issues/1320)

**Comment by birchamp** [comment]
@elsylambert @Joel-C-Johnson Here's the release note:
## What's New?

We are pleased to announce that tC Create 1.6 is now available online at https://create.translationcore.com/.

## New Features:

- User branches used to be created immediately when a user opened a file. Now branches in DCS will not be created until a user saves their work. [1320](https://github.com/unfoldingWord/tc-create-app/issues/1320)

**Comment by elsylambert** [comment]
@birchamp  I edited the one Bincy posted ^^
