### ISSUE TITLE
\qs tagged words in USFM are not shown in the scripture pane

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#1364]
Issue:
---
A number of verses in Psalms in the ULT end with 'selah', but that word is not displayed in tC Create.  The word is set off with the \qs ... \qs* marker.  

DoD:
---
Verses with 'selah' within \qs should display the word and the highlight should work as well. 

Details
---
In Psalm 3:2 for instance the ULT has:
```
\qs 
\zaln-s |x-strong="H5542" x-lemma="סֶלָה" x-morph="He,Tj" x-occurrence="1" x-occurrences="1" x-content="סֶֽלָה"\*\w Selah|x-occurrence="1" x-occurrences="1"\w*\zaln-e\*
\qs*
```
This line doesn't display in tC Create but it is shown in tC.

**Comment by elsylambert** [comment]
translationCore Create - v1.6.0 build 164-06992b7. Looks good.
![Screen Shot 2022-08-31 at 9.29.59 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/b4929c10-df0c-4460-bde5-c6056e21aced)
