### ISSUE TITLE
Reference ranges show the text in the scripture viewer

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#1366]
When a reference range in TSV7 refers to multiple verses it needs to display the text of all of those verses.  Notes with reference ranges should function as normal - editing the range to be a single verse reference, editing a single reference to be a range, creating a new note with a reference range, and highlighting. 

A spike was done on this #718

DoD:
---
If there is a reference range in the reference field then all the verses in the range should be displayed and the note should have all of the functionality of a single reference note.

Details
---
Here's the mockup for gatewayEdit. tC Create should be similar.

![CleanShot 2022-08-25 at 10.15.42.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/5dfb3bc8-d927-4519-a84f-ef57106947c0
)

**Comment by mandolyte** [comment]
There is a JSON file with the verses per chapter per book in tc-create.

See `/src/core/bcv.json`

**Comment by birchamp** [comment]
This is blocked by #1438

**Comment by elsylambert** [comment]
translationCore Create - v1.8 build 192-d709261. Works fine and looks good. Tested also with #1438 where user can enter a verse range.![Screenshot 2022-11-30 at 9.33.40 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/7d46244d-135b-4d86-bb34-b43b943bc1c1)
