### ISSUE TITLE
License tool-tip on the chip shows Type unknown 

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#138]
0.9.0-rc.1.
This one is part of issue tc-create#122.

The tool tip on the License icon(i) shows as shown in the snapshot below:
![Screen Shot 2020-05-14 at 2.20.03 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/37d3e1af-96ac-4cbb-b446-7281f2d3339b)
Clicking on the icon(i), it goes to the license page in a new tab. which is fine as per the DoD on #122.

**Comment by klappy** [comment]
Should be QA testable in `v0.9.0-rc.2`.

**Comment by elsylambert** [comment]
Looks good in v0.9.0-rc.2. The tool tip shows as View License on the chip.
