### ISSUE TITLE
Release v 1.7

### ISSUE THREAD

**Issue by BincyJ** [unfoldingWord/tc-create-app#1382]
#### Prepare Staging 
- [x] PR to remove RC from the version number
  - start in new branch (e.g., `zpp-remove-rc-1.6.0`); 
  - edit `package.json` for version (e.g., v1.6.0); commit; publish
  - `git tag` (e.g., v1.6.0);    `git push --tags`
  - create PR from `remove...` branch --> `develop`;  connect this PR to the "RELEASE" issue
  - merge this PR (even if you merge it yourself, please use PR and do not commit directly to the develop branch)
- [x]  Release Branch:
  - pull latest develop changes
  - create new branch: release branch for version 1.7 from develop
  - publish release branch to github
- [x] Create staging Netlify link (PROD Data)
  - create new PR from `v1.6.0` --> `STAGE`; connect to the release issue
  - walk through happy path on deploy preview
  - merge 

Definition of Done
- [x]  QA signs off on specific build in regression testing: current for v1.7 build number: 
- [x]  Update changelog
- [x]  create draft release on github for translationCore
- [x]  Attach the github action builds (same build as QA signed off) to the draft release as assets
- [x]  Update Release Notes to the draft release
 after everyone has reviewed translationCore draft release, make it an official release.
- [x]  Confirm all links to the release
-  github release page - https://github.com/unfoldingWord/translationCore/releases
-  door43 forum
- [ ] Inform Sam, Vipin, Abel, Dima about release 
- [ ] Announce on Zulip

**Comment by BincyJ** [comment]
@Joel-C-Johnson, @elsylambert  is 1.7 ready for release

**Comment by BincyJ** [comment]
@elsylambert / @birchamp Please review the  release notes and give a final go-ahead for releasing 1.7:

**tCCreate 1.7** 

**What's New?**
We are pleased to announce that tC Create 1.7 is now available online at https://create.translationcore.com/.

**New Features:**

- Enhancements to cursor navigation to avoid  unnecessary scrolling across the app [1089](https://github.com/unfoldingWord/tc-create-app/issues/1089) ; [1088](https://github.com/unfoldingWord/tc-create-app/issues/1088)

- A pop up message now informs users to update their work to the latest master file whenever their branch is more than two weeks out of date.[1066](https://github.com/unfoldingWord/tc-create-app/issues/1066)

- Hebrew scripture is now displayed in a font that is easily readable. [1151](https://github.com/unfoldingWord/tc-create-app/issues/1151)



Bug fix: 


Source side data appears blank upon editing the reference drop-down in TWLs  upon changing to a different chapter or verse. https://github.com/unfoldingWord/tc-create-app/issues/1307 1307

**Comment by elsylambert** [comment]
@BincyJ @birchamp I edited the notes and added two more bug fixes that were field reported.

**Comment by elsylambert** [comment]
translationCore Create - v1.7.0 build 167-c63d59b looks good on Staging server and good to move to Production. @Joel-C-Johnson
