### ISSUE TITLE
Sort filter drop down with Intro first. 

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#1394]
A while back we resorted the filter drop down to be in alphabetic order.  This puts "Intro" records at the bottom of the filter drop down list.  Users would like "intro" to come at the beginning of the list

DoD:
----
When filtering "Intro" comes at the top of the dropdown instead of the bottom of the list.

Details:
---
![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/971197f9-239f-44b4-9023-455a0c0c69ff)

**Comment by elsylambert** [comment]
Looks good in  - v1.10 build 228-f43ba9b.
![Screenshot 2023-02-15 at 10.37.50 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/9c898313-412f-4947-ab7e-c32d3188f648)
