### ISSUE TITLE
Forward Delete does not enable the Save button

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#1399]
Windows Keyboard: Delete key or Selecting text and then using Delete key does not enable Save button.

Mac keyboard : fn+Delete 

Problem: tCC does not detect that the text has been edited when the keystroke is specific as mentioned above but it does when Delete(Mac) or Backspace (Win) is used to delete text.

**Comment by elsylambert** [comment]
Which build is it in fixed in? @Joel-C-Johnson . I do not see it working in translationCore Create - v1.7.1 build 169-feb61ad.

**Comment by Joel-C-Johnson** [comment]
Sorry. I couldn't find what happened to the code. I have released a new release (markdown RCL and datatable RCL) and updated in the tC create
