### ISSUE TITLE
Disable Auto Save

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/tc-create-app#1417]
This decision was reached after some investigation and discussion. Given the number of issues that have been raised for it and the fact that it isn't being used as expected, then the following:

- For now, disable the feature completely in tc-create
- in the future, if we decide to try again, then try to make it a re-useable component that any app can use.

Some notes on an auto-save component:
- the app must have complete control over what is being saved and the key used to identify it
- the app must be able to clear the auto-saved when needed
- as now, the data must be written to the browser's indexedDB and the app should be able to name the store as it wishes.

@birchamp does the above capture things?

**Comment by BincyJ** [comment]
@Joel-C-Johnson , please merge changes for QA review

**Comment by elsylambert** [comment]
translationCore Create - v1.8 build 183-ca725ce. tCC is no longer autosaving the edits as expected. This means that users must click on Save button to save the edits done to the file.
