### ISSUE TITLE
Missing space between some of the Original language text (Greek) breaks the highlighting 

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#142]
There are a bunch of places where the space between two Greek words are missing in the Scripture Pane, which breaks the highlights in the scripture pane. 

This might be a content issue in bg server, as it is outdated and might be fixed by an update from the Production server.

Here is an example from 2 Timothy:
![Screen Shot 2020-05-28 at 11.05.15 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/15fb6289-be2c-44db-b58c-841da0e6f878)

**Comment by elsylambert** [comment]
@richmahn Can you please notify when bg server is updated with the latest content? I will verify if this is a content or a tC create issue after that. Thanks.

**Comment by ancientTexts-net** [comment]
Dear @elsylambert 

I am NOT fluent in USFM yet...  but you are correct there is SOME difference between "bg" server and PROD

Specifically, it looks like the \k-s milestone is not terminated at 2 Tim 1:1 ?  between της and εν

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/8f402a3a-4fe8-4f90-8bac-ce2bea187445)

**Comment by richmahn** [comment]
@elsylambert Working on that now.

**Comment by richmahn** [comment]
@elsylambert bg.door43.org has been updated. Please check.

**Comment by elsylambert** [comment]
Looks good now after the upgrade. Not seeing the highlights breaking.
