### ISSUE TITLE
Prevent users from opening new TSV7s if TSV9s exist in repo

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#1429]
Users should be informed that their Translation Notes file is in the previous format (TSV9) and that they can not continue.

Once the en_tn source repo has been converted to TSV7 there are 3 possibilities:
1) TSV9 files exist in the target repo user or master branch and the user should be prevented from continuing (source: TSV9 ≠ target: TSV7) 
2) TSV7 files exist in the target repo (user or master branch) and the user should continue as normal (source: TSV7<->target: TSV7)
3) No files are present in the target repo. Create a new TSV7 file in the target user branch (source: TSV7->target: TSV7)

"tC Create cannot continue to open this file because it is in an outdated format.  Please contact your administrator to update the repository's files to the latest format."

DoD:
---
If a repo has TSV9 files in the top-level directory or user branch they should be informed and not be allowed to continue if the source (English) is TSV7.

**Comment by birchamp** [comment]
Check the filenames in the manifest to see if they are the new style.  gE is already distinguishing between TSV9 and TSV7 so it may be helpful to see what was done there.

**Comment by elsylambert** [comment]
translationCore Create - v1.8 build 190-5da41d8.
1. Works as expected. tested using translate _test which had TSV9 old format files. When user tried to open the files, error message pops up like shown below preventing the user to open the old format files:
![Screenshot 2022-11-29 at 8.59.40 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/b150cba1-e146-4e87-9d7f-69f1db68c4b4)

2. Tested using TEST_QA es-419_tn TSV7 format. Master was in TSV9, user was able to create target file by editing and saving the file in TSV7 format. Looks good.
3. Looks good, tested with the ^^ above org and repo. User was able to create fresh user branch in TSV7 format files.

**Comment by elsylambert** [comment]
translationCore Create - v1.8 build 192-d709261. Still seeing the problem that after I deleted my user branch(which had old TSV9 files), I am unable to open the file in new format and seeing the error message.
![Screenshot 2022-11-30 at 9.14.49 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/25b1da56-c962-4999-b653-a4ab002335b0)

**Comment by elsylambert** [comment]
translationCore Create - v1.8 build 192-d709261. No longer seeing the problem with the warning pop-up after deleting old format branch.
