### ISSUE TITLE
Enter verse range in the reference field

### ISSUE THREAD

**Issue by BincyJ** [unfoldingWord/tc-create-app#1438]
Users should have the ability to enter reference range in the reference field

DOD:
If a user enters a reference range in the reference range field, then, the parallel scripture reflects the scripture text as per the range selection.

**Comment by elsylambert** [comment]
translationCore Create - v1.8 build 192-d709261. Works as expected. If users enters a verse range like 2:1-2; 3:1-2: 4:1, the parallel scripture viewer displays the verses correctly for that specific row.
![Screenshot 2022-11-30 at 9.26.24 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/bb1cce65-efe2-48ff-9f9d-3db60682e039)
