### ISSUE TITLE
Support Reference drop- down in Rows shows full rc link

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#1441]
Support Reference drop- down in Rows shows full rc link instead of Support Reference name.
![Screenshot 2022-11-16 at 11.17.31 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/85da79b8-1429-4164-bc3f-210528f6ae12)
Related to #1440

**Comment by birchamp** [comment]
@elsylambert test the type ahead to see if it finds the name of the figure of speech.

**Comment by elsylambert** [comment]
translationCore Create - v1.8 build 190-5da41d8. Support Reference drop-down does find the name of the figure of speech on typing, which means it works fine. As mentioned by Cecil, Support Reference would display the full rc link as a result of the TSV7 format. So closing this issue.
