### ISSUE TITLE
Content Validator showing error 950 for language code.

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#1449]
translationCore Create - v1.8 build 183-ca725ce.
With the new TSV7 format, CV is showing error 950"tC cannot yet process '*' language code".
![Screenshot 2022-11-18 at 1.28.20 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/d4abd391-9d51-4091-91cc-d8403814c35f)

**Comment by mandolyte** [comment]
There is a "cvFilter" which is used to discard results that are of little value or are misleading. It is in `/src/hooks/validationHelpers.js`.

@Joel-C-Johnson @jincypjose

**Comment by mandolyte** [comment]
As of this moment, I am blocked. gA is getting 403 Forbidden errors when trying to convert tsv9 to 7. The error type is "cors", so I have asked Rich to help on discord.

**Comment by elsylambert** [comment]
No longer seeing the problem in translationCore Create - v1.8 build 190-5da41d8.
