### ISSUE TITLE
Stepper enabling/disabling based on user login

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#145]
Currently the user is able to open the files without a login and it hangs the app.
 when the user clicks on the stepper itself and surpasses one or two steps in the stepper.
Please review the screen recording:
[Stepper-organisation.mp4.zip](https://github.com/unfoldingWord/tc-create-app/files/4718125/Stepper-organisation.mp4.zip)

Below is the screenshot of 0.9.0-rc.3. when opened:
<img width="1751" alt="Screen Shot 2020-06-02 at 11 47 16 AM" src="https://user-images.githubusercontent.com/51806180/83540992-0b1b3100-a4c7-11ea-805a-a08947658852.png">

Here what happens after stepper is clicked. File selection is made enabled without login.
<img width="1751" alt="Screen Shot 2020-06-02 at 11 18 31 AM" src="https://user-images.githubusercontent.com/51806180/83540031-c6db6100-a4c5-11ea-9dfc-d8ba0de6411f.png">

When the file is clicked, the file loading spinner shows up and hangs up the app( Since the file cannot be actually opened with login to the Repo)

**Comment by klappy** [comment]
Testable in `1.0.0-beta.2`

**Comment by BincyJ** [comment]
@birchamp think this was demoed and can be closed. Closing now. Let me know if otherwise.
