### ISSUE TITLE
Repo chips not showing

### ISSUE THREAD

**Issue by Joel-C-Johnson** [unfoldingWord/tc-create-app#1455]

**Comment by Joel-C-Johnson** [comment]
Open tc create app
Open a file. You should see repos chips at the top. but in the last build, it is not showing. 

![repo_path_chips](https://user-images.githubusercontent.com/25791348/203548324-5875ad9a-a753-4c06-b6cf-ee72ea19167e.png)

**Comment by superdav42** [comment]
Fixed in https://github.com/unfoldingWord/tc-create-app/pull/1453

**Comment by elsylambert** [comment]
Chip shows and works as expected in translationCore Create - v1.8 build 190-5da41d8.
