### ISSUE TITLE
Change filter dropdowns to autocomplete combo boxes

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#1463]
Issue:
---
The filter dropdowns should allow the user to type what they want so the list is limited.  https://mui.com/material-ui/react-autocomplete/ 

DoD:
---
The filter dropdowns have the autocomplete feature.

**Comment by elsylambert** [comment]
translationCore Create - v1.9.0 build 207-408b416 works as expected. Users can type in the filter box and get the result.
