### ISSUE TITLE
Add resource text to parallel scripture pane

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#148]
As a GL translator, I want to be able to see other published Bible texts as I translate and edit my GL resources.

The users choice of resources should update all of the parallel scripture panes.

**Comment by ancientTexts-net** [comment]
FWIW, here's how Logos8 does it.
(I will try to find a screenshot of Logos7, which was somewhat klunkier)

1. Several "parallel scriptures" visible:

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/f695a150-d17e-4d38-815c-4b6882e4f601)


2. Clicking the "parallel" button shows which resources are available & selected:

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/4ae3e1ee-62ea-44fe-9e50-186026f781ae)


3. Deselecting a resource hides it

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/b2cc0b29-c2f9-414b-b015-9505dd1ca5a5)

**Comment by ancientTexts-net** [comment]
one possible way to adapt something similar to the Logos8 UI would be to provide the URL:

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/73c0907e-4d0a-4ae1-ae04-2d7496ae92a0)

**Comment by ancientTexts-net** [comment]
@klappy , can you help me with a design question, please?

Here's how I understand it:

`ParallelScripture` currently has a `ResourcesContext`.  
`ParallelScripture` has 1 `ScriptureTable`.

`ScriptureTable` accepts *titles*, *books*;
and it constructs *columns* out of those titles & books (each column is a title + rows of verses).

The `ColumnsMenu` can show/hide columns...
But I don't see how I can add new resources via `ColumnsMenu`

**Comment by ancientTexts-net** [comment]
One way would be to wire-up the `ColumnsMenu` to inherit the `ResourcesContext`.
Then the `ColumnsMenu` component can manipulate the `ResourcesContext`, which would cause the `ParallelScripture` --> `ScriptureTable` to react

**Comment by ancientTexts-net** [comment]
Also, @klappy,
would it be possible to design something like `addResource()` in `ResourcesContextProvider`?

Instead of calling `useResources()` and re-initializing the whole array, we could just ADD one on demand ?

is this the kind of use case you were thinking of here, please?

Thanks

**Comment by ancientTexts-net** [comment]
Recommended test plan for:

May I suggest a test plan:

1. Open scripture-resources-rcl RCL demo site:
https://deploy-preview-32--scripture-resources-rcl.netlify.app/#/Parallel%20Scripture%20?id=parallelscripture

2. Click the `Add Resource` button:
Add one resource.  (Sample resource addresses below.)
**VERIFY**: the resource is correctly displayed in ScriptureTable.

**Sample edge case:**
Enter invalid resource path (e.g., `ASDF` or `google.com`)

*NOTE:* invalid resource paths currently don't have special handling.

**Sample resource addresses:**

`Door43-Catalog/hi/ulb/master/3jn`

`STR/hi/irv/master/3jn`


.

**Comment by ancientTexts-net** [comment]
@elsylambert 
@klappy

**Comment by elsylambert** [comment]
@ancientTexts-net Following your suggested test plan on the RCL: I added the sample resource, seeing the Resources under "Manually providing files" section.

**Comment by ancientTexts-net** [comment]
@RoyalSix  

current PR is #34

testable in:

https://deploy-preview-34--scripture-resources-rcl.netlify.app/

here are some sample **resource links** that work in the markdown demo:

Door43-Catalog/hi/ulb/master/3jn

STR/hi/irv/master/3jn

**Comment by ancientTexts-net** [comment]
@RoyalSix -- thank you -- great catch

that was a deprecated method that should have already been removed.
i removed it and re-pushed
thanks

**Comment by ancientTexts-net** [comment]
Testable at:

https://deploy-preview-169--tc-create-app.netlify.app/

**Comment by ancientTexts-net** [comment]
PR for RCL is merged.

Now need to publish to NPM
and PR for app

**Comment by ancientTexts-net** [comment]
@elsylambert 

@BincyJ , @birchamp 

testable in translationCore Create - `v1.1.0-beta.1`
https://develop--tc-create-app.netlify.app/

**Comment by birchamp** [comment]
@elsylambert @ancientTexts-net  I'm failing this because when I put in an invalid address it breaks the parallel scripture viewer

**Comment by ancientTexts-net** [comment]
Fix for bug is testable here:

https://deploy-preview-38--scripture-resources-rcl.netlify.app/#/Parallel%20Scripture%20?id=parallelscripture

**Comment by ancientTexts-net** [comment]
FYI @jag3773 identifies an original bug related to this issue:
from Ruth book package work

https://git.door43.org/unfoldingWord/hbo_uhb/pulls/520

https://unfoldingword.zulipchat.com/#narrow/stream/209457-SOFTWARE/topic/string.20tokenizer

**Comment by mandolyte** [comment]
@ancientTexts-net in the demo page, could you add example resources to use? Just add some text above the demo. For example, I added this line when I was doing some work in the Parallel Scripture demo: "To see highlighting appear, change the -1 occurrence to 1; then click or tab out of field."

I also notice that the occurrence doesn't have "-1" in it now. So my instructions may not make sense... perhaps you could change it back while you are in there... thanks.

**Comment by ancientTexts-net** [comment]
@mandolyte done!  Thanks

**Comment by ancientTexts-net** [comment]
@elsylambert testable at 
https://scripture-resources-rcl.netlify.app/#/Parallel%20Scripture%20?id=parallelscripture

**Comment by elsylambert** [comment]
Works fine at the RCL: Able to see the Additional Sample Resources and not seeing any crash when invalid address is input.

**Comment by ancientTexts-net** [comment]
Testable in `v1.0.0-beta.7`

https://deploy-preview-188--tc-create-app.netlify.app/

Features in this build:
- #148 Add resource
- #78 Scroll to new row after add/delete
- #171 Unable to save file in tW, tA, and OBS
- #120 Save action: app  needs to refresh the save action

.

**Comment by ancientTexts-net** [comment]
Testable on `develop`!  `v1.0.0-beta.7`

https://develop--tc-create-app.netlify.app/

Features in this build:

#148 Add resource
#78 Scroll to new row after add/delete
#171 Unable to save file in tW, tA, and OBS
#120 Save action: app needs to refresh the save action

**Comment by elsylambert** [comment]
Looks good and works as expected in v1.0.0-beta.7. Able to see the Additional Sample Resources and not seeing any crash when invalid address is input.

**Comment by ancientTexts-net** [comment]
Russian Open Bible

resourceLink:

Door43-Catalog/ru/rob/master/


----

Cumulative list of examples:

Door43-Catalog/hi/ulb/master/

STR/hi/irv/master/

Door43-Catalog/ru/rob/master/
