### ISSUE TITLE
Highlight when multiple verses are in the reference field in TSV7

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#1491]
If the occurrence number is -1, the word should be highlighted every time it appears in ANY of the verses in the reference range. This is the most common use case, but the current way of highlighting based on specific occurrence numbers (like 1, 2, 3) should still work.

**Comment by birchamp** [comment]
@jincypjose we need to know how big of an effort this is.

**Comment by jincypjose** [comment]
@birchamp - @larsgson, @Joel-C-Johnson and i were debugging this issue and found out it's a few day's effort not a quick fix
And for the future reference.its in single-scripture-rcl
these are two files where focus is needed:
ScripturePane.tsx
useScripture.tsx

and then search for "verseObjectsArray", 
which is the structure @larsgson  created to solve this within gE

**Comment by jincypjose** [comment]
1. we made progress on this but later found that it only works if the occurrence happens on the first verse, if there is no occurrences on the first verse non of the words would be highlighted for eg php1:1-2,2:5
Edge case 1:
![failing-2.png](https://images.zenhubusercontent.com/5f8fb2e83cdc9276e3df86d3/338058a6-5be5-4b0e-815d-46f94390a043)
2. if there is no occurrences in the middle verses then only the words in the first verse would be highlighted
Edge case 2:
[working-1.png](https://images.zenhubusercontent.com/5f8fb2e83cdc9276e3df86d3/a5acc0b1-62a0-46c9-b520-97de9a7a3dc4)![failing-1.png](https://images.zenhubusercontent.com/5f8fb2e83cdc9276e3df86d3/c0dfa20d-22a5-4478-8314-7b73b4754059)

AREA OF FOCUS 
(export const selectionsFromQuoteAndString = ({
  quote,
  stringMap: rawStringMap,
  occurrence,
  })) this is in selection.js file (https://github.com/unfoldingWord/scripture-resources-rcl/blob/master/src/core/selections/selections.js) line-62

**Comment by elsylambert** [comment]
Does this issue scope for occurrences -1 only? Or does it cover Occurrence 2 or more in verse ranges? @abelpz @jincypjose

**Comment by elsylambert** [comment]
translationCore Create - v1.11 build 235-a32731d. Highlighting in verse ranges works fine. -1 occurrence highlights all the occurrences in the range and if occurrences are changed to 1 or higher, the correct occurrence of the Quote is highlighted.
