### ISSUE TITLE
Allow filtering by chapter in TSV7

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#1493]
Users want to be able to filter records down to all of the records in a single chapter of a book.  Now that TSV7 has a string for the reference the filter no longer has a separate chapter field; however users need to check chapter by chapter. 

DoD:
Users can filter to show only the records from a particular chapter.

**Comment by mandolyte** [comment]
This works already:
![Screenshot 2022-12-19 4 34 43 PM](https://user-images.githubusercontent.com/1289437/208528737-6842c4c1-e1a3-4d30-8714-63442e1f7724.png)

**Comment by birchamp** [comment]
@mandolyte @larsgson When I do a search I get any note that includes the text '20:' because it searches all of the columns. Also the records don't show up in order for me.![CleanShot 2022-12-27 at 10.35.13.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/7906382a-3e77-408c-a58d-3d09dc51a143)

**Comment by elsylambert** [comment]
translationCore Create - v1.9.0 build 211-463611d. @abelpz The max limit to show the chapter verse is 18 and we cannot scroll beyond that. ![Screenshot 2023-01-10 at 9.55.53 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/1206772b-bcb2-415c-b7e4-39816e921bb0)

**Comment by abelpz** [comment]
Thanks for finding this @elsylambert. I'll take a look

**Comment by abelpz** [comment]
@elsylambert this PR should fix that https://github.com/unfoldingWord/tc-create-app/pull/1510
@Joel-C-Johnson could you review it?

**Comment by elsylambert** [comment]
Looks good in translationCore Create - v1.9.0 build 213-b124b37. Scroll bar is visible for Chapter and verse drop-downs. The selection from the filter and display of results are showing no delay. Works fine.
