### ISSUE TITLE
Highlighting by Occurrence number is not working for 2nd and 3rd occurrences

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#1494]
Highlighting by Occurrence number is not working for 2nd and 3rd occurrences.

It works for occurrence 1 and -1(highlights all occurrences), but for 2nd or 3rd occurrences it highlights the first occurrence of the word. This needs to work for a single verse.
![Screenshot 2022-12-19 at 4.02.26 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/7ea14bac-e0e2-42fb-b6d6-db8c2dabef1b)

**Comment by birchamp** [comment]
@jincypjose please estimate this. It was working in TSV9. Is this the same problem as with the -1 occurrence?

**Comment by jincypjose** [comment]
@birchamp this is the issue @Joel-C-Johnson is looking into.Sure i will take a follow up on this and update you for the same.

**Comment by jincypjose** [comment]
This issue is almost connect to https://app.zenhub.com/workspaces/tc-create-workspace-5f049cdbfa88090016bf043e/issues/gh/unfoldingword/tc-create-app/1491 as the focusing area is same and i think this also should be added to the same release(1.9.1)

**Comment by elsylambert** [comment]
Verified in  - v1.10 build 228-f43ba9b. Highlighting by Occurrence number is working fine for 2nd and 3rd occurrences as well as for -1.![Screenshot 2023-02-15 at 10.20.15 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/53f4c462-caf6-43fc-bf99-4fcd7d4d3fa9)
