### ISSUE TITLE
Expand Chapter button in Parallel scripture Viewer expands without a scroll bar

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#150]
translationCore Create - v1.0.0-beta.2

Expand Chapter button in Parallel scripture Viewer expand all the chapters (with no scroll bar )on the page when expanded in one verse. If it is a long book, the Expanded chapter consumes the whole page.
- Click on Expand Scripture Pane button and then click on the Expand Chapter Button.
[Expand button.mp4.zip](https://github.com/unfoldingWord/tc-create-app/files/4759818/Expand.button.mp4.zip)

**Comment by klappy** [comment]
Should be testable in `1.0.0-beta.4`

**Comment by elsylambert** [comment]
Looks good in translationCore Create - v1.0.0-beta.4. Scroll bar appears in the Expanded Chapter window.
