### ISSUE TITLE
Performance issue: Opening a file takes a longer time for Bigger books

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#1500]
After the TSV7 changes, it is found that opening a TN file takes longer than usual. The time taken for a file to load depends on how big the book/file is. For Ex Mathew takes 6.9 sec whereas Mark takes 4.6 secs to load.

**Comment by elsylambert** [comment]
From Benjamin: Time for various actions in tccreate in Psalms. I have my usual: 2 copies of tcore (ult/ust), logos, browser with a few tabs (some google sheets for TN templates and Christopher's Psalms feedback, GL man, and Psalms Layer-by-layer project, zulip), spotify, telegram. Using about 62% of 16gb RAM.

Change a note from 4:1 to 4:front and then navigate to Note field: 34 secs, 1 browser wait or kill tab question, chose wait
Pasted Hebrew text into Quote field, clicked to Occurrence field: 15 secs, 1 browser wait or kill tab question, chose wait
Changed occurrence to 1, moved to note, field: 4 secs
Edited Note field, changed to SupportReference field: 16 secs, 1 browser wait or kill tab question, ignored.

**Comment by superdav42** [comment]
After running git bisect between 1.7.1 which work fast and 1.8 the first version to start running slowly I found that 0d668e737e2713a6cb16e4061352f4a645f99658 is the first bad commit.

**Comment by superdav42** [comment]
I traced the changes in the versions to these two PRs. 
https://github.com/unfoldingWord/datatable-translatable/pull/117/files
https://github.com/unfoldingWord/datatable-translatable/pull/119/files
Probably the problem is with the property passed for the font family. I'll see how it can be improved.

**Comment by elsylambert** [comment]
Looks good in translationCore Create - v1.9.1 build 215-30d207e
