### ISSUE TITLE
Make new row obvious to user

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#1513]
When the user creates a new row the row should be highlighted so it can be found easily.  By adding a CSS animation to the row for 2s the user will find it quickly.  Change the background to a blue pastel temporarily. 

DoD:
---
When the user makes a new row the color of the new row should be changed temporarily

**Comment by elsylambert** [comment]
Some of the problems observed:
1. When a new row is added, it flashes on the screen with a darker shade for few seconds and then the parent row shows UI overlapping on the scripture viewer.![Screenshot 2023-01-31 at 9.26.03 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/6efc1d6c-faee-43d5-bc2d-de2b62857180)
2. The scripture viewer now changes to a darker shade upon clicking.
![Screenshot 2023-01-31 at 9.37.37 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/a9f506a6-7ca8-4dc7-9fa7-b0aeaa49bf57)

**Comment by elsylambert** [comment]
3. The row is not highlighted when added if the notes are not written up in the Add a new row dialog box.
- Click on + to add a new row.
- Add a row modal opens up. Do not add anything to the row and click on Add.
- Note that the new row is not highlighted.

**Comment by elsylambert** [comment]
translationCore Create - v1.10 build 218-8325097. The above mentioned issues are resolved and a newly added row is made obvious to the user by bordering the row in blue.

**Comment by danielklapp** [comment]
translationCore Create - v1.10 build 218-8325097. I also tested mentioned issues and they are resolved.
