### ISSUE TITLE
Filter text overflows the screen area when Reference list is long

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#1519]
For en_tn, file tn_PSA, select filter and choose chapter 119. This example has a long list of reference. Note that the filter result overflows the app screen area..
![Screenshot 2023-01-19 at 9.22.04 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/90784965-4e26-4e14-a5af-b2e2cf7a358a)

**Comment by elsylambert** [comment]
@abelpz While you are fixing the filter bug, can you take a look at this too?

**Comment by abelpz** [comment]
Sure, thanks @elsylambert, I'll get on it.

**Comment by elsylambert** [comment]
This issue is fixed in  - v1.10 build 228-f43ba9b.
