### ISSUE TITLE
Release 1.9.1

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#1520]
Performance improvement

**Comment by elsylambert** [comment]
@birchamp Can you please review the notes ^^

**Comment by elsylambert** [comment]
translationCore Create - v1.9.1 build 215-30d207e is looking good in Production.

**Comment by BincyJ** [comment]
@jincypjose please check above release notes

**Comment by Joel-C-Johnson** [comment]
@elsylambert I have published the release notes
