### ISSUE TITLE
Filter do not reset properly when closed from the header

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#1522]
When results from the filter is closed by clicking on the close button x on the header, it shows results for verse 2 and if done once again, it leaves the Reference in the header.
![image.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/153763c7-2d1d-47bd-a1de-fd41a7fe25c4)
![image.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/f1ce52de-1f07-406c-bb74-ffe97fe62761)

**Comment by elsylambert** [comment]
@abelpz I wrote this issue for the filter issue Rich saw.

**Comment by superdav42** [comment]
> @superdav42 Is this ready to be tested in translationCore Create - v1.10 build 218-8325097?

Yes.

**Comment by elsylambert** [comment]
Verified in translationCore Create - v1.10 build 218-8325097. The problem is still happening. Closing the filter from the header leaves it on verse 2.

**Comment by superdav42** [comment]
Can you provide more details? 
It seems to work fine for me. I just tested on https://develop--tc-create-app.netlify.app/ . Click the 'x' in the chip clears the filter and shows everything again. The Reset button also works as does the 'x' in each filter field. 
What do you do exactly to reproduce this?

**Comment by elsylambert** [comment]
Here is the screen recording: https://images.zenhubusercontent.com/191973535/d4c8b34e-8867-4e1a-8d2c-5311b87968f1/screen_recording_2023_02_07_at_3_42_21_pm.mov

**Comment by elsylambert** [comment]
https://images.zenhubusercontent.com/191973535/b823e846-8733-49b5-a051-9a5d49dc8944/screen_recording_2023_02_07_at_3_42_21_pm.mov

**Comment by abelpz** [comment]
@elsylambert, yes, you can assign this to me. This needs to be changed directly in tc-create. There is a bible-reference-range update that just came out, I needed it to improve the filter. Should be a simple task.

**Comment by elsylambert** [comment]
![image.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/2e249175-d42f-4906-b7c1-82b6b0a078ae)

**Comment by danielklapp** [comment]
I was using Safari when app crashed with grey screen. Then tried closing filter in Chrome and it worked.

**Comment by elsylambert** [comment]
Not seeing this problem in  - v1.10 build 228-f43ba9b. Filters now close properly when closed from the header.
