### ISSUE TITLE
Reference is missing in Add row modal for some OT books

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#1533]
translationCore Create - v1.10 build 218-8325097
- Open Lev, Num or Jos( old testament book)>tN.
- Go to any row and click + to add a new row. 
Note that Reference is missing from the modal.![Screenshot 2023-02-09 at 10.26.03 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/1775872e-2733-4b81-bca5-f0f774221f94)
And it adds the row with empty Reference.
![Screenshot 2023-02-09 at 10.27.02 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/98169831-23fc-4d4f-a159-adb96aa6eb07)

**Comment by elsylambert** [comment]
@abelpz I found this issue as closed. Has this been merged into Develop? I do not see a build number change and the fix is not showing in translationCore Create - v1.10 build 218-8325097 ?

**Comment by abelpz** [comment]
@elsylambert I believe this issue was linked to @superdav42 PR so it closed automatically after I merged.

**Comment by elsylambert** [comment]
Looks good in v1.11 build 231-7a4c868. Reference is populated for new row modal for Exo, Lev and Num.
