### ISSUE TITLE
SPIKE: Merging from Master down to the Branch and then pushing to master

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#1545]
Plan a collab week accounting for all RCL layers of a "pull/push" feature where users can get their branch "updated" from master and then merge their work into master.

Questions:
What layers or components will be needed?
What will the UI look like?
Does Gitea need another permissions level to prevent merging to master for some users?
How do we make this so it can work in both gA and tCC?

**Comment by abelpz** [comment]
@BincyJ @Joel-C-Johnson 

These are some of steps we could follow to achieve this:

- Release the new extensible version of Datatable-translatable
- Copy @PhotoNomad0 implementation of the icons (from: https://github.com/unfoldingWord/gateway-edit/blob/feature-mcleanb-syncChanges/src/components/ResourceCard.js#L254)
- Paste and adapt that code in TranslatableTSV.js component in tc-create-app and add the onRenderToolbar prop to Datatable.
- Connect those buttons to  https://unfoldingword.github.io/dcs-branch-merger/ from @richmahn@mandolyte

**Comment by Joel-C-Johnson** [comment]
@abelpz @jincypjose 
- [ ] Release the new extensible version of Datatable-translatable
- [ ] Copy @PhotoNomad0 implementation of the icons (from: https://github.com/unfoldingWord/gateway-edit/blob/feature-mcleanb-syncChanges/src/components/ResourceCard.js#L254)
- [ ] Paste and adapt that code in TranslatableTSV.js component in tc-create-app and add the onRenderToolbar prop to Datatable.
- [ ] Connect those buttons to https://unfoldingword.github.io/dcs-branch-merger/ from @richmahn@mandolyte
