### ISSUE TITLE
Field Reported: Adding a new row when filter is ON jumps to the end of the page.

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#1551]
- Open uW, en-tn, choose book of Psalms,
- In the filter, choose chapter 44. The filter displays the results from chapter 44.
- Add a new row to 44:1. After you click on Add in the new row modal, note that the focus is not on the new row, but on 44:22 which is end of the pages as filtered. You ll have to then filter using verse 1, to see the new row.

**Comment by birchamp** [comment]
What do you think the priority is on this? Don't a lot of users do their work filters by chapter? @elsylambert @abelpz

**Comment by elsylambert** [comment]
Priority is High for this. They are filtering by Chapters and when they add a row, they are thrown to the end of the page. @birchamp

**Comment by elsylambert** [comment]
Not seeing the problem in  v1.11 build 232-2318d17. Adding a new row when filter is On looks good.
