### ISSUE TITLE
Order of books in tN

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#1556]
The order of books in en_TN in develop is not in the order. Its in Alphabetical order now.
![image.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/7046b9be-daa5-408a-8fc8-71846031e3bc)

**Comment by mandolyte** [comment]
More notes:

I discovered that the master branch is at v1.9

![image](https://user-images.githubusercontent.com/1289437/225074756-c7da3495-f46e-4534-b83b-bdfaf5faad2a.png)

but current production is at v1.10
![image](https://user-images.githubusercontent.com/1289437/225074954-a8d8c74b-c595-40a4-95ca-f3e882985973.png)

How did that happen?

**Comment by mandolyte** [comment]
This comparison claims there are no differences between v1.10 and master.
https://github.com/unfoldingword/tc-create-app/compare/v1.10...unfoldingword:master

However, package.json in master has this:
```
$ pwd
/home/cecil/Projects/github.com/unfoldingword/tc-create-app
$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
$ head package.json 
{
  "name": "tc-create-app",
  "homepage": "https://create.translationcore.com/",
  "version": "1.9.0",
  "license": "MIT",
  "private": false,
  "bugs": {
    "url": "https://github.com/unfoldingWord/tc-create-app/issues"
  },
  "repository": {
```

But the tagged has 1.10 in its package.json:
![image](https://user-images.githubusercontent.com/1289437/225078400-67d47ef4-86b8-4d38-8ce0-92a7f897c1f1.png)

How can this be?

**Comment by jincypjose** [comment]
@mandolyte for me master branch is in same version as it is in production
![Screenshot from 2023-03-15 11-36-28](https://user-images.githubusercontent.com/66897554/225221583-5d644c2f-1704-4710-b090-2923700ff89f.png)

package.json in master for me is this:

$ head package.json
{
  "name": "tc-create-app",
  "homepage": "https://create.translationcore.com/",
  "version": "1.10",
  "license": "MIT",
  "private": false,
  "bugs": {
    "url": "https://github.com/unfoldingWord/tc-create-app/issues"
  },
  "repository": {
  
  Not sure whats happening.
  last time i remember i did a version update to v1.11 for scripture rcl changes(for develop) and the changes was for the highlights

**Comment by mandolyte** [comment]
I was mistaken (see edited post above) about what was in master... still looking for the last version that worked correctly. So will now back up using the tagged releases.
