### ISSUE TITLE
Enable/Disable "get updates" button based on master

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#1568]
Follow the steps for the workflow here:
https://discord.com/channels/867746700390563850/1087710131271237632/1096086897337581628
When should this update? On Save?

**Comment by elsylambert** [comment]
Looks good in v1.12 build 255-e6e5da8. When there is an update in master file, a red dot 🔴  is seen over the icon. Otherwise, the icon stays grey and its clickable. When clicked, it gives the message prompt that the user branch is up-to-date.

**Comment by danielklapp** [comment]
Agree that Update icon is working properly. It’s gray and a red dot appears over icon when there’s an update in master file. And if there’s no update in master file a message pops up saying user branch is up-to-date. Tested with v1.12 build 255-e6e5da8.
