### ISSUE TITLE
Menu item and dialog for push to master

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#1569]
**If no conflict:**

![CleanShot 2023-04-13 at 10.08.58.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/a4a3912e-94ee-41ae-8698-1513cf0f3f14)

**If conflict:**
Dialog box, "There is a conflict between your branch <branch_name> and <master_branch>. Your work can not be merged without administrative intervention. Please contact your administrator." [OK] button.

**Comment by elsylambert** [comment]
Looks good in v1.12 build 255-e6e5da8. When there is no conflict users are able to push their changes  from user branch to master and then the user branch is deleted automatically. In case of conflict, proper message pops up informing users that they need to contact admin to resolve the conflict manually.

**Comment by danielklapp** [comment]
Agree that users can push their changes from user branch to master and then the user branch deletes automatically. Also agree if there’s a conflict, that a pop up lets user know to contact admin to resolve the conflict manually. Tested with v1.12 build 255-e6e5da8.
