### ISSUE TITLE
View Versions in Scripture pane after the Expand pane Button is toggled

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#157]
translationCore Create - v1.0.0-beta.4

View Versions in Scripture pane after the Expand pane Button is toggled
-Click new Expand Scripture Pane menu button.

-Hide resources:
-Click View Versions menu button.
Uncheck ULT; Uncheck UST.

Notice: The column headers disappear, but the resource text is still displayed.
Expected result: The corresponding text & columns should hide/show together.
![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/35f149eb-02d5-4a50-889f-74e7796fa535)

-Close/Expand Scripture pane:
-Toggle the Close Scripture Pane / Expand Scripture Pane until the resource text is visible again.
Notice: The appropriate column headers/text match.

-Show resources:
-Click the View Versions menu button again.
Enable both ULT, UST.
Notice: The column headers are visible, but the resource text is not displayed.
Expected result: The corresponding text & columns should hide/show together.
![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/9838b194-ffcb-4863-b20d-4f83a2f725c1)

**Comment by klappy** [comment]
Testable in `1.0.0-beta.5`

**Comment by elsylambert** [comment]
Not seeing the issue in translationCore Create - v1.0.0-beta.5.
