### ISSUE TITLE
Highlighting for discontiguous Original Quote

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#1577]
translationCore Create - v1.12 build 257-de3d3b0
In case where we have two '&'s in the original quote. It highlights only two occurrences of the word.

![Screenshot 2023-05-11 at 10.23.56 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/59cbec59-307f-4a4e-ab81-7e0c9e09973c)

**Comment by jincypjose** [comment]
My observation for Examples - 
Deu 1-5-6 
Example1: (הַ⁠יַּרְדֵּ֖ן & מוֹאָ֑ב & אֱלֹהֵ֛י⁠נוּ & אֵלֵ֖י⁠נוּ)
Case 1: (הַ⁠יַּרְדֵּ֖ן & מוֹאָ֑ב & אֱלֹהֵ֛י⁠נוּ & אֵלֵ֖י⁠נוּ)
form right to left the first two instance which is in the 1st verse i.e 5 get highlighted but the second two instance doesn't (the highlighting broke for two verses )
Case 2: (אֱלֹהֵ֛י⁠נוּ & אֵלֵ֖י⁠נוּ)
This works fine if we want to highlight only these two instances for 2nd verse i.e 6
Case3: (הַ⁠יַּרְדֵּ֖ן & מוֹאָ֑ב )
This also works fine and also note that if we swap the words the highlighting doesn't works

Example 2:  (הַ⁠יַּרְדֵּ֖ן & מוֹאָ֑ב & מֹשֶׁ֔ה & אֶת־הַ⁠תּוֹרָ֥ה & לֵ⁠אמֹֽר)
case1: (הַ⁠יַּרְדֵּ֖ן & מוֹאָ֑ב & מֹשֶׁ֔ה & אֶת־הַ⁠תּוֹרָ֥ה & לֵ⁠אמֹֽר)
 In this example all the words get high lighted
case2: (לֵ⁠אמֹֽר & אֶת־הַ⁠תּוֹרָ֥ה & מֹשֶׁ֔ה & מוֹאָ֑ב & הַ⁠יַּרְדֵּ֖ן)
In this case only the first right will be highlighted

**Comment by jincypjose** [comment]
For above mentioned example psa 6:8-9 nothing is getting highlighted

**Comment by elsylambert** [comment]
translationCore Create - v1.12 build 260-45d04f9
![Screenshot 2023-06-05 at 9.35.52 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/6b57d614-88f4-42b7-9e3b-0394cd1f9f67)

**Comment by danielklapp** [comment]
Highlighting working properly in translationCore Create - v1.12 build 260-45d04f9.

<img width="1412" alt="Screenshot 2023-06-06 at 12 02 22 PM" src="https://github.com/unfoldingWord/tc-create-app/assets/82067076/bbf8f7b6-eb33-41c1-be7b-1116f48b56b0">
