### ISSUE TITLE
Highlighting breaking with Hebrew punctuation in verse ranges

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#1580]
In Deuteronomy 1:5-6, the quote was not highlighted, so I added an & in the quote and it highlighted the first quote.
![image.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/f13710df-0a0e-49d3-b9b9-f470080fff97)

**Comment by abelpz** [comment]
The problem with this one is that the order for the ampersand separated quotes is not right to left as you would expect for hebrew. It is actually the first quote must be on the left side, and the further quote must be on the right side. @elsylambert @birchamp 

Changing that quote to this: יְהוָ֧ה אֱלֹהֵ֛י⁠נוּ דִּבֶּ֥ר אֵלֵ֖י⁠נוּ בְּ⁠חֹרֵ֣ב & מֹשֶׁ֔ה בֵּאֵ֛ר אֶת־הַ⁠תּוֹרָ֥ה הַ⁠זֹּ֖את לֵ⁠אמֹֽר׃

Would actually highlight what was intended.

**Comment by elsylambert** [comment]
translationCore Create - v1.12 build 260-45d04f9
![Screenshot 2023-06-05 at 9.40.26 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/b32831ee-dc2f-4e1e-97d8-ed875ecc222f)

**Comment by danielklapp** [comment]
Highlighting working properly in translationCore Create - v1.12 build 260-45d04f9.

<img width="1397" alt="Screenshot 2023-06-06 at 12 26 01 PM" src="https://github.com/unfoldingWord/tc-create-app/assets/82067076/e480ba94-4fe4-4070-8b96-dcfb948152c2">
