### ISSUE TITLE
Testing Highlighting use cases

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#1583]
After the current fixes to highlighting, test the following cases:
1. Highlights of single quotes.
2. Highlights of quotes with multiple occurrences.
3. Highlights of single quotes in a reference range.
4. Highlights with &
5. Highlights for Hebrew text
-  with & 
-  with References range and &

**Comment by danielklapp** [comment]
Highlighting working properly in translationCore Create - v1.12 build 260-45d04f9.

1. Highlights of single quotes.

<img width="1409" alt="Screenshot 2023-06-06 at 2 35 06 PM" src="https://github.com/unfoldingWord/tc-create-app/assets/82067076/1530e424-896a-4075-99c9-e96f2d9fbc68">

2. Highlights of quotes with multiple occurrences.

<img width="1415" alt="Screenshot 2023-06-06 at 1 58 47 PM" src="https://github.com/unfoldingWord/tc-create-app/assets/82067076/43f9ff00-044e-4373-9e2e-c756ad9b9a29">

3. Highlights of single quotes in a reference range.

<img width="1411" alt="Screenshot 2023-06-06 at 2 28 05 PM" src="https://github.com/unfoldingWord/tc-create-app/assets/82067076/865ea894-96df-4c24-b273-50459e985dc7">

4. Highlights with &

<img width="1411" alt="Screenshot 2023-06-06 at 2 31 07 PM" src="https://github.com/unfoldingWord/tc-create-app/assets/82067076/97304667-fa12-41bd-85d9-9e0aba82a78c">

5. Highlights for Hebrew text
-    with &

<img width="1410" alt="Screenshot 2023-06-06 at 2 44 42 PM" src="https://github.com/unfoldingWord/tc-create-app/assets/82067076/7571a4b6-07ca-4e36-bd85-aac9ff6e91a0">

-  with References range and &

<img width="1394" alt="Screenshot 2023-06-06 at 2 51 53 PM" src="https://github.com/unfoldingWord/tc-create-app/assets/82067076/32ad74ab-b222-4319-9e61-67d1ed5e6b4c">

**Comment by elsylambert** [comment]
Tested in translationCore Create - v1.12 build 260-45d04f9, Highlighting works as expected as per the use cases.
- Highlights of single quotes.
![Screenshot 2023-06-07 at 9.31.50 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/e7003e06-06d1-429e-9de6-29629765b49c)

- Highlights of quotes with multiple occurrences.

![Screenshot 2023-06-07 at 9.32.30 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/c42a2cec-256f-42ce-a541-894d2a753497)

- Highlights of single quotes in a reference range.
![Screenshot 2023-06-07 at 9.33.42 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/cc88edc3-e49c-4a11-893a-c73fa5892e8a)

- Highlights with &
![Screenshot 2023-06-07 at 9.36.17 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/add75f62-c5df-43bd-b460-9e4b80b3a9a5)!

- Highlights for Hebrew text with & in a reference range
![Screenshot 2023-06-07 at 9.34.39 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/4046350a-f54b-4556-b6f5-3ded7869563e)
