### ISSUE TITLE
Scripture pane missing when reference range is selected from the filter drop down

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#1585]
translationCore Create - v1.12 build 260-45d04f9
Open tN and select a reference range from the filter dropdown as shown in the snapshot(using Psalms 6:3-4):
![Screenshot 2023-06-05 at 9.31.15 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/509c2b30-5069-4deb-99ac-9ac1672f602b)

Note that the scripture pane is missing.(using Psalms 6:8-9)
![Screenshot 2023-06-05 at 9.29.21 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/935355e8-0d37-4d0d-9755-4e670ee869e8)

**Comment by birchamp** [comment]
@abelpz is this an easy fix?

**Comment by abelpz** [comment]
@birchamp @elsylambert reason for this is the use of a different hyphen character, it sis using – instead of -, that got it confused. Quick fix for content team would be to replace that character with the regular minus/hyphen character https://www.codetable.net/decimal/45

**Comment by abelpz** [comment]
This is not related to the filter feature. It is scripture-resources-rcl the one that is choking with any strange hyphen character.

**Comment by elsylambert** [comment]
Wrote up another issue #1601 for a problem found while testing this issue. Not seeing the above reported issue.
