### ISSUE TITLE
tcc crashes opening TWL resources

### ISSUE THREAD

**Issue by abelpz** [unfoldingWord/tc-create-app#1596]
Step to reproduce: 

1. Open tCC, select this resource: Links from the original language words to Translation Words articles.
2. Open any twl file.

tCC crashes and will block user from working in app until indexedDB is manually cleared.

**Comment by elsylambert** [comment]
Looks good in translationCore Create - v1.14 build 265-99f3c5d. Not seeing tWL crashing in develop branch.
