### ISSUE TITLE
Add toggle button to expand/collapse scripture resources

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#160]
Add to the slide-out panel:
Expand all scripture (on/off). 
![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/56d1e9c8-a7c2-4ae6-90e1-2a3b531ceab9)

State management/persistence for scripture expansion will need to be exposed.

DoD: The user can expand or collapse all scripture resources. The expand toggle in the side panel should change the entire page when the toggle is set and when a new page is loaded.

**Comment by mandolyte** [comment]
**To clarify:** this makes the toggle to be global affecting all scripture panes. As a consequence should the current per pane toggle be removed?

**To consider:** in principle, any setting or UI element that is static/global could be moved to the slide out panel. This could be especially useful for to regain space in the main body of the window. For example, the source and target chips at the top could be moved to the slide out and recover several lines of vertical space.

@BincyJ @birchamp

**Comment by birchamp** [comment]
@mandolyte No, the current per pane toggle should remain as is. 

The expand toggle in the side panel should change the entire page when it is set and when a new page is loaded.  

Yes you're right about that consideration.  We're working on the UI that would include that.

**Comment by ancientTexts-net** [comment]
@RoyalSix @elsylambert 

Jay, I reviewed the code but I have questions about viewing this feature in the app.  I am unable to make it work on my machine?
Thanks

**Comment by ancientTexts-net** [comment]
https://deploy-preview-355--tc-create-app.netlify.app/

**Comment by ancientTexts-net** [comment]
Testable in `translationCore Create - v1.0.4-rc.1`
https://develop--tc-create-app.netlify.app/

**Comment by ancientTexts-net** [comment]
were we planning to have a text prompt for the user?

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/cba2aaa2-3a72-4d32-bed1-719ed4f24577)

**Comment by elsylambert** [comment]
translationCore Create - v1.0.4-rc.1.
The button does not have any text.

**Comment by ancientTexts-net** [comment]
testable in translationCore Create - v1.0.4-rc.2

https://develop--tc-create-app.netlify.app/

**Comment by cckozie** [comment]
Looks good in v1.0.4-rc.2, although it would be nice for the button to be more responsive with a spinner displayed during the page updates. See #389

**Comment by elsylambert** [comment]
Looks good in v1.0.4-rc.2.

**Comment by cckozie** [comment]
Tested in Katalon tCC tN Test Column Options
