### ISSUE TITLE
Cannot open forked TQ or TN projects

### ISSUE THREAD

**Issue by larrysallee** [unfoldingWord/tc-create-app#1610]
I have been working on https://git.door43.org/Worldview/en_tq/src/branch/master/tq_MRK.tsv in tCC for several months. Last week, it stopped opening the file. Just spins with no explanation. File seems to be OK on Door43. Tried to open other files in https://git.door43.org/Worldview/en_tq with same problem. Tried files in https://git.door43.org/Worldview/en_tn with same problem. 

Did something change in tCC to stop opening projects from other organizations? Nothing else has changed. I have tried two logins and two browsers with the same result.

**Comment by birchamp** [comment]
This seems to be the same thing that the Farsi Team is experiencing.  

> I strongly urge you to address this technical issue as soon as possible with your team. The delays caused by this problem are wasting our time and putting our project timeline at risk. We must resolve this immediately so our tC Create team can get back on track with our work. Please review the attached screenshot and download the video from the below link which demonstrates the loading problem we are encountering. Your swift action in resolving this issue is greatly appreciated, as it will allow us to complete our work on time. https://www.transfernow.net/dl/20230828a7iKaXxG

**Comment by richmahn** [comment]
@larrysallee We're all looking into this. Do you know when was the last time you COULD view and edit with tCC usig your Wordview org?

**Comment by larrysallee** [comment]
Rich,

I believe it quit last Wednesday.

Larry

Sent from my iPhone

On Aug 29, 2023, at 9:47 AM, Richard Mahn ***@***.***> wrote:

﻿

@larrysallee<https://github.com/larrysallee> We're all looking into this. Do you know when was the last time you COULD view and edit with tCC usig your Wordview org?

**Comment by richmahn** [comment]
@larrysallee Ok, worked with a bunch of developers this morning and we figured out a problem. Deploying a fix now. You should be able to work in tCC in an hour.

**Comment by larrysallee** [comment]
Rich,

Just came back up. Thanks.

Larry

From: Richard Mahn ***@***.***>
Date: Tuesday, August 29, 2023 at 2:09 PM
To: unfoldingWord/tc-create-app ***@***.***>
Cc: Larry Sallee ***@***.***>, Mention ***@***.***>
Subject: Re: [unfoldingWord/tc-create-app] Cannot open forked TQ or TN projects (Issue #1610)

@larrysallee<https://github.com/larrysallee> Ok, worked with a bunch of developers this morning and we figured out a problem. Deploying a fix now. You should be able to work in tCC in an hour.
