### ISSUE TITLE
Highlighting failing on Occurrence Number 

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#1613]
translationCore Create - v1.14 build 266-2dce737
Highlighting breaks when occurrence number is changed when there are multiple occurrences of a word.
Taking the example of John 1:1 and looking at the word "Θεὸς  "
Case I: Wrong word is highlighted when the Occurrence is 1.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakY0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--57a7fb18424baad6f6820e955f27620bfd969c42/Screenshot%202023-09-07%20at%208.53.15%20AM.png)
Case II: No highlights are shown when occurrence is 2.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2Q0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--055b033db7cc8d609b36ffd410cc823983102643/Screenshot%202023-09-07%20at%209.01.21%20AM.png)
Case III: All the words are not highlighted when occurrence is -1.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2w0IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fbd58b9a0732e9485b721a963b678ad4df75af7f/Screenshot%202023-09-07%20at%209.02.22%20AM.png)

**Comment by abelpz** [comment]
@elsylambert what happens here is that, although in English the word "God" is written the same both times it occurs in verse 1, this does not happen in Greek, it is written in two different ways, so if you want to highlight both the quote should be "Θεόv & Θεὸς", for the first one it would be "Θεόν" and for the second one it would be "Θεὸς".

**Comment by elsylambert** [comment]
Thanks @abelpz for clarification. I verified in Mathew 1:1 and looks like highlighting works fine by Occurrence number.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmIyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7df6ecf6db553814a5c866facfc58d6669515f78/Screenshot%202023-10-02%20at%2011.09.17%20AM.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmYyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--40cb00c47d8ddea706a3d525cb6329f21722e02b/Screenshot%202023-10-02%20at%2011.09.28%20AM.png)
