### ISSUE TITLE
Preview takes the page to Page 1 when filter is on.

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#162]
Steps to replicate:
- Select the filter in UTN to go to chapter 2 or 3 of the book.
- Click on the Preview button.
- It lands on the first page/chapter of the book. 

DoD: On clicking the preview button, the window should direct to the preview of the selected book and chapter.( same location as filter)

**Comment by birchamp** [comment]
make lightweight context consumer for the preview to avoid prop drilling that causes the re-render.

**Comment by ancientTexts-net** [comment]
Testable in app in `v1.0.0-beta.10`

https://deploy-preview-204--tc-create-app.netlify.app/

**Comment by elsylambert** [comment]
Looks good at https://deploy-preview-204--tc-create-app.netlify.app/ in version 1.0.0-beta.10. Preview works fine when the filter is ON.
