### ISSUE TITLE
Add OBS-TN as a translation source

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#163]
### User Story

As a translator, I want to be able to translate the resources associated with OBS like OBS translation notes.

### Features / Specifications

- [ ]
- [ ]
- [ ]

### Definition of Done

- [ ]
- [ ]
- [ ]

### Mockups

ZPP: Recommended DoD:
OBS Translation Notes shows as an option in the stepper.  OBS-TN can be successfully edited/saved.

**Comment by RoyalSix** [comment]
https://git.door43.org/Door43-Catalog/en_obs-tn

**Comment by RoyalSix** [comment]
src/core/state.defaults.js

**Comment by ancientTexts-net** [comment]
![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/e3c0e0e3-bcd9-47f1-9f51-17a3faf0c716)

**Comment by ancientTexts-net** [comment]
Thanks for your guidance @RoyalSix

**Comment by ancientTexts-net** [comment]
Testable in https://deploy-preview-169--tc-create-app.netlify.app/

**Comment by ancientTexts-net** [comment]
Testable in https://deploy-preview-175--tc-create-app.netlify.app/

**Comment by ancientTexts-net** [comment]
PR for RCL is merged.

Now need to publish NPM
and then PR for app

**Comment by elsylambert** [comment]
Looks good in  https://deploy-preview-175--tc-create-app.netlify.app/. 
@mandolyte The icon for Obs-tn needs to be changed with consistency with other Icons.

**Comment by ancientTexts-net** [comment]
Thank you @elsylambert .  Good eye!

I asked wg-comms:

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/5b9e558e-dcc5-4d2b-b375-58ba77bcf088)

**Comment by ancientTexts-net** [comment]
@elsylambert, 
Should be good now.

@jag3773 and wg-comms (@timjore) told me what they needed for a new icon.

@jag3773 helped me put the icon on both `bg` and `git.door43.org`.

**Comment by ancientTexts-net** [comment]
@elsylambert , testable at:
https://gitea-react-toolkit.netlify.app/#/Repositories%20?id=repositories-1

thanks!!  :-))

**Comment by jag3773** [comment]
The swapped name and description looks great!

**Comment by elsylambert** [comment]
Icon and name looks good.
