### ISSUE TITLE
Compare Branch not working for Translation flow

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#165]
When having spanish as Target language and en_tn as Source, Compare button does not function.
![Screen Shot 2020-06-19 at 12.07.02 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/ec1078cf-18fc-41f8-a7f9-3d008ea3a6dd)

@birchamp @klappy  Question: For Translation workflow, do we need to compare user branch with the Source Master file? If not, this button can be disabled.

DoD: should compare master for your org and your branch.

**Comment by elsylambert** [comment]
@birchamp Needs attention

**Comment by RoyalSix** [comment]
@elsylambert I am not able to get to that screen you are showing. I keep getting this dialog before I am able to see my translation notes. 
Are you still able to reproduce this issue?
<img width="452" alt="Screen Shot 2020-07-13 at 9 55 16 AM" src="https://user-images.githubusercontent.com/16184018/87331531-f7fc7780-c4ee-11ea-92f3-eb584c339e1e.png">

**Comment by elsylambert** [comment]
@RoyalSix "Elsy-org-test" organization does not have a Repo for en language. Please select ru or es as language for tn resource.

**Comment by ancientTexts-net** [comment]
QA PASS

confirmed in 1.0.1

https://deploy-preview-257--tc-create-app.netlify.app/
