### ISSUE TITLE
Target side chip gives 404 error when clicked on the Article and License

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#170]
- Click on the Branch to see the Article on the Repo. Gives 404 error.
- Click on the Licence icon. Gives 404 error.
![Screen Shot 2020-06-19 at 12.19.10 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/b9fa99a8-4b3f-4f68-9032-1e0da597ea26)
![Screen Shot 2020-06-19 at 12.19.50 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/11c00317-57f2-4a15-9edb-076ef91f81bd)

DoD: clicking on chip should direct user to their current file on door43.org.

**Comment by mandolyte** [comment]
@elsylambert how can I access this server & organization? I looked on both bg and production and don't see it. In other words, both of the links below return 404s for me:
- https://bg.door43.org/Elsy-org-test
- https://git.door43.org/Elsy-org-test

**Comment by elsylambert** [comment]
@mandolyte This is a test Organization that I created. I will add you as a member to that.

**Comment by mandolyte** [comment]
@elsylambert thanks for adding me. The snapshot above does not include the URL that resulted in the 404 error. Could you try again and get that for me? It should something like:
https://bg.door43.org/Elsy-org-test/es_tn/src/branch/cecil.new-tc-create-1/LICENSE.md, except your branch, of course.

At the moment...

With the develop link for beta.6, and pop-ups enabled, I get two tabs, neither is a 404 error.
Picture:
![image](https://user-images.githubusercontent.com/1289437/85627961-54c9e800-b63d-11ea-9bb7-20a70cbffaaf.png)

When I used my fixed code, I get just the License file:
![image](https://user-images.githubusercontent.com/1289437/85628008-69a67b80-b63d-11ea-848c-0aacde3a810f.png)

**Comment by elsylambert** [comment]
Hi Cecil,

I couldn't do much testing on #170. Not a high priority now. There are
other few issues moved to current phase which needed work. Thanks for
looking into it. I will send more info on 170 soon but as if now 170 can be
paused.

Many thanks.

**Comment by elsylambert** [comment]
Here is the 404 error URL: https://bg.door43.org/Elsy-org-test/es_tn/src/branch/ElsyLambert-tc-create-1/en_tn_44-JHN.tsv

**Comment by mandolyte** [comment]
@elsylambert Just did some testing... it appears that a "login" via tC Create **DOES NOT** log you into DCS, at least as far as the browser is concerned.

When you get the 404, try doing a login on that page. Then the article will appear. And once authenticated to the DCS, it will continue to work without any problem.

So is this more a documentation, user training thing more than a bug? I don't know if it is possible for tc-create to authenticate the browser to DCS.

Can you confirm what I have described? Thanks!
@BincyJ @birchamp

**Comment by elsylambert** [comment]
@mandolyte That is correct. When I am logged into DCS, the article shows up instead of 404 error.
So shouldn’t it bring the login page to DCS when I click the article?

**Comment by mandolyte** [comment]
@jag3773 @richmahn @klappy  Some questions for you... first look at the above two posts.
1. Given that DCS is "public", why would there ever be a 404 error for a valid file? Or is @elsylambert 's test repo on `bg` not public as I expected?
2. Can one of you "fix" this at the DCS or repo level? 
3. And is the problem something we will have once in production? (thus impacting how orgs are created and managed).

Thanks!

**Comment by mandolyte** [comment]
@elsylambert I do notice that this problem doesn't happen with the unfoldingWord org. This leads me to suspect that is has something to do with how the bg server or your test org is setup. 

Here is an example link that will fail with 404:
https://bg.door43.org/Elsy-org-test/ru_ta/src/branch/cecil.new-tc-create-1/translate/biblicalimageryta/title.md

@jag3773 ???

**Comment by richmahn** [comment]
As already noted, this org was set up as a private org, so you have to be a member.

**Comment by elsylambert** [comment]
Closing this issue based on the comments from Rich and Cecil.
