### ISSUE TITLE
Unable to save file in tW, tA and OBS (.md files)

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#171]
Tested on Production and bg server as well on translationCore Create - v1.0.0-beta.5.

The edits are not saved:
- Tabbing out of the edit box does not enable the Save button.
- Toggle the Section button, the edits are reversed.

**Comment by RoyalSix** [comment]
@elsylambert Are you also experiencing the save button not working?

**Comment by elsylambert** [comment]
@RoyalSix Yes, the save button is not enabled. Also the edited words are lost when section is toggled

**Comment by RoyalSix** [comment]
@elsylambert I am seeing different behavior. Would it be possible to take a video for me?

**Comment by elsylambert** [comment]
[unable to save md files.mp4.zip](https://github.com/unfoldingWord/tc-create-app/files/4826682/unable.to.save.md.files.mp4.zip)
Here is the recording:
@RoyalSix I used my Account elsylambert and organization as unfoldingword. However, this is happening regardless of the Organization. I have other organization also where I see the same behaviour.

**Comment by RoyalSix** [comment]
@elsylambert Nevermind I am seeing the behavior

**Comment by ancientTexts-net** [comment]
@elsylambert testable at 
https://markdown-translatable.netlify.app/#/Block%20Editable?id=blockeditable


thank you! :)

**Comment by elsylambert** [comment]
Works fine at RCL:https://markdown-translatable.netlify.app/#/Translatable?id=translatable-1. 

Able to Save the edits in MD file.

**Comment by ancientTexts-net** [comment]
Testable in `v1.0.0-beta.7`

https://deploy-preview-188--tc-create-app.netlify.app/

Features in this build:
- #148 Add resource
- #78 Scroll to new row after add/delete
- #171 Unable to save file in tW, tA, and OBS
- #120 Save action: app  needs to refresh the save action

.

**Comment by elsylambert** [comment]
Tested in https://deploy-preview-188--tc-create-app.netlify.app/. Able to save .md files and not seeing edits lost when section is toggled.

**Comment by ancientTexts-net** [comment]
Testable on `develop`!  `v1.0.0-beta.7`

https://develop--tc-create-app.netlify.app/

Features in this build:

#148 Add resource
#78 Scroll to new row after add/delete
#171 Unable to save file in tW, tA, and OBS
#120 Save action: app needs to refresh the save action

**Comment by elsylambert** [comment]
Verified on translationCore Create - v1.0.0-beta.7. Able to save .md files and not seeing edits lost when section is toggled.
