### ISSUE TITLE
License Icon button on the Chip opens the both the License and the Article pages

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#172]
translationCore Create - v1.0.0-beta.6
1. Click on the "i" License icon on the chip.
2. It opens the License Info page as well as the Article page on DCS.

**Comment by mandolyte** [comment]
@elsylambert could you provide some details? It worked fine when I did as follows:
- used https://develop--tc-create-app.netlify.app/
- opened UTN for Titus 
- clicked both source and target "i" on the "chip" at the top of page.
- in each case it went to the appropriate license page and no other pages were also opened

**Comment by elsylambert** [comment]
[License icon.mp4.zip](https://github.com/unfoldingWord/tc-create-app/files/4825632/License.icon.mp4.zip)
Here is my screen recording

**Comment by ancientTexts-net** [comment]
LGTM;  I will publish to NPM after my PR is merged today if that's OK

**Comment by ancientTexts-net** [comment]
@mandolyte

**Comment by elsylambert** [comment]
Works fine in the app in  v1.1.1-beta.3.
