### ISSUE TITLE
Change default view to hide Occurrence and OrigQuote fields

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#177]
Change tC-Create to hide Occurrence and OrigQuote fields.  The user can choose to show them as needed.

**Comment by RoyalSix** [comment]
@elsylambert Verified in https://deploy-preview-224--tc-create-app.netlify.app/

**Comment by elsylambert** [comment]
@RoyalSix  Not seeing the changes in https://deploy-preview-224--tc-create-app.netlify.app/. In fact the fixes done in rc2 are gone and Russian file is overwritten by English

**Comment by elsylambert** [comment]
Verified in translationCore Create - v1.0.0-rc.3. Works fine. Occurrence and Original Quote are unchecked by default.
