### ISSUE TITLE
Datatable Translatable v0.4.0 Add Row function giving error

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#18]
![image](https://user-images.githubusercontent.com/51806180/68228903-3f2b8380-ffc4-11e9-85a1-bde4abfa9b88.png)
Click on the Add Button, throws error:
![image](https://user-images.githubusercontent.com/51806180/68229032-77cb5d00-ffc4-11e9-8f80-2cde2aed8ac2.png)

The effect on the GLTS app is that clicking on Add button brings a blank page and aborts the app.

**Comment by RoyalSix** [comment]
@klappy not sure how to access the site in the issue https://unfoldingword.github.io/datatable-translatable/ is not showing

**Comment by RoyalSix** [comment]
I went to 1PET 1:1 and tried adding a row and it seems to give no feedback as if nothing happened, and the dialog stays open (one with Cancel/Add buttons)

**Comment by klappy** [comment]
Looks like there's a bug in DataTable-Translatable RCL as I can reproduce this in the RCL's styleguide: https://datatable-translatable.netlify.com/

Both Edit and Delete do not work as intended.

**Comment by klappy** [comment]
This should be addressed in `beta.2` build.

**Comment by elsylambert** [comment]
Looks good in beta-2. Add row function/button duplicates the row. Delete function permanently deletes the row.
