### ISSUE TITLE
App re-opens to previous file when closed accidentally without Remember me option 

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#190]
when the app is simply closed after getting to a file (I used utn for Ruth), and then app is launched a second time, then the stepper seems to advance to the the file, even though it has no credentials. This leads to the endless spinner.

If I close the resource from the tool bar, it proceeds to the login; from there it works.

**Comment by mandolyte** [comment]
Confirmed that this still happens with latest preview (https://deploy-preview-192--tc-create-app.netlify.app/).

I suspect this should be easy to fix. Here is what I think it would take:
- At app launch time, in the code where authentication is loaded from persistence, this load will not find any authentication key.
- If no authentication key is loaded then the stepper should be set to the beginning, making the user login.
- Once logged in, then if goes directly to the file and opens it, then that is OK.

@RoyalSix @elsylambert Does this sound right?

**Comment by mandolyte** [comment]
@RoyalSix @elsylambert I did some debugging and found that at launch the "active step" is zero (the login step). And if I pay attention, the login does briefly show and then proceeds directly to the endless spinner.

It's like it thinks there was a successful login... still looking...

**Comment by elsylambert** [comment]
Works fine in 1.0.0.beta 10.
