### ISSUE TITLE
Endless spinner when logged back in with Keep me logged in option

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#198]
Steps to Replicate:
- Login with your credentials and Check the Keep me logged in option.
- Select your Organization, Language and Resource.
- Open the file.
- From the top Menu, Click on your Avatar and logout.
- Log back in on the same login window using your password.
- You can see the Organization page, do the Organization selection and Resources , the loading spinner shows up and spins endlessly.![Screen Shot 2020-07-13 at 10.40.25 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/f72bc743-4ead-4200-ab51-47a62db6136a)

**Comment by mandolyte** [comment]
@elsylambert I think the logout persistence work done recently has fixed this. Can you retest?

**Comment by elsylambert** [comment]
@mandolyte Still seeing this issue. Please follow these steps:
- Login with your credentials and Check the Keep me logged in option.
- Select your Organization, Language and Resource.
- Open the file.
- From the top Menu, Click on your Avatar and logout.
- Log back in on the same login window using your password.
- You can see the Organization page, do the Organization selection and Resources , the loading spinner shows up and spins endlessly.

**Comment by mandolyte** [comment]
@elsylambert looks like the logout is clearing all the persisted data **except** for the filepath. This is likely the cause of the problem, altho how/why precisely is uncertain.

@ancientTexts-net any ideas?

**Comment by mandolyte** [comment]
@RoyalSix @ancientTexts-net I have been stepping thru the debugger trying to find out why filepath is persisted on a logout, when "keep me logged in" is NOT checked. All the other keys are removed from IndexedDB, but not this one.

I found that it is being removed but is immediately put back by Gitea React Toolkit's `useFile.js` -- that was a surprise. For documentation purposes and in case I do not figure it out before lunch, I wanted to put this here so you can take it up if you wish.

![image](https://user-images.githubusercontent.com/1289437/88070175-64572680-cb40-11ea-9e5b-9cfbf1f7fbf4.png)

**Comment by mandolyte** [comment]
@ancientTexts-net @RoyalSix Today I completed more debugging on this. It is not a persistence issue, even tho it resembles one. I can manually remove the "filepath" key from IndexedDB and it will still fail. The value for filepath appears to be sticking in memory for the FileContext (and useFile.js). Some indications that it and something called `blobfilepath` are getting tangled somehow.

Could one of you meet with me tomorrow to review this? I think I need some help!!

**Comment by ancientTexts-net** [comment]
Apologies @mandolyte , but I just now saw your msg from 7/22.
At any rate, the fix looks good.  Tested locally in tc-create-app

**Comment by ancientTexts-net** [comment]
QA PASS

confirmed in 1.0.1

https://develop--tc-create-app.netlify.app/
