### ISSUE TITLE
Single Editor Pane for MD Document

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/tc-create-app#2]
Add a mode for editing the entire document as a single block that doesn't break the document up into smaller blocks by paragraph. 

This could be handled by adding a toggle in the menu for Paragraph Blocks just like we have for Heading Sections.

**Comment by klappy** [comment]
Heading Sections feature was accomplished by rendering a single SectionTranslatable component instead of DocumentTranslatable component from the MarkdownTranslatable component library. 

Option 1:
We can render a BlockTranslatable component from the library, but it does not currently have the same buttons/functionality as the Document and Section components. We can wrap it with the same buttons but will have to maintain that for parity. 

Option 2 (recommended):
We can add a flag to both DocumentTranslatable and SectionTranslatable to toggles Block segmenting on/off. This allows the Block mode to be disabled in both modes of Heading Sections and gives greater flexibility and requires less long term maintenance.

**Comment by klappy** [comment]
Should be addressed in Alpha.27

**Comment by elsylambert** [comment]
Verified in Alpha-28. Single editor pane looks good. Works fine on toggle.
