### ISSUE TITLE
change organization page to have spinner while loading orgs instead of showing the error message

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#207]
Currently, the organization page has a default error message displayed while organizations are being fetched.

**Comment by ancientTexts-net** [comment]
Dear @RoyalSix I am having trouble testing this feature in tc-create-app

**Comment by ancientTexts-net** [comment]
I think I am still seeing the issue?

I believe this is latest RCL?
I paused the screen capture on the error msg:


![bug-207.gif](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/bfdef774-4a27-44db-9b6e-e3ae49d72623)

**Comment by ancientTexts-net** [comment]
@RoyalSix  ^^

**Comment by RoyalSix** [comment]
This one is verified in develop branch

**Comment by ancientTexts-net** [comment]
Dear @RoyalSix ,

Larry reported an issue where users that are members of NO organizations get a spinner with no error message. Previously, I believe the error message showed?  Even if not, is it possible to get the error message to show in this case?

1. create new user on BG.door43
2. do NOT assign this user to any orgs 
3. login
see: spinner is in the org list, with no way out.  

I think there is an error message here.  Is it possible to show this msg in this case please.



![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/84854f16-718d-4f41-8478-5ace398e48da)

**Comment by ancientTexts-net** [comment]
Please ignore above comment.  
This new issue is UNRELATED to these changes

**Comment by ancientTexts-net** [comment]
Unable to test throttled due to HSTS
without too much additional effort.

Tried Fiddler & Chrome throttling

**Comment by ancientTexts-net** [comment]
Passing in QA

but strange artifact if you go BACK:
(only available during SLOW throttling)

1. login
2. select org
3. click orgs in stepper
see: instead of spinner, we see selected org button
see: clicking this org does nothing.

see: orgs screen automatically recovers & ends up working fine.

**Comment by ancientTexts-net** [comment]
![throttled-207.gif](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/faf13506-c393-4d4b-bb89-2a81ba596785)
