### ISSUE TITLE
Stepper Auto Advance

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/tc-create-app#22]
As a user, I expect the stepper to auto-advance to the next step after I have made a choice since there is only 1 interaction on each screen.

For example, after I click login I expect to see the language page (the hot pink/red LOGOUT button makes it look like something went wrong.

Same unexpected results on Language and Resource steps... e.g. after I select my option I expect to be taken to the next step automatically.  Incidentally, this is what happens on the file selection, I am automatically taken to the next step of editing the file.

*Version GLtS v0.9.0-alpha.17*

**Comment by klappy** [comment]
Should be addressed in `beta.5`

**Comment by elsylambert** [comment]
Verified in beta.6- Auto-stepper looks good.
One question here :
@klappy From the login page, it jumps to the Resources page instead of Languages page cause the app saves the language selected from the previous session. Is this supposed to work this way?
