### ISSUE TITLE
Occurrence Notes option is unchecked by default for the second file in Translation mode.

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#223]
translationCore Create - v1.0.0-rc.1
Related to #208.

For tN, when the file is opened first time it overwrites the file with English as reported in #208.
For the Second file(That has an alternative language translation file) that is opened, the Occurrence Notes option is unchecked by default so the content is the Target language is not seen.![Screen Shot 2020-07-17 at 11.32.14 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/c98687ca-2742-4f15-95ee-bec5ed8da8da)

**Comment by ancientTexts-net** [comment]
The FIX cannot be demonstrated in the preview.
But at least we can verify the change does not crash/break anything else.

True testing of this bug fix will need to be in the tc-create-app.

https://deploy-preview-14--datatable-translatable.netlify.app/

**Comment by elsylambert** [comment]
Looks good in translationCore Create - v1.0.0-rc.3
