### ISSUE TITLE
Integrate content validation RCL into tC Create App

### ISSUE THREAD

**Issue by BincyJ** [unfoldingWord/tc-create-app#235]
Use Case1 - On exiting a text field for which the content has been added/modified the content is validated using the content validation RCL.

Use Case2 -On loading a file for editing/translating, the content has been validated using the content validation RCL.

Need analysis on error handling.

https://unfoldingword.github.io/content-validation-rcl/

**Comment by PhotoNomad0** [comment]
**Notes:**
- tsv files: in datatable-translatable, DataTable.context, actions cellEdit

**Comment by birchamp** [comment]
@PhotoNomad0 can you list what checks we need to do in order to replicate what's being done in tC?

The goal here is to give the content team a way of validating their work without opening it in tC and clicking on every check.

**Comment by mandolyte** [comment]
More...

- Should we wait for the new TSV formats to be supported by tc-create?
- Opportunities for checks: 1) on fetch; 2) on edit (only for "row/cell oriented data"; 3) on save; 4) on demand
- For validation notices on open/save: how should they be presented? a) a list in a model dialog; b) a list in the slide-out panel; c) turn things red with hover-over popups containing a list; d) other ideas?
- link resolution might introduce time consuming delays in startup or save (or even edit); would not be an issue with "on-demand"

**Comment by mandolyte** [comment]
General requirements are [here](https://docs.google.com/document/d/1xKNMj3cfSFO_DqDeE3axcMTvcINVmqqbiq7CDk1A0qU/edit)

**Comment by mandolyte** [comment]
Technical design is [here](https://docs.google.com/document/d/1__uJl2KFn8pv2aGQyAukyr34RNZrMXsVPe9g7pzGCmg/edit#).

**Comment by mandolyte** [comment]
Connected this spike to issue for CV on-demand;
Will also connect to CV on open/save and on edit (per row, on blur event)
