### ISSUE TITLE
Show the horizontal toolbar for Markdown Files on scroll up

### ISSUE THREAD

**Issue by BincyJ** [unfoldingWord/tc-create-app#236]
Display the horizontal toolbar to be available as user scrolls up through the page, so that user can easily access the save/preview functionality as they edit instead of having to scroll back up to the top of the page each time. Toolbar should be hidden until user scrolls up.

![image.png](https://images.zenhubusercontent.com/5e84ee777ce69e38edc9290e/70576257-c89d-45e0-b50a-4ed0799033e5)

**Comment by mandolyte** [comment]
Note: when scrolling down in the file, the bar does not scroll off page. But when scrolling up, it does.

**Comment by mandolyte** [comment]
@ancientTexts-net At this time, there are two different ways this feature is working. This solution is one way and the TSV TN is another.

It was decided that:
- both should work the same way
- and markdown should work like TN

**Comment by ancientTexts-net** [comment]
![scrollbars-2.gif](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/55120a78-7d7d-4d8d-afd2-24a0a637df7c)

current status:

@birchamp @BincyJ @elsylambert @cckozie @mandolyte

**Comment by ancientTexts-net** [comment]
Zach Pennington: @Cecil New turns out, only markdown-translatable and tc-create-app need to change. With the new markdown-translatable, the APP includes fixes for both TSV and MD

**Comment by cckozie** [comment]
v1.1.1-rc.3 build 44-bde198f
It is interesting that when scrolling up slowly the bar does not appear, but I think the current implementation is sufficient to pass this issue.

**Comment by elsylambert** [comment]
translationCore Create - v1.1.1-rc.3 build 44-bde198f.
Toolbar shows up while scroll up and gets hidden when scroll down. Works as expected.
