### ISSUE TITLE
Increase Build Speed (Remove Cypress)

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/tc-create-app#240]

**Comment by ancientTexts-net** [comment]
Build speed appears to be mostly a function of CPU availability on netlify??

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/ee315267-f134-485d-ad2c-b20ae6c3d35c)

**Comment by ancientTexts-net** [comment]
QA Pass
