### ISSUE TITLE
CTRL+I is inserting underscores for italics 

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#249]
When the user selects text and presses CTRL+I to format the text in italics underscores are inserted in the markdown but are not rendered correctly.

Per the content team, italics are represented with a single underscore ie \_term\_.

DoD: When the user presses the italics hotkey (Ctrl+I) the text is enclosed by underscores and is rendered italicized.

**Comment by ancientTexts-net** [comment]
@RoyalSix good thinking on the unit test coverage! 

Looks great but I have 1 question about sg demo, please.  Thanks!

**Comment by ancientTexts-net** [comment]
@RoyalSix is this correct, please?

Underline is showing as <u>...</u> in the MARKDOWN file

Bold + italic: `**_Lorem_** `
Bold + underline: `<u>**ipsum**</u>`
Bold + italic + underline: `**<u>_dolem_</u>**`
Underline:  `<u>amet</u>`

**Comment by cckozie** [comment]
In Preview mode I'm seeing italicized text surrounded by single asterisks, not underscores. Is that the expected behavior in preview mode?

**Comment by RoyalSix** [comment]
markdown-translatable
