### ISSUE TITLE
Default paste should be unformatted

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#251]
Users shouldn't have to use the hotkey for unformatted paste.  This should work for right-click paste.   This must work for the OrigQuote field, but it is fine for all fields to function this way.

Options (in order of preference):
1. normal paste should be unformatted.
2. formatting should be stripped at paste time. 
3. formatting is stripped when exiting the field.  (not functioning properly )

DoD: users can easily paste plain text using one of the above options. 

**Note**: after working on developing this it was determined that a different solution was needed.  The text from the scripture pane needs to be copied to the clipboard as unformatted text.  See issue #444.

**Comment by elsylambert** [comment]
@RoyalSix @ancientTexts-net  Can we have the RCL link to test, Please?

**Comment by ancientTexts-net** [comment]
https://markdown-translatable.netlify.app/

**Comment by cckozie** [comment]
Looks good to me. I'm seeing the same result in Chrome after copying a multiple word string from a tN project and then using CMD+v, the context menu Paste, and the context menu Paste and Match Style.

**Comment by elsylambert** [comment]
Getting error "TypeError: Cannot read property 'removeEventListener' of null" when pasted a formatted text into the text box.

Seeing that it is not removing the formatted text.

**Comment by elsylambert** [comment]
Not seeing the fix in v1.0.5 rc4. Here is the screenshot of Original Text copied and pasted and the formatting was not removed.
![Screen Shot 2020-10-08 at 3.48.53 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/4d415ac8-5c5a-46c4-a03f-87b87219f424)

**Comment by elsylambert** [comment]
![Screen Shot 2020-10-12 at 12.28.09 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/435dca21-dfac-4c24-8ac0-5bfcbdede1c6)

![Screen Shot 2020-10-12 at 12.49.58 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/096f7313-857b-4845-8b9d-396408962969)
