### ISSUE TITLE
Update mui-datatable

### ISSUE THREAD

**Issue by ancientTexts-net** [unfoldingWord/tc-create-app#252]
Review the change log for mui-datatable
Consider
- should we upgrade to latest version?
- does it fix any state issues/etc
- any breaking changes?

This was spiked and it was determined that the upgrade wasn't breaking.

**Comment by ancientTexts-net** [comment]
@klappy

**Comment by ancientTexts-net** [comment]
passed in QA: tC Create v `1.0.3.rc-2`

**Comment by RoyalSix** [comment]
https://deploy-preview-18--datatable-translatable.netlify.app/
