### ISSUE TITLE
Display error when a user opens a file that can't be read by tC Create

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#255]
When the user clicks on files other than MD or TSV file like manifest.yaml or .gitignore they should receive an error instead of a spinner.

Error text:
"This file cannot be opened by tC Create. Please choose a markdown (.md) or tab-separated-values (.tsv) file."

**Comment by mandolyte** [comment]
Hmmm, that used to work. Should show the error message that used to show
instead of the spinner. I kept the old message and it is supposed to show
if not either an md or tsv file.


Cecil

**Comment by mandolyte** [comment]
Error message has been removed. There should be an else statement and it is no longer there. Go back in the change history log to find the missing code.

Source is `Translatable.js` in tc-create-app. Around line 63.

**Comment by mandolyte** [comment]
Here is the missing lines of code

```js
} else {
        _translatable = <h3 style={{ 'text-align': 'center'}} >Unsupported File. Please select .md or .tsv files.</h3>;
      }
```

**Comment by ancientTexts-net** [comment]
Passed in QA

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/2d1bec60-9012-47e6-90c5-56abdebf7d9f)
