### ISSUE TITLE
User with No Orgs: Infinite Spinner

### ISSUE THREAD

**Issue by ancientTexts-net** [unfoldingWord/tc-create-app#263]
Larry identified this issue when logging in with no orgs.  Is this a regression from the error message?

1. Identify a user with permissions on **no** orgs
2. Login
SEE: org list has infinite spinner

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/908bc48e-7183-42f6-b328-b3f4cc15613e)

DoD: A user with no organization receives an informative error.

**Comment by ancientTexts-net** [comment]
Testable in `translationCore Create - v1.0.4-rc.1`
https://develop--tc-create-app.netlify.app/

**Comment by elsylambert** [comment]
Verified in translationCore Create - v1.0.4-rc.1.

The user with no organization gets the message as shown below:
![Screen Shot 2020-09-10 at 5.16.42 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/aa443a70-65f6-4117-a4a2-c5cf42a9bb32)
