### ISSUE TITLE
Save button  'On' anytime user edits

### ISSUE THREAD

**Issue by BincyJ** [unfoldingWord/tc-create-app#320]
Currently the user is required to step out of the edit block to save text. 

Expected Behaviour:  User should be able to 'Save' while editing without having to step out of the block.

![image.png](https://images.zenhubusercontent.com/5e84ee777ce69e38edc9290e/8b7ef783-7848-4fa0-8315-244f1cdc5e43)

**Comment by cckozie** [comment]
The Save button should be enabled any time there is an unsaved change to any editable text, and disabled is there are no pending changes to save.

**Comment by elsylambert** [comment]
Looks good in v1.0.5-rc.5. Save button is enabled when there is unsaved edits and disabled when there is no change to save.
