### ISSUE TITLE
Typing a new line with > doesn't save as two lines

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#321]
Field Reported by Russian team during 8/12/20 training. 

When editing TA they were to type two parallel lines
```quote
> You make him to rule over the works of your hands;
> you have put all things under his feet (Psalm 8:6 ULT)
```

The editor runs these lines together when they are added to the target side.  
**Workaround:**  Copy the text from English. Edit each line individually.

**Comment by cckozie** [comment]
Tested in tCC tA Test Block Quotes

**Comment by ancientTexts-net** [comment]
`&gt;` bug is fixed.

Working on issue as stated:

I see the problem; outputFilters can fix this

**Comment by ancientTexts-net** [comment]
Turns out the behavior described in this issue is "normal" for markdown-to-html conversion:

http://demo.showdownjs.com/

If you end the line with two spaces, it formats the text the way requested in this issue.
This behavior is because ending a line with two spaces is markdown's way of declaring a <br/> break

https://www.markdownguide.org/basic-syntax/#line-breaks

**Comment by ancientTexts-net** [comment]
perhaps we can add a filter to make it "nicer" for RCL users

**Comment by RoyalSix** [comment]
https://deploy-preview-33--markdown-translatable.netlify.app/

**Comment by RoyalSix** [comment]
Confirmed issues working [here](https://5fa0967635343500ec6e7a78--tc-create-app.netlify.app/): 
 - `Typing a new line with > doesn't save as two lines`

**Comment by ancientTexts-net** [comment]
Testable in `v1.0.5-rc.7`

https://deploy-preview-488--tc-create-app.netlify.app/

@elsylambert 
@cckozie 

@BincyJ 
@birchamp

**Comment by ancientTexts-net** [comment]
Testable in `develop`, v `1.0.5-rc.7`

https://develop--tc-create-app.netlify.app/

@elsylambert 
@cckozie 

@birchamp 
@BincyJ

**Comment by cckozie** [comment]
Looks good in v1.0.5-rc.7

**Comment by elsylambert** [comment]
Not seeing the issue in translationCore Create - v1.0.5-rc.7.
