### ISSUE TITLE
Make add resource simpler

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#322]
User's should be able to add resources by using the full hyperlink to the resource or the relative one.
For example: 
- https://git.door43.org/ru_gl/ru_rlob
- /ru_gl/ru_rlob
-  ru_gl/ru_rlob

Use the master branch by default if no branch is specified. 

DoD: pasting the url to the repo of a scripture text will add that repo as a new resource

**Comment by ancientTexts-net** [comment]
@elsylambert  @birchamp  @BincyJ 

I have debugged the problem here.  Discrepancy between RCL and how the app handles resource links internal to the app

I would like to claim this issue.  assigning me

**Comment by ancientTexts-net** [comment]
Regarding the state issue with scripture not loading after adding custom resources:

I have tracked the issue back to August 20, differences between v1.0.2 and v1.0.3

https://github.com/unfoldingWord/scripture-resources-rcl/compare/v1.0.2...v1.0.3

**Comment by ancientTexts-net** [comment]
![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/4ff70f82-6697-4322-a6bf-f8e2fe6ec630)

**Comment by elsylambert** [comment]
Tested in Automated script by test-tCCreate/ Add New Resource

**Comment by elsylambert** [comment]
https://5fa0967635343500ec6e7a78--tc-create-app.netlify.app/ The given Resource link(https://git.door43.org/ru_gl/ru_rlob) loads fine for TIT, Ruth and 3JN but this makes all other books fail loading cause they cannot find the newly added resource.

**Comment by cckozie** [comment]
Here is a screenshot of what is displayed in tC when a verse has no text in a resource.
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/5c0e7bc2-6f92-4ab0-b706-ee8e448ec5b4)

**Comment by ancientTexts-net** [comment]
Testable in translationCore Create - `v1.0.5-rc.10`
https://develop--tc-create-app.netlify.app/


@elsylambert  @cckozie

**Comment by elsylambert** [comment]
translationCore Create - v1.0.5-rc.10. Looks good. Able to add the Resource by using a URL or a relative path. The app does not hang when a book does not have the resource. It shows blank in scripture pane in such case.

Tested in Automated script by test-tCCreate/ Add New Resource

**Comment by cckozie** [comment]
I am seeing some issues in v1.0.5-rc.10
1. If the pasted path doesn't exist or is not a valid repo, there is no indication to the user that something is wrong. Nothing happens when the add icon is clicked and there is no explanation of why.
2. I am unable to enter a URL using the keyboard. Only some keys actually work. Try typing in ru_gl/ru_rlob (or pretty much any other path) rather than pasting it. Only some keystrokes work.

**Comment by birchamp** [comment]
@ancientTexts-net @cckozie 
I've added issues #548 and #549 to cover the above. 

In reference to adding URLs manually please see the end of this video :) 
https://www.youtube.com/watch?v=2f453vD1-ew

**Comment by elsylambert** [comment]
Tested in Automated script by test-tCCreate/ Add New Resource- 
- Checks New resource by relative path
- Checks New resource by a URL.
- Checks if the other book crashes if the Resource is not available for that book.
