### ISSUE TITLE
The Save button is not enabled until the user clicks out of the element being edited

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/tc-create-app#331]
v1.0.2
The Save button should be enabled as soon as a user makes a change to any editable text.

**Comment by cckozie** [comment]
This should be implemented as part of #320.

**Comment by elsylambert** [comment]
This has been addressed in v1.0.5-rc.5

**Comment by cckozie** [comment]
Tested in TCC Test Multiple Sessions
