### ISSUE TITLE
Clicking on the <> on the organization page opens a blank page

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/tc-create-app#338]
Currently clicking on the organization <> link opens a blank page. The link should point to the org page on git.door43.org for that organization. - ie: https://git.door43.org/ru_gl

**DoD**: Clicking on the <> beside an organization opens a new tab and takes the user to the  door43 git page of that organization.

---
#### More info ####
v1.0.3.rc-2
[https://app.zenhub.com/files/191973535/670dc83a-3a44-4719-9c79-a13850af44de/download](https://app.zenhub.com/files/191973535/670dc83a-3a44-4719-9c79-a13850af44de/download)

I'm not sure where the user should land when clicked, but suggest these as possible options:
1. Fix the link
2. Disable the link if it doesn't point to something useful
3. Show an alert with useful information for the user

**Comment by elsylambert** [comment]
This button currently redirects to the Organization's Website. If an Organization does not have a website, the page is blank.

**Comment by elsylambert** [comment]
Tested in Test Case- Link to Organization page

**Comment by elsylambert** [comment]
Looks good in GiteaReactToolkit v1.3.11 and works as expected.

**Comment by ancientTexts-net** [comment]
Testable in `v1.0.5-rc.7`

https://deploy-preview-488--tc-create-app.netlify.app/

@elsylambert 
@cckozie 

@BincyJ 
@birchamp

**Comment by elsylambert** [comment]
Looks good in Preview https://deploy-preview-488--tc-create-app.netlify.app/

**Comment by ancientTexts-net** [comment]
Testable in `develop`, v `1.0.5-rc.7`

https://develop--tc-create-app.netlify.app/

@elsylambert 
@cckozie 

@birchamp 
@BincyJ

**Comment by cckozie** [comment]
v1.0.5-rc.7
Clicking on the link for the org translate_test takes me to https://git.door43.org/translate_test which I assume is correct

**Comment by elsylambert** [comment]
Tested in Katalon Test Case- Link to Organization page and it works as expected in translationCore Create - v1.0.5-rc.7.

**Comment by PhotoNomad0** [comment]
That is correct as far as my understanding.
