### ISSUE TITLE
Parallel scripture not loading up/slow in loading when scrolled down the chapters

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#34]
For a Romans Book as an example, the Parallel scripture loads up fine for Rom 1:1, 1:2...1:3....
when scrolled down to 1:16//1:17 the App seems to be hung as the Parallel scripture loads up.

![image.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/8a595a4d-2f19-4c0a-aa85-dd0b0c842700)

**Comment by klappy** [comment]
This should be improved but still a bit slow. Can you confirm that this has improved after release build alpha.20?

**Comment by elsylambert** [comment]
Not seeing this issue in alpha.20.

**Comment by elsylambert** [comment]
Still looks good in Beta 6.
