### ISSUE TITLE
Markdown blockquote disappearing

### ISSUE THREAD

**Issue by ancientTexts-net** [unfoldingWord/tc-create-app#356]
Jane Bussard reported: Markdown for blockquote is disappearing

Reproduce in tC Create:
1. Open a tA article: e.g., `translate/bita-humanbehavior/01.md`
2. Turn off sections
3. Find a block that has blockquote `> ... > ... >` characters
4. Click the block & blur out.
5. See: the blockquote content disappears

Turn OFF preview mode & this issue does not occur.

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/8dc2a508-9b84-481b-b7c8-c89f3bd9a1b6)

**Comment by ancientTexts-net** [comment]
https://unfoldingword.zulipchat.com/#narrow/stream/207526-wg-tools/topic/tC.20Create.20App.20(GLtS)

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/001f3aff-d44d-4f95-bbe5-b53891c2ba65)

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/05a7c70e-2712-4849-b842-ac02cf94d798)

**Comment by ancientTexts-net** [comment]
Testable in `translationCore Create - v1.0.4-rc.1`
https://develop--tc-create-app.netlify.app/

**Comment by elsylambert** [comment]
Verified in translationCore Create - v1.0.4-rc.1. The issue does not exist in tA. Markdown blockquote is persisted when tabbed out of the block.
