### ISSUE TITLE
OT Punctuation breaks highlighting - reported by Joel (Parashah Setumah marker ס etc )

### ISSUE THREAD

**Issue by ancientTexts-net** [unfoldingWord/tc-create-app#358]
We have an issue in tC Create, although I don't think it's an issue in tCore (although I can't test it yet for sure until we publish Nehemiah UTN). In Nehemiah 3:2, there is a setumah in the middle of the verse, i.e. a Hebrew character that is not part of the text. From my experience, tCore knows that these characters aren't part of the text. But tC Create seems to think that this setumah is part of the Hebrew word. This is causing tC Create not to recognize the OrigLQuote in note ID [u2s6]. The USFM code in the UHB has a space there to separate the setumah character from the rest of the Hebrew text, but tC Create apparently doesn't read it. The point is that I think this note is correct, but tC Create doesn't recognize the OrigLQuote.

ס

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/cab34be1-4f02-417f-bd73-4652fc89119c)

**Comment by ancientTexts-net** [comment]
TODO: investigate if the recently updated normalizer is breaking because of non-breaking space?

TODO: consult how we do it in tC

**Comment by ancientTexts-net** [comment]
birch adds: 

last character on line 600 of https://git.door43.org/unfoldingWord/hbo_uhb/src/branch/master/16-NEH.usfm

**Comment by ancientTexts-net** [comment]
![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/2fafac92-66c4-45fe-8b70-ec063e1d4919)

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/dbf43786-288d-4450-95b5-d3968e87b4fd)

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/a5b8e7a1-1a38-43aa-918d-e7ee1d4c856e)

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/67841f5c-c7bb-4645-a44e-d4e9dd365511)

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/7052ec29-ba7b-48c1-bf70-abd5b42dc0a7)

**Comment by ancientTexts-net** [comment]
![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/6ea0b682-500d-4844-882d-d698b634cdd3)

**Comment by ancientTexts-net** [comment]
![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/a4f70c3c-9eec-4a31-bb2a-cd5bab97dd4e)

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/3b2a25cf-9372-4e9b-8f6d-002bdb873cdd)

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/240bafcf-4405-4196-a467-25719590770a)

**Comment by ancientTexts-net** [comment]
https://unfoldingword.zulipchat.com/#narrow/stream/207526-wg-tools/topic/OT.20Hebrew.20usfm

**Comment by ancientTexts-net** [comment]
Testable in `translationCore Create - v1.0.4-rc.1`
https://develop--tc-create-app.netlify.app/

**Comment by elsylambert** [comment]
Not seeing this issue in translationCore Create - v1.0.4-rc.1
OT punctuations are no longer breaking the highlights.

**Comment by cckozie** [comment]
Tested in Katalon tCC tN Test Copy OrigLangQuote
