### ISSUE TITLE
Spike []: DCS Repo workflow

### ISSUE THREAD

**Issue by BincyJ** [unfoldingWord/tc-create-app#359]
The current pull request and saving changes process is quite complicated. Need to outline the current steps and possibility of automating these steps into the app for a user friendly manner. Based on admin rights, user should be able to perform pull requests, view and action conflicts on the app.

For reference: https://github.com/unfoldingWord/tc-create-app/issues/61

Russia team scenario: (Need to be able to recreate the steps)
- Alex translated tA articles related to the book Titus.
- After he finished and merge it to Master and deleted his repository. 
- We allocated that book tA articles to Yuri to check.
- He started a check and at the end of the work we found out that he has a different version from master. Our understanding that Yuri opened tA before we merged Alex's repo to master. Yes, we said/wrote please don't open tA files but people do.
- That means we have duplicated work now 

Need to outline the branch workflow, 
- how it works when a single user makes edits. (is the workflow different for different resources)
- Multiple user makes edits to same file.
- Outline how the files get updated from creation of file in user branch to the master 
- Workflow in case of a new file
- Workflow in case of an existing file
- Do we leverage DCS or do we use other APIs/RCLs

stretch goal- How can we include pull request in the front-end workflow.

**Comment by RoyalSix** [comment]
1. Is there a difference in the PR process for translating and editing?

2. The current workflow for the PR button creates a link that is like this: `https://qa.door43.org/unfoldingWord/en_tn/compare/master...{{my_org}}:{{my_user}}-tc-create-1`
Was this ever the correct method? Or should it always be:
`https://qa.door43.org/{{my_org}}/en_tn/compare/master...{{my_org}}:{{my_user}}-tc-create-1`

@birchamp @BincyJ @klappy

**Comment by BincyJ** [comment]
https://drive.google.com/file/d/1HQqLWeaTj6aLCzJrIGQCAfA-zgwcpjmh/view?usp=sharing

**Comment by birchamp** [comment]
@richmahn We need to what DCS features don't exist but will be needed.

- that there will be a conflict before merge
- what the conflicts are (diff) or at least what files are conflicting
- merge conflict resolution

Task:
- [ ] research merge conflict server or client solutions

**Comment by richmahn** [comment]
1. We can know that there is a merge issue, both when making a pull with the API, querying the pull and attempting to merge.

2. Same lines and adjacent lines show up as conflict because diff goes by content and not line numbers.

3. A immediate option is to use [Github Desktop](https://desktop.github.com) and train people how to set up the repo, change the branch and do a merge of master into that branch, resolving conflicts in the UI, and pushing back to DCS.
