### ISSUE TITLE
BUG:Filter crashes the app. Initially reported as ID duplicated and now deleted. 

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#365]
Maria on the Russian team sent this screenshot and was concerned that the he note on knowledge from Titus 1:1 is above the intro for chapter 1.  

![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/d565006e-e786-4dbc-8dd5-44db87031976)

Further investigation shows that the ID for that note is `xyz8` and the commit history shows that it's duplicated here:
https://git.door43.org/ru_gl/ru_tn/commit/62ff82e880fbb46200caf62dac7632fb48f27073

![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/c8ec778d-1f80-469b-893c-25e2bd55f115)

later commits show that BOTH record with ID `xyz8` are now missing. 
https://git.door43.org/ru_gl/ru_tn/src/branch/mkaryakina-tc-create-1/en_tn_57-TIT.tsv

**Comment by ancientTexts-net** [comment]
https://datatable-translatable.netlify.app/

**Comment by elsylambert** [comment]
@RoyalSix Please give some details on what was the issue and how did you reproduce it?

**Comment by RoyalSix** [comment]
This issue was happening on many different scenarios, the one mentioned above is not the only one.

The main problem was with the filtering. 
If you visit this link https://5f3e3bcb406b170008b6a514--datatable-translatable.netlify.app/
That is before the fix

The method to replicate the issue is to put the filter on chapter 3, note how the verse 3:15 is in front of 3:intro. that is not right.

Now if you visit the latest datatable translatable: https://datatable-translatable.netlify.app/
and repeat the steps above you will see that 3:intro is before 3:15.

@elsylambert @cckozie

**Comment by elsylambert** [comment]
@RoyalSix Thanks for adding steps for this issue. In v1.0.5-rc.5, adding filter is crashing the app.
- open a .tsv.
- Add filter, i.e choose any chapter from the drop down list. Note that the App crashes.
Here is the screen recording:
[https://app.zenhub.com/files/191973535/e8528439-9e3d-478c-ae50-34552da605ee/download](https://app.zenhub.com/files/191973535/e8528439-9e3d-478c-ae50-34552da605ee/download)

**Comment by ancientTexts-net** [comment]
![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/5bffdb58-661b-4d60-bc91-6b5d85532fd9)

filter issue

**Comment by cckozie** [comment]
Tested in tCC Test App Crashes

**Comment by ancientTexts-net** [comment]
Crashing is fixed.

I see strange behavior when I move to later pages:
Intro still shows up at top

1. open a tsv
2. click to another page
3. notice: book intro still shows at top of page


![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/a98c18fa-e91f-45df-b29d-e1767454eef3)

**Comment by ancientTexts-net** [comment]
@elsylambert  @cckozie  @RoyalSix    ^^

**Comment by RoyalSix** [comment]
Issues confirmed fixed [here](https://5fa0967635343500ec6e7a78--tc-create-app.netlify.app/): 
 - `Intro still shows up at top`
 - `App Crashes after filter`
 - `BUG:Filter crashes the app. Initially reported as ID duplicated and now deleted.`

**Comment by ancientTexts-net** [comment]
Thank you @RoyalSix  -- which PR(s) include(s) these most recent changes please?

**Comment by ancientTexts-net** [comment]
Testable in `v1.0.5-rc.7`

https://deploy-preview-488--tc-create-app.netlify.app/

@elsylambert 
@cckozie 

@BincyJ 
@birchamp

**Comment by elsylambert** [comment]
Not seeing filter crash in the preview https://deploy-preview-488--tc-create-app.netlify.app/

**Comment by ancientTexts-net** [comment]
Testable in `develop`, v `1.0.5-rc.7`

https://develop--tc-create-app.netlify.app/

@elsylambert 
@cckozie 

@birchamp 
@BincyJ

**Comment by cckozie** [comment]
Looks good in v1.0.5-rc.7

**Comment by elsylambert** [comment]
Not seeing the issue in translationCore Create - v1.0.5-rc.7.
