### ISSUE TITLE
"Sorry, no matching records found" message upon opening a TN file 

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#366]
Two Russian users are reporting that opening a TN tsv file returns a: "Sorry, no matching records found". Contact Dima Savisky <dimasavisky@gmail.com> for more info.

![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/bafb5b84-ccb1-43f3-8ede-a19b3e221c50)

Attempts to fix: 
Refresh
Logout/login
Changing browser to Chrome
Deleting branch.

**Comment by BincyJ** [comment]
@elsylambert can you check and confirm if you can recreate this issue? Thanks.

**Comment by elsylambert** [comment]
@BincyJ @birchamp  Not able to reproduce in translationCore Create - v1.0.3. I can open JON.tsv and tested few other files as well

**Comment by BincyJ** [comment]
@elsylambert they are unable to open en_tn_32-JON.tsv and en_tn_08-RUT.tsv. 

@ancientTexts-net and @richmahn.

**Comment by richmahn** [comment]
This was due to the "tsv" files being actually comma-delimited rather than tab-delimited.
