### ISSUE TITLE
Manage Versions: Adding X to close the Menu

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/tc-create-app#375]
v1.0.3
There is an inconsistency in providing an "X" to close popup menus
The View Columns and Filter Table menus show an X to allow the user to close them. The Manage Versions menu does not.
Suggest adding the X to the Manage Versions menu.

The Manage versions dropdown should have an X like the other dropdowns
![Screen Shot 2020-11-03 at 1.13.32 PM.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/824c6837-50f2-44f0-ae10-ba6bb5c65acb)
![Screen Shot 2020-11-03 at 1.12.34 PM.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/2b21ecca-bbbf-4514-a7f9-44c57f816f78)

**Comment by birchamp** [comment]
@elsylambert So this is blocking one of your scripts? Is that correct?

**Comment by elsylambert** [comment]
@birchamp Yes. ;)

**Comment by elsylambert** [comment]
translationCore Create - v1.2.0-rc.2 build 28-4717783. X button is added to the Mange version modal. looks good.
