### ISSUE TITLE
Save not working for tA articles in v1.0.4-rc.1

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/tc-create-app#379]
Save does work when editing tN, but not tA.

Open a tA article and make an edit, then blur.
Click the Save button.
Note that the Save button stays enabled.
Wait for a while
Start a new session to edit the same tA article.
Note that the previous edit was not saved.

[tC Create - Google Chrome 2020-09-10 16-07-06.zip](https://github.com/unfoldingWord/tc-create-app/files/5204817/tC.Create.-.Google.Chrome.2020-09-10.16-07-06.zip)

**Comment by ancientTexts-net** [comment]
Thanks Kos.

I see same behavior for **tW**

here is the JS error:
![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/1dd72679-722e-402a-bc96-e59dbb64c1bf)

I think this is related to  **160**

**Comment by ancientTexts-net** [comment]
Testable in 1.0.4-rc.2

https://develop--tc-create-app.netlify.app/

**Comment by cckozie** [comment]
I'm still not seeing tA being saved in v1.0.4-rc.2. After clicking the save button it does not become disabled again, and when I reopen the project, the text has not been changed as expected.

**Comment by elsylambert** [comment]
![Screen Shot 2020-09-17 at 11.08.49 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/c21d96c8-2dff-4067-9289-028272151b77)

v1.0.4-rc.2 - I am able to save but the tool tip stays on the screen and seems frozen.

**Comment by elsylambert** [comment]
v1.0.4-rc.2. save is working fine for tA and tW.

**Comment by cckozie** [comment]
I have now experienced this in both Chrome and FireFox. If a session is left open on a tA article (I think on Chrome it was opened for hour or so, and on Firefox 2+ hours), the Save does not work. The icon stays enabled and the data does not get saved.
On both browsers, after refreshing and logging in, it does work correctly.

**Comment by cckozie** [comment]
Is there an expectation that users can leave the browser opened in a project for any amount of time and everything will be fine when they return?
I think the real danger is that when they have no indication that the data was saved, they might assume that data was saved when it was not. Violating the cardinal rule of not losing data.
We may want to consider adding a positive indicator that the save was successful other than the icon going to the disabled state.

**Comment by ancientTexts-net** [comment]
Thanks Kos.

Are you saying that if you leave the browser IDLE for a long time, the session expires & it won't save?

thanks

**Comment by cckozie** [comment]
Another update - It appears that the save problem may be related to multiple sessions. I had a single session that was still working after sitting open all night. I opened a second session on the same machine and after sitting idle for 1 1/2 hours the first session did not save and the second session did save.

**Comment by ancientTexts-net** [comment]
Here is the JS error that occurs in that condition

@cckozie 
@elsylambert 

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/996977f7-605a-41fe-aef8-9d178759ae03)

**Comment by ancientTexts-net** [comment]
Here was Birch & Elsy's recommendation:

- Display warning on save, if save fails.
- Why do we delete application token?  Is it possible to prevent this?
- Can we confirm the issue is strictly related to multiple sessions?  i.e., Can we reproduce any timeouts within a single session?

thanks

**Comment by elsylambert** [comment]
#397 written up for - "Display warning on a Save failure"

**Comment by elsylambert** [comment]
Save is working fine for tA articles. #397 will cover the save issues encountered due to session expiration with DCS.
