### ISSUE TITLE
Side menu bar shows up blank when using the filter

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#39]
Noticed this issue when testing #38.
After the up/down button is clicked when the filter is on, the app lands on first page> Click on the side menu option(the hamburger icon), it shows up a blank menu as a result of slow loading
![image](https://user-images.githubusercontent.com/51806180/71915085-008f8200-3149-11ea-83cc-dda1269b963d.png)
Similarly, when we move to the next pages from the footer Next button to go to the later chapters (approx 1000th page), it brings up a blank Menu as it loads up very slow.
![image](https://user-images.githubusercontent.com/51806180/71993918-e36cb900-3205-11ea-922b-aaa9f5b12462.png)

**Comment by mandolyte** [comment]
@elsylambert Do the performance enhancements make this acceptable now? I went to book of Acts, set rows to 100, clicked a couple of times to get to the 300 range of rows and then immediately opened the side panel. The panel populated in about 4s.

**Comment by elsylambert** [comment]
@birchamp @mandolyte  Looks good in translationCore Create - v1.0.0-beta.5.
