### ISSUE TITLE
Misalignment of block text in tA when Section is off.

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#393]
![Screen Shot 2020-09-17 at 11.13.00 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/ea2909f3-d2d5-4320-9e7a-1620108db02e)
v1.0.4-rc.2

- go to a tA article(eg. translate/bita-humanbehavior/01.md)
- toggle the section button to remove the section 
- scroll down the page and note that the blocks are misaligned as in the screenshot.

**Comment by elsylambert** [comment]
This can also be replicated when Blocks button is toggled with the Section kept as OFF.

**Comment by BincyJ** [comment]
@ancientTexts-net do we retest this? Thought the misalignment issue was fixed. Can you confirm?

**Comment by birchamp** [comment]
@elsylambert Can you re-test?

**Comment by elsylambert** [comment]
moving to watchlist as Section button might get fixed with rc.7. will retest after that.

**Comment by elsylambert** [comment]
Not seeing the issue in translationCore Create - v1.0.5-rc.7.

**Comment by cckozie** [comment]
v1.0.5-rc.10
@elsylambert - This doesn't seem right, but I'm not sure if this is different than what you were seeing.
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/967c9457-a615-49f8-a1e1-d2abdf079c95)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/24ce3dc1-36c7-4fe7-a76b-9320a23e15ec)
