### ISSUE TITLE
Prompt users to login if DCS returns an error on Save

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#397]
When attempting to save a file, Create may get a communications error from DCS. The user should be notified that "A communication error has occurred. Please login." and prompted to re-login via a modal dialog. If login is successful then save. If there is a communication error with DCS on login, that login error should be communicated to the user. 

**DoD:** When a save could potentially fail ([#379](https://github.com/unfoldingWord/tc-create-app/issues/397)) the user should be prompted to login to see if the save can be completed. 

![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/a6f338ca-e41a-4655-927c-06ae2c847160)

**Comment by elsylambert** [comment]
![Screen Shot 2020-10-16 at 10.45.55 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/cca01ec3-383c-40b6-8c9a-4f22b7fe0e66)

**Comment by ancientTexts-net** [comment]
@elsylambert , thank you.
I see the problem.  Working on fix now

**Comment by ancientTexts-net** [comment]
@elsylambert  @cckozie -- thank you.
This might be a condition we haven't considered?  I have a recommended fix.

Please see below:

The FIRST failure gets the `403 Forbidden` error (as expected)
since the gitea auth token is expired now:
> ![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/9d0a6cef-c565-44e5-ac6d-ec0f24245f6a)

But after logging in, we get an error that the `sha` (checksum) for the file has changed.  
> ![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/0c382494-8c37-4ed0-bc4a-910785156a4c)

I have a recommendation for fix

**Comment by ancientTexts-net** [comment]
GOOD CATCH @elsylambert , @cckozie 
great job

**Comment by elsylambert** [comment]
- User logs in session 1>Makes changes> Not saved.
- User logs into another session (Session 2) but does not edit the file.
- User goes back to session 1 and clicks on Save>Login prompts comes up and on Login, the changes are saved.

**Comment by cckozie** [comment]
v1.0.5-rc.6
The login prompt is displayed when the error condition is met. The problem with the save then failing when the user attempts a login has been moved to another issue.
