### ISSUE TITLE
Parallel Scripture viewer missing in the develop branch

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#415]
Parallel Scripture viewer is missing in the develop branch 1.0.4.

**Comment by ancientTexts-net** [comment]
Thank you @elsylambert,

This issue will be resolved whenever we can finish the `App Integration queue

thank you!!

**Comment by elsylambert** [comment]
v1.0.5-rc.5. Parallel Scripture Viewer is displayed and the initial bug has been fixed but the "Expand All Scripture " toggle does not work now.

**Comment by elsylambert** [comment]
Tested in Automated script by test-tCCreate/ Parallel Scripture Viewer.

**Comment by RoyalSix** [comment]
Confirmed issues fixed [here](https://5fa0967635343500ec6e7a78--tc-create-app.netlify.app):
 - ` "Expand All Scripture " toggle does not work now.`
 - `Parallel Scripture viewer missing in the develop branch`

**Comment by ancientTexts-net** [comment]
Testable in `v1.0.5-rc.7`

https://deploy-preview-488--tc-create-app.netlify.app/

@elsylambert 
@cckozie 

@BincyJ 
@birchamp

**Comment by elsylambert** [comment]
Looks good in Preview. Parallel Scripture viewer works as expected and the Expand All Scripture toggle works fine.

**Comment by ancientTexts-net** [comment]
Testable in `develop`, v `1.0.5-rc.7`

https://develop--tc-create-app.netlify.app/

**Comment by ancientTexts-net** [comment]
Testable in `develop`, v `1.0.5-rc.7`

https://develop--tc-create-app.netlify.app/

@elsylambert 
@cckozie 

@birchamp 
@BincyJ

**Comment by elsylambert** [comment]
Tested in Katalon script by test-tCCreate/ Parallel Scripture Viewer. Looks good in V 1.0.5-rc 7

**Comment by cckozie** [comment]
Looks good in v1.0.5-rc.7
