### ISSUE TITLE
Web elements with missing or non-working identifiers

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/tc-create-app#420]
These elements are not findable in Katalon except by using XPath.

**Comment by cckozie** [comment]
![tN preview button.jpg](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/c7e8bd96-117e-401a-8066-d0501b9d410f)

**Comment by cckozie** [comment]
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/2f6ea11c-f85e-4c65-aab7-33c0441f5305)

**Comment by cckozie** [comment]
This one has an id attribute, but it is related to two different elements
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/9b6c1405-90ce-4a81-9f9c-4fc7c884d143)

**Comment by cckozie** [comment]
If I load a Titus tN project and identify some elements using Katalon Attributes, then load an Ecclesiastes project using the drawer, then reload the Titus project using the drawer, the original elements are no longer findable using Katalon Attributes. I must switch to using Xpath to find them. In some situations, Xpath is unable to locate a single element, but finds multiple elements instead.
It is unclear whether this actually relates to loading from the drawer, or just loading a different project in the same session.

**Comment by ancientTexts-net** [comment]
we met today; as I understand status:

- aria-label was added to datatable translatable Save & Preview
- Ecclesiastes ID is OK (we recommend use xpath with [@id='.....'])

- devs still need to add "target" and "source" to datatable cell (possibly a parent container)

**Comment by ancientTexts-net** [comment]
Testable in translationCore Create - `v1.0.5-rc.10`
https://develop--tc-create-app.netlify.app/


@elsylambert  @cckozie

**Comment by cckozie** [comment]
v1.0.5-rc.10
The aria-label has been added to the Preview button in tN, but it is missing on the enabled Save button.
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/abb01e49-e8c1-49ef-823e-b623d477b45e)
