### ISSUE TITLE
Adding a line feed in block quote text changes '>' to '&gt;' when Preview is enabled

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/tc-create-app#424]
v1.0.5-rc.1
movie at [https://app.zenhub.com/files/191973535/74c8eb5b-0de2-4404-b1f2-72967fc07d2f/download](https://app.zenhub.com/files/191973535/74c8eb5b-0de2-4404-b1f2-72967fc07d2f/download)
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/03561958-b5a9-4701-acf0-4942f067d553)

**Comment by cckozie** [comment]
Tested in tCC tA Test Block Quotes and Sections

**Comment by elsylambert** [comment]
@ancientTexts-net Please move it back to QA when it is testable. Not seeing the changes in v1.0.5-rc.6.

**Comment by ancientTexts-net** [comment]
HTML is garbled if PREVIEW mode turned off

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/590f02f3-5635-4182-bb6d-04fff56aff2a)

**Comment by ancientTexts-net** [comment]
@elsylambert  @cckozie 

Can you please help me see what's going on in RCL?
http://localhost:6060/#/Translatable?id=translatable-1

- turn off preview
- turn off blocks/sections
- edit
- turn on preview
- NOTICE: loses some content

**Comment by elsylambert** [comment]
@ancientTexts-net  Cant open the link(local Host). Can you please send the link to RCL?

**Comment by ancientTexts-net** [comment]
Thank you @RoyalSix  , @elsylambert  :

https://deploy-preview-35--markdown-translatable.netlify.app/

As of now the only issues I see are that the FIRST time you edit the markdown document (with sections & blocks OFF), it sends cursor to the bottom of the file

**Comment by RoyalSix** [comment]
@ancientTexts-net I am not seeing that behavior on the example you sent https://deploy-preview-35--markdown-translatable.netlify.app/#/Translatable?id=translatable-1

**Comment by elsylambert** [comment]
https://deploy-preview-35--markdown-translatable.netlify.app/- Turn Off the toggle for Blocks and the text goes blank.

**Comment by RoyalSix** [comment]
Issues confirmed fixed:
 - `Turn Off the toggle for Blocks and the text goes blank.`
 - `As of now the only issues I see are that the FIRST time you edit the markdown document (with sections & blocks OFF), it sends cursor to the bottom of the file`
 - `HTML is garbled if PREVIEW mode turned off`
 - `Adding a line feed in block quote text changes '>' to '&gt;' when Preview is enabled`

**Comment by ancientTexts-net** [comment]
Testable in `v1.0.5-rc.7`

https://deploy-preview-488--tc-create-app.netlify.app/

@elsylambert 
@cckozie 

@BincyJ 
@birchamp

**Comment by elsylambert** [comment]
Looks good in Preview.https://deploy-preview-488--tc-create-app.netlify.app/

**Comment by ancientTexts-net** [comment]
Testable in `develop`, v `1.0.5-rc.7`

https://develop--tc-create-app.netlify.app/

@elsylambert 
@cckozie 

@birchamp 
@BincyJ

**Comment by elsylambert** [comment]
Not seeing this issue in translationCore Create - v1.0.5-rc.7

**Comment by cckozie** [comment]
Looks good in v1.0.5-rc.7
