### ISSUE TITLE
App Crash on the following conditions: v 1.0.5 rc2

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#428]
-App is crashing when Section button is clicked for .md files.
-App crashes when file (both tsv and md)is selected from Hamburger Menu selection

**Comment by ancientTexts-net** [comment]
here's what I get onblur

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/04b571b6-405b-4ad2-9913-cee96f05ecda)

**Comment by ancientTexts-net** [comment]
the onblur issue above is fixed I think

**Comment by elsylambert** [comment]
The app no longer on the above mentioned conditions but Section button has some issues which are reported separately in

**Comment by cckozie** [comment]
Tested in tCC tA Test Block Quotes and Sections
