### ISSUE TITLE
Spike:  [12] Auto Save Feature

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/tc-create-app#43]
What triggers do we want to fire autosave?
Do we think this is safe if inadvertent actions are taken.

Also, do we save on blur like the changed status happens currently on the save icon.

- How does data retrieval work?
- Recover data from user branch?

**Comment by klappy** [comment]
If we auto-save to the browser's indexedDB, this paves the way to offline mode.

**Comment by cckozie** [comment]
Should it be a user controlled option, perhaps a checkbox on the login page?

**Comment by ancientTexts-net** [comment]
- "always" save to indexDB
- save to server when online
- load from indexDB (but not if stale? what if offline?)

**Comment by ancientTexts-net** [comment]
does mui-datatable re-render like the old issue we had?

**Comment by BincyJ** [comment]
@ancientTexts-net to update documentation on spike.

**Comment by ancientTexts-net** [comment]
IndexedDB storage:

Recent articles:

https://web.dev/storage-for-the-web/#indexeddb


Older articles:

https://stackoverflow.com/questions/5692820/maximum-item-size-in-indexeddb

https://developer.chrome.com/docs/apps/offline_storage/#temporary
https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria#storage_limits

**Comment by ancientTexts-net** [comment]
FYI can test at:

https://60d090630db00b179eedeef9--tc-create-app.netlify.app/

**Comment by BincyJ** [comment]
Please add issues to close out the spike.
