### ISSUE TITLE
Target section goes blank when Section/Blocks are toggled

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#437]
v1.0.5-rc.5
Target section goes blank when Section/Blocks are toggled.
- Open.md file(tA or tW).
- Click on Sections button and then Blocks. Note that the Target side has gone blank.
- Toggle is back . Note that the Source side has a blank space and the content is pushed down.

Here is the screen recording:
[https://app.zenhub.com/files/191973535/79155025-a9a3-44ea-bd4d-38c19b68db47/download](https://app.zenhub.com/files/191973535/79155025-a9a3-44ea-bd4d-38c19b68db47/download)

**Comment by cckozie** [comment]
Tested in tCC tA Test Block Quotes and Sections

**Comment by RoyalSix** [comment]
https://deploy-preview-35--markdown-translatable.netlify.app/

**Comment by RoyalSix** [comment]
Confirmed issues fixed [here](https://5fa0967635343500ec6e7a78--tc-create-app.netlify.app/):
 - `Target section goes blank when Section/Blocks are toggled`

**Comment by ancientTexts-net** [comment]
Testable in `v1.0.5-rc.7`

https://deploy-preview-488--tc-create-app.netlify.app/

@elsylambert 
@cckozie 

@BincyJ 
@birchamp

**Comment by elsylambert** [comment]
Not seeing the issue in the Preview https://deploy-preview-488--tc-create-app.netlify.app/

.

**Comment by ancientTexts-net** [comment]
Testable in `develop`, v `1.0.5-rc.7`

https://develop--tc-create-app.netlify.app/

@elsylambert 
@cckozie 

@birchamp 
@BincyJ

**Comment by cckozie** [comment]
Looks good in v1.0.5-rc.7

**Comment by elsylambert** [comment]
Not seeing the issue in translationCore Create - v1.0.5-rc.7.
