### ISSUE TITLE
Table Filter duplicating text in options

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/tc-create-app#44]
<img width="1440" alt="Screen Shot 2020-01-08 at 4 08 28 PM" src="https://user-images.githubusercontent.com/118073/72016106-23956100-3231-11ea-9e33-ff63284ee167.png">

**Comment by klappy** [comment]
Addressed along with #68.

**Comment by elsylambert** [comment]
Not seeing the issue in v0.9. beta-4. Filter view looks good and displays correct results on selection.
