### ISSUE TITLE
Search functionality: App crashes on Search in tN

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#440]
v1.0.5-rc.5
App is crashing when you type in something to search in the search bar.

**Comment by cckozie** [comment]
Tested in tCC Test App Crashes

**Comment by RoyalSix** [comment]
Fixed by #461

**Comment by RoyalSix** [comment]
Confirmed issues fixed [here](https://5fa0967635343500ec6e7a78--tc-create-app.netlify.app/): 
 - `Search functionality: App crashes on Search in tN`

**Comment by ancientTexts-net** [comment]
Testable in `v1.0.5-rc.7`

https://deploy-preview-488--tc-create-app.netlify.app/

@elsylambert 
@cckozie 

@BincyJ 
@birchamp

**Comment by elsylambert** [comment]
Not seeing the crash on Search in Preview. https://deploy-preview-488--tc-create-app.netlify.app/

**Comment by ancientTexts-net** [comment]
Testable in `develop`, v `1.0.5-rc.7`

https://develop--tc-create-app.netlify.app/

@elsylambert 
@cckozie 

@birchamp 
@BincyJ

**Comment by cckozie** [comment]
Looks good in v1.0.5-rc.7

**Comment by elsylambert** [comment]
Not seeing the issue in translationCore Create - v1.0.5-rc.7.
