### ISSUE TITLE
Text from the scripture pane should be copied/pasted as plain text

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#444]
When the user copies and pastes text from the scripture pane the text should be pasted as unformatted text. Otherwise, the text should remain formatted when it is copied.

This issue came out of a previous attempt to fix this #251 and spike #438 

This is to be fixed by #424

DoD: Copying formatted or highlighted text from scripture pane won't retain highlighting or other HTML styles on paste. Pasting text copied from source in preview mode to target in preview mode will preserve formatting.

**Comment by cckozie** [comment]
Katalon tests in tCC tN Test Copy OrigLangQuote

**Comment by RoyalSix** [comment]
Confirmed issues working [here](https://5fa0967635343500ec6e7a78--tc-create-app.netlify.app/): 
 - `Text from the scripture pane should be copied/pasted as plain text`

**Comment by ancientTexts-net** [comment]
@RoyalSix 

@elsylambert 

I still see HTML paste in v1.0.5-rc.7
not sure I understand DOD here

https://deploy-preview-488--tc-create-app.netlify.app/

**Comment by RoyalSix** [comment]
Pasting with preview mode on removes formatting @ancientTexts-net 
That is the behavior I am seeing in the preview

**Comment by ancientTexts-net** [comment]
Works with `yalc` in tc-create-app

![444-highlight.gif](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/157d3520-28e4-4a94-87c3-044a9f6b3a96)

**Comment by ancientTexts-net** [comment]
compare to PROD

![444-prod-notwork.gif](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/8e4d9d42-1299-4294-8dae-d3affe426ce5)

**Comment by cckozie** [comment]
Looks good in v1.1.0-rc.3 on Mac. Need to test in Windows.
Not seeing highlighting now in OrigQuote. 
Not seeing weird formatting when doing copy/paste into OrigQuote.

**Comment by elsylambert** [comment]
Looks good in translationCore Create - v1.1.0-rc.3. Able to paste unformatted text from scripture pane to Original Quote box. In Preview mode, pasting preserves the formatting. Works as expected.
