### ISSUE TITLE
Greek words with Punctuation are tokenized improperly.

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/tc-create-app#45]
This causes issues where alignments are not highlighted properly.

![Screen Shot 2020-01-08 at 4.12.55 PM.png](https://images.zenhubusercontent.com/568146ca638e718c995faa57/3b193801-9700-484a-9ab2-fc484188f983)

**Comment by klappy** [comment]
This has been tracked down to a content issue: https://git.door43.org/unfoldingWord/el-x-koine_ugnt/pulls/160

**Comment by klappy** [comment]
Fix merged and published as `scripture-resources-rcl@0.12.5`

**Comment by elsylambert** [comment]
Verified in alpha-26. There are some cases where the highlights are not proper as reported in
