### ISSUE TITLE
v1.0.5-rc.6 opens tN files with the blue bar and repo chips scrolled out of view

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/tc-create-app#455]
(this caused Katalon scripts to fail)

tA and tW both open properly in both develop and production

In v1.0.5-rc.6 tN files opens like this:
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/a9dfb11e-6ed4-4e0f-8f23-aeb9b4851f0b)

In v1.0.4 (production)  tN, tA, and tW files open like this:
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/8053c1ed-4d82-4c05-8a05-ad73154a2dc0)

**Comment by cckozie** [comment]
Tested in TCC tN Test Column Options

**Comment by elsylambert** [comment]
Looks good in v1.1.0-rc.3.

**Comment by cckozie** [comment]
Looks good in v1.1.0-rc.3.
