### ISSUE TITLE
Crash on pagination (on develop branch, not master)

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/tc-create-app#463]
To reproduce:
- go to: https://develop--tc-create-app.netlify.app/
- login
- org: select unfoldingWord
- resource: select translation notes
- language: select english
- file: select Ruth

When page is populated (rows 1 to 25), 
- click to go to next page (rows 26 to 50), 
- click to go to next page again

The page crashes. Contents of console messages will look like this:
![image](https://user-images.githubusercontent.com/1289437/97191437-41f72980-177d-11eb-8287-afb115403d8e.png)

**Comment by elsylambert** [comment]
When the next button is clicked the first time, the Target side text is messed up. As soon as you reach chapter 2, the app crashes.
![Screen Shot 2020-10-26 at 11.25.09 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/78ef43e1-a619-4707-8962-4e1b03288107)

**Comment by cckozie** [comment]
Test in Katalon tCC Test App Crashes

**Comment by RoyalSix** [comment]
https://github.com/unfoldingWord/tc-create-app/pull/461

**Comment by RoyalSix** [comment]
Confirmed issues fixed [here](https://5fa0967635343500ec6e7a78--tc-create-app.netlify.app/):
 - `Crash on pagination (on develop branch, not master)`
 - `When the next button is clicked the first time, the Target side text is messed up. As soon as you reach chapter 2, the app crashes.`

**Comment by ancientTexts-net** [comment]
Testable in `v1.0.5-rc.7`

https://deploy-preview-488--tc-create-app.netlify.app/

@elsylambert 
@cckozie 

@BincyJ 
@birchamp

**Comment by elsylambert** [comment]
Not seeing Crash on Pagination in Preview https://deploy-preview-488--tc-create-app.netlify.app/

**Comment by ancientTexts-net** [comment]
Testable in `develop`, v `1.0.5-rc.7`

https://develop--tc-create-app.netlify.app/

@elsylambert 
@cckozie 

@birchamp 
@BincyJ

**Comment by cckozie** [comment]
Looks good in v1.0.5-rc.7

**Comment by elsylambert** [comment]
Not seeing the issue in translationCore Create - v1.0.5-rc.7.
