### ISSUE TITLE
A single click highlights an original language word when it is directly adjacent to a highlighted word

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/tc-create-app#469]
v1.0.5-rc.6
Movie at [https://app.zenhub.com/files/191973535/a854ebfa-5912-4066-ab09-971d71dce3b9/download](https://app.zenhub.com/files/191973535/a854ebfa-5912-4066-ab09-971d71dce3b9/download)
1. Open a tN project
2. Scroll to a check that has an original language word highlighted
3. Single click on a word adjacent to the highlighted word
4. Note that the clicked on word is now also highlighted
5. Single click on the word in step 3
6. Note that the highlight on that word is removed

**Comment by birchamp** [comment]
@RoyalSix Do we want to allow users to click to highlight words and update the original language field?

**Comment by birchamp** [comment]
@mandolyte this is specific to 'kai' this doesn't happen with other words.  Doesn't even have to be adjacent. Just Kai'

**Comment by mandolyte** [comment]
Do you know of other words that like κατ᾽ that end with an apostrophe?

**Comment by mandolyte** [comment]
Note1: other cases can be found by:
```sh
$ grep \’\| *.usfm
```

Thus in Rev 1:12, which has this:
```
1:12 καὶ ἐπέστρεψα βλέπειν τὴν φωνὴν ἥτις ἐλάλει μετ’ ἐμοῦ. καὶ ἐπιστρέψας, εἶδον ἑπτὰ λυχνίας χρυσᾶς,
```

The word μετ’ has the same behavior.

@birchamp FYI

**Comment by ancientTexts-net** [comment]
saving these changes for posterity in case we need to re-activate onClick one day?

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/7c406675-cc9a-4e99-967c-daa3585109fc)

**Comment by cckozie** [comment]
Not seeing the problem in v1.2.0-rc.2 build 28-4717783
I'll add a test for it in tCC tN Test OrigLangQuote

**Comment by elsylambert** [comment]
translationCore Create - v1.2.0-rc.2 build 28-4717783. Not seeing this issue. Single click is not activated and hence, not highlighting a word in the scripture viewer.
