### ISSUE TITLE
Cannot read property 'split' of undefined     at a.filterLogic

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/tc-create-app#497]
This is a random bug that is happening in tc-create-app when scrolling down the page. Not sure what is causing it, but its making the app crash so patching it.

**Comment by RoyalSix** [comment]
<img width="1792" alt="Screen Shot 2020-11-04 at 10 15 02 AM" src="https://user-images.githubusercontent.com/16184018/98152481-a48bac00-1e86-11eb-988c-728f5cfb2bcd.png">

**Comment by ancientTexts-net** [comment]
can we please get together regarding this unit test?

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/2ea5e320-a8c1-4c77-a4ba-4742c3524abb)

i cannot get it to work for some reason

**Comment by ancientTexts-net** [comment]
![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/3b3f7151-384c-44f3-a9c5-e4bf31820290)

**Comment by birchamp** [comment]
@ancientTexts-net possible line ending issue between Linux and Windows

**Comment by cckozie** [comment]
v1.1.0-rc.4 build 19-6e50a4c
I have not seen, and am not seeing, any app crashes when scrolling so I'm not really able to verify the "fix".

**Comment by elsylambert** [comment]
v1.1.0-rc.4 build 19-6e50a4c.

Not seeing the reported issue while scrolling down the page.
