### ISSUE TITLE
tN now opens with Rows per Page set to 10 when it used to be 25

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/tc-create-app#498]
v1.0.5-rc.7
Open any tN project and note the Rows per Page
Probably not a big deal for most users, but does break automation scripts

**Comment by cckozie** [comment]
I added a test for this (as well as tests for all rows/page options) to tCC tN Test Columns Options and renamed it to tCC tN Test Columns and Page Rows.

**Comment by cckozie** [comment]
tN opens with 25 rows in v1.2.0-rc.2 build 28-4717783

**Comment by elsylambert** [comment]
translationCore Create - v1.2.0-rc.2 build 28-4717783. By default. the page opens with 25 Rows per page. The other options 10, 50, 100 are working fine too.
