### ISSUE TITLE
Content Validation: on-open

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/tc-create-app#500]
This issue covers invocation of Content Validation when a file is opened and when a file is saved.

**Comment by mandolyte** [comment]
@BincyJ @birchamp Since we know now that users are creating content manually, the highest priority has shifted to validating content when a file is initially opened. This will ensure that any critical formatting errors do not crash tc-create. 

Here is my understanding of the requirements for CV-on-open:

### Only critical errors should be processed

This has the advantage of minimizing the slow down that a full CV would incur. It is not known whether the CV package allows the checks to be limited to critical errors. So this may result in an enhancement request for the CV package. This needs to be determined.

If there are no critical errors, then proceed as normal and open the file.

### On critical errors

If there are critical errors, then it is important to warn the user. After the warning, there are some alternatives:

- the user may choose to proceed, possibly crashing the app or 
- risk fixing the data using tc-create or
- do not allow the user to proceed, but require them first fix the critical errors outside of tc-create

### UI/X Questions, Observations, Decisions

**Alert Box**
In other parts of tc-create, warnings are shown, but they do not allow the user to proceed. In these cases, a simple alert box is shown with some details. When the user clicks OK, then alert goes away and the step is not advanced. An alert box may not be a suitable UI for what could be a long list of errors (unless we only show the first one or two).

**Dialog Box**
While a dialog box has the advantage of being able show more, it still has the problem with being modal. Errors in data need to be "out of band", that is, kept separate so the user can see the error and the data _simultaneously_ in order to correct the data. Perhaps even copy/pasting a suggested fix from the error list to the document. See also note 1.

The alert box would be the simplest to implement, but has inherent limitations. A dialog could show more and could include a way to export/download the data to a CSV, allowing the user to view it in a different window while they continue editing.



Note 1: For completeness, there may be a way to make a dialog non-modal. See [here](https://stackoverflow.com/questions/55733179/how-to-create-a-non-modal-dialog-in-material-ui).

**Comment by birchamp** [comment]
@mandolyte @BincyJ - 

Here's what I propose:
"There are critical errors in this file. Continuing to open this file may result in a blank screen or severe error, but no data will be lost. Are you sure that you want to continue?"   Then we give them two options:
* View errors 
* Continue to open file

"View errors" takes them a new tab with the validation results.

**Comment by mandolyte** [comment]
@BincyJ @birchamp A summary and a finding...

Based on conclusions in this issue:

- We will go with a model dialog box
- The box will show high priority errors
  - include the message and other info needed to understand the error
  - the "line" number with link to open DCS to location
- Provide two buttons:
  - Close which will not advance the stepper
  - Continue which will advance the stepper

One goal for new content is to avoid creating the branch with default (bad) content. Otherwise, the branch will need to be removed before continuing to work on the file after the source is corrected.

**Finding:** tc-create hands the source content over to the Gitea React Toolkit, along with the branch, filename/path, etc. When it returns, the branch is created and populated if it didn't exist. Thus tc-create does not have any direct control and cannot interrupt the sequence of actions. To make this work would require changes to GRT to take a "callback" function to invoke before creating the branch. Alternatively, the existence checking could be pulled in tc-create itself (this may actually be simpler, altho to the purist, it may be polluting the tc-create code base). In theory, this could be said to be addressing an issue which shouldn't happen in normal practice and thus our code should not try to address such corner cases.

At present, I'll just check the target content. If it is deemed important to solve, I'll take a second pass and enhance it avoid branch creation when source has bad content.

**Comment by ancientTexts-net** [comment]
Reviewed with Cecil:

2 issues:

- TSV is not opening after validation (spinner)
- LICENSE.md is being validated in `en_tn` (should not be)

- no errors logged to console

**Comment by cckozie** [comment]
@mandolyte - Can you add some of the problems that are considered "critical errors" so I have a better idea of how to test this?

**Comment by elsylambert** [comment]
"LICENSE.md is being validated in en_tn (should not be)"
It does validate License.md and Readme.md in v1.1.0 rc3 @mandolyte

**Comment by mandolyte** [comment]
> @mandolyte - Can you add some of the problems that are considered "critical errors" so I have a better idea of how to test this?

I answered this, but probably in another issue? At any rate, if you don't see let me know. I'll hunt it down and put here as well.

**Comment by cckozie** [comment]
v1.1.0-rc.3
@birchamp - Are these good enough?

This is the error displayed when the header is missing:
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/88a0bd0d-579d-4985-a674-bc3d3bec3ce1)

This is the error displayed when there is a tab missing in one of the rows:
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/7b47e612-501b-4962-ba72-c5e39eb0a771)

**Comment by birchamp** [comment]
@mandolyte are these coming from the CV app or are they internal to TCC?

**Comment by cckozie** [comment]
v1.1.0-rc.3
Today I encountered the app hanging while running this validator.
I used an open session for a tN project that I had started last night
I opened the drawer and selected a Luke tN project, enabled the ID and OrigQuote columns, and then searched for an ID
I opened the drawer and selected a Romans project, then clicked on the main screen
The on-open validator started and then hung
Is this possibly a lost token issue?
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/f618ad58-c86c-4777-b91c-729c7822e4e3)

**Comment by birchamp** [comment]
@mandolyte materialUI alert. Indicate something bad happened and then a button to close the file. Use https://material-ui.com/components/alert/.  We will need to give the user a link to where they can edit the file.

**Comment by birchamp** [comment]
@cckozie So this is a QA fail since new code needs to be written for these notices, correct?

**Comment by elsylambert** [comment]
@birchamp Yes, this needs to be moved out of IN QA

**Comment by birchamp** [comment]
@mandolyte @cckozie - The error should say:

This file cannot be opened by tC Create. Please contact your administrator to address the following error(s).

**Comment by birchamp** [comment]
Added stakeholder requested feature to have a button to copy the error text #658

**Comment by cckozie** [comment]
@birchamp 
This now functions properly and the text is as requested. Instead of a "button to close the file", there is an "X". Is that good enough?
![image](https://user-images.githubusercontent.com/8171759/106051231-cd01fb80-60ad-11eb-9950-5d31531eabe0.png)

**Comment by cckozie** [comment]
Tested in tCC tN Test On-Open Validator

**Comment by birchamp** [comment]
@mandolyte @cckozie - 

- The x needs to be bigger if it's not too much effort.  Or you could make it bigger by making it bold: **Close   X**
- The box should be either:
  - modal
  - closed by any action outside of the box (clicking the menu, or the close file button).

**Comment by birchamp** [comment]
@mandolyte what is the effort needed of getting rid of the error box popping up for a new file or at least change the text in the box to say "Processing..."?

**Comment by mandolyte** [comment]
Swapped out the material ui "Alert" component for the "Dialog" (modal) component. Same one as used for the validating process message. Behaves the same but you must click the Close button to continue. The click action clears the error messages and so the dialog no longer appears between file choices. Here is how it looks:

![image](https://user-images.githubusercontent.com/1289437/106635604-0ecbef80-654f-11eb-88c4-3c2f8bc3f5bc.png)

**Comment by ancientTexts-net** [comment]
Should be available in v1.1.0-rc.6 build 21-ad9123a
https://develop--tc-create-app.netlify.app/

@elsylambert , @cckozie 

Thank you :)

**Comment by elsylambert** [comment]
translationCore Create - v1.1.0-rc.6 build 21-ad9123a. On-open Content Validation is working fine : displays the error message as expected.![Screen Shot 2021-02-08 at 11.12.02 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/6d62aa49-52f4-4405-8736-56d5a815123a)
