### ISSUE TITLE
Some of the formatting is different in target than in the source in tA projects

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/tc-create-app#505]
v1.0.5-rc.7
Is this because the source has changed since it was copied to the target?
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/0ec40a88-76f2-439b-973e-23352e571782)

**Comment by birchamp** [comment]
@cckozie can you fix the link above? Are you seeing this after you delete your branch?

**Comment by cckozie** [comment]
@birchamp The link is fixed, but so far we have been unable to recreate the repo after I deleted it.

**Comment by elsylambert** [comment]
@birchamp  I see this behaviour in Org- translate-test but not on the Organization - unfoldingword.

**Comment by cckozie** [comment]
The formatting was correct after deleting and recreating the repo. Closing this issue.
