### ISSUE TITLE
Unable to add new lines and duplicated blocks at the bottom of tA blocks

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/tc-create-app#507]
translationCore Create - v1.0.5-rc.7
This happens both in preview and non-preview mode
Movie at [https://app.zenhub.com/files/191973535/8484057a-2b35-4e45-80be-e9e1e869e7c1/download](https://app.zenhub.com/files/191973535/8484057a-2b35-4e45-80be-e9e1e869e7c1/download)
1. Open a tA project
2. Open one of the blocks
3. Position the cursor at the bottom of the block
4. Press the Enter/Return key
5. Note that the new line is temporarily added, then deleted with the cursor returning to the end of the previous last line

**Comment by ancientTexts-net** [comment]
here's the behavior I see:

C:\Users\ZPennington\AppData\Local\Temp\557e1d2d-88d0-4eeb-9cc2-72539bcd6171.gif

@RoyalSix  maybe unblocking tomorrow ?

**Comment by ancientTexts-net** [comment]
I narrowed this down to `markdown-translatable` 1.2.5

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/2ddd288a-967f-440a-b627-1a95acd550ec)

**Comment by ancientTexts-net** [comment]
deploy preview is here:

https://deploy-preview-509--tc-create-app.netlify.app/

**Comment by elsylambert** [comment]
https://deploy-preview-509--tc-create-app.netlify.app/ Verified in the link- Able to add new lines at the bottom of Blocks.

There is an issue - Autofill /duplicated blocks when we type at the end of a block. This does not happen with every block. After some investigation, found that if there is a text which does not start with a md character (# or >) the blocks gets duplicated and autofilled.

**Comment by ancientTexts-net** [comment]
Testable in `v1.0.5-rc.10`
https://develop--tc-create-app.netlify.app/

**Comment by ancientTexts-net** [comment]
Testable in translationCore Create - `v1.0.5-rc.10`
https://develop--tc-create-app.netlify.app/


@elsylambert  @cckozie

**Comment by elsylambert** [comment]
translationCore Create - v1.0.5-rc.10. Not seeing the issue in tA blocks. Able to add new lines at the end of a block and not seeing duplicated blocks.

**Comment by cckozie** [comment]
Looks good in v1.0.5-rc.10
