### ISSUE TITLE
Text Editor becomes unresponsive when field is cleared completely using delete/backspace key

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#508]
- Open a tA article and click on an edit block to start editing.
- Using the keyboard -delete or backspace keys, clear the text in the editor box.
- Note that when you completely clear the text, the # shows up. Clear #  and then the text from the next block gets rendered into the cleared edit box, which cannot be cleared then. The app becomes unresponsive.
.![Screen Shot 2020-11-09 at 10.13.27 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/74b2dbc7-2ee5-4822-b7c1-e545746336e7)

**DoD:** The app still responds per normal use when clearing a field completely

**Comment by elsylambert** [comment]
Found this issue by Katalon script- undo text in editor

**Comment by elsylambert** [comment]
When the text block is cleared completely, the next block is moved up and for the whole article , one block moves up to the top.

**Comment by birchamp** [comment]
So I don't mind the text getting out of sync with the blocks **as long as** the user can get them back in sync. We need to allow translators to delete a block to move the text up if the text is out of line to begin with.  @Elsy says that the app becomes unresponsive. That *is* a real problem. @cckozie Are you seeing it become unresponsive in production?

**Comment by elsylambert** [comment]
@birch The original issue which I labelled as QA fail is a problem. When the text is cleared completely from the Header Block it displays # in non-preview mode and when you try to clear that #, it copies the text from the next block. At this point the app becomes unresponsive. This is not happening in Production.

**Comment by cckozie** [comment]
@birchamp - Yes, as Elsy stated, I am not seeing it become unresponsive in Production.

**Comment by elsylambert** [comment]
In the Preview- https://deploy-preview-509--tc-create-app.netlify.app/ Not seeing the # but Save is not working. Save button does not get enabled when the changes are made to the file.

**Comment by ancientTexts-net** [comment]
Testable in translationCore Create - `v1.0.5-rc.10`
https://develop--tc-create-app.netlify.app/


@elsylambert  @cckozie

**Comment by elsylambert** [comment]
translationCore Create - v1.0.5-rc.10. Not seeing the App becoming unresponsive when the field is cleared completely.

**Comment by cckozie** [comment]
v1.0.5-rc.10
I'm not seeing the app becoming unresponsive or significant differences in the way deleting text is working as compared to Production, but do see another anomaly where a > is left in a field where the text was deleted by highlighting and clicking Delete.
[https://app.zenhub.com/files/191973535/0b422bca-b727-4e34-badd-394ec9ddb2e6/download](https://app.zenhub.com/files/191973535/0b422bca-b727-4e34-badd-394ec9ddb2e6/download)
