### ISSUE TITLE
Clearing a header adds a hashtag to the field

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#513]
Clearing a header completely inserts a hashtag to the text field.

**Comment by elsylambert** [comment]
In Production- # appears when you clear the text box by first selecting the whole text using a mouse and then hitting delete>on blur.
App is responsive.

In Develop rc 7- # appears after you clear the text box using keyboard key- delete(Mac)/backspace

**Comment by birchamp** [comment]
Need to evaluate if this is necessary in order to align sections.

**Comment by elsylambert** [comment]
Not seeing this issue in Production translationCore Create - v1.1.0 build 23-603db56
and in Develop  v1.1.1-rc.3 build 44-bde198f
