### ISSUE TITLE
Highlights are lost when Occurrence number is changed back from 0 to 1

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#521]
Highlights are lost when occurrence number is changed back from 0 to 1 or changed by removing the Occurrence Number and adding back.

**Comment by elsylambert** [comment]
- Open tN and go to a note that has a highlight.
- Change the Occurrence number from 1 to 0. Highlight is removed as expected.
- Change the Occurrence number back to 1. Note that OriginalQuote cannot be highlighted.

**Comment by birchamp** [comment]
I'm no longer seeing this @elsylambert. I'm adding a re-test tag.
