### ISSUE TITLE
Incorrect line breaks in raw mode

### ISSUE THREAD

**Issue by lrsallee** [unfoldingWord/tc-create-app#53]
Duplicate of #48

upLooking at TA/translate/figs-metaphor/01.md

In preview mode, breaks are OK now. However, in raw mode they still seems to occur in text that has underlining. See the Bible quotes in the section `Examples from the Bible`

> Listen to this word, 
you cows of Bashan
, (Amos 4:1 ULT)

**Comment by birchamp** [comment]
This is a duplicate of #35

**Comment by klappy** [comment]
Duplicate issue was addressed and closed.
