### ISSUE TITLE
Strange symbol in Hebrew text in Ruth 1:8

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/tc-create-app#532]
Seen in both production and v1.0.5-rc.7
Seen in both Chrome and Firefox
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/3f7bc2a8-2fce-47bf-b0b8-f2cd1d9007e5)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/c4ce2686-aa8d-443c-a0ca-30383abb78ec)

**Comment by mandolyte** [comment]
What symbol are you referring to? I don't know Hebrew, so the only thing that stands out to me is the footnote symbol

**Comment by cckozie** [comment]
Yes, it is the symbol for footnotes. Hadn't seen this before, and it's different than in our other apps, so wrote it up.
Closing this issue.
