### ISSUE TITLE
Edits are lost when  typed in after a header is cleared completely using  delete/backspace button

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#545]
- Clear the text using delete/backspace button.
- type -in new edits.
Case 1:
- Tab out/on blur edits are lost and blocks moved up.
Case 2:
- Click on save after step2. edits are lost and blocks moved up.

This is taken out from #508.

**Comment by birchamp** [comment]
@elsylambert can you retest this? I suspect it's still an issue

**Comment by elsylambert** [comment]
Not an issue in translationCore Create - v1.2.0-rc.2 build 28-4717783.
