### ISSUE TITLE
Add error message when add resource has a bad url. 

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#548]
There is no indication to the user when add resource encounters a bad url or invalid repository.

Notifications of errors should be added to the text field similar to:
![image.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/d5d03e26-5aba-4d1a-8335-66cf2aba1c9f)
See this issue https://github.com/unfoldingWord/create-app/issues/34

Catch-all error message:  "Error: Could not add the resource. Please check the URL."

**DoD**: The user is notified when they attempt to open a bad path or invalid repo for a scripture resource.

===========================
 in v1.0.5-rc.10
1. If the pasted path doesn't exist or is not a valid repo, there is no indication to the user that something is wrong. Nothing happens when the add icon is clicked and there is no explanation of why.

Add a notification to let the user know that the path didn't resolve satisfactorily:
"A valid resource cannot be found at <resource_path>. Please check the address and try again."

**Comment by birchamp** [comment]
@birchamp make a link to mclean's issue.

**Comment by ancientTexts-net** [comment]
@mandolyte 
@PhotoNomad0 

ready for testing:

http://localhost:6060/#/Parallel%20Scripture%20?id=parallelscripture

- open `ParallelScripture` demo
- click "Manage Versions" button; add an INVALID resource (e.g., "www.google.com")
Verify: red error message shows
- next, add VALID resource (e.g., `Door43-Catalog/hi/ulb/master/3jn`)
Verify: red error message disappears; & new resource shows

**Comment by cckozie** [comment]
@birchamp - It is unclear to me whether or not this verbiage in the first comment was part of the DOD:
'Add a notification to let the user know that the path didn't resolve satisfactorily:
"A valid resource cannot be found at <resource_path>. Please check the address and try again."'

This is what it displayed when the user tries to add a resource with a bad URL or one not pointing to a uW resource. 
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/34b85a24-c9e0-4fbb-b58b-7e515fd8295b)

**Comment by birchamp** [comment]
@ancientTexts-net Since this is a catch-all phrase, let's make the message say: "Error: Could not add the resource. Please check the URL."

**Comment by birchamp** [comment]
@cckozie I've updated it. ...at least we're using "resource".

**Comment by elsylambert** [comment]
Looks good in translationCore Create - v1.2.0-rc.3 build 28-c60492b.
