### ISSUE TITLE
Inconsistent user experience when using the on demand validator

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/tc-create-app#559]
When a tN project is first loaded and the Validate icon is clicked, there is no indication that the validator is running and the user is free to perform other actions in the project.
When the Validate icon is clicked a second (or successive) time in the same project, the icon stays highlighted and the tooltip remains displayed and the user is prevented from performing any other actions until the download is complete.
When the validation is run against Matthew on my fastest Mac, it runs for about 50 seconds. During that time my browser issues the Page Unresponsive message.

**Comment by cckozie** [comment]
Looks good in v1.1.0-rc.3

**Comment by elsylambert** [comment]
Looks good in translationCore Create - v1.1.0-rc.3.
