### ISSUE TITLE
Validator seems to find the same errors after they've been fixed

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/tc-create-app#566]
Use this project: https://qa.door43.org/translate_test/en_tn/src/branch/tc01-tc-create-1/en_tn_57-TIT.tsv
Movie here: https://drive.google.com/file/d/1NCBbNvj88y1aLpiHa-qXDxB14hmWGMiE/view?usp=sharing
Validation files here: [https://app.zenhub.com/files/191973535/80b16f36-67ee-4195-875e-7b91aad540b8/download](https://app.zenhub.com/files/191973535/80b16f36-67ee-4195-875e-7b91aad540b8/download)
To replicate:
1. Load the project in tN
2. Click the Validate button
3. Wait for file download
4. Click the Prevew button
5. Delete the extra space after the 1., 2., and 3. in the first occurrence note
6. Click the Preview button
7. Click the Columns button
8. Check the OrigQuote  checkbox
9. Navigate down to the row where the original quote is ​'κατὰ πίστιν abc abc'
10. Delete the ' abc abc'
11. Click out of the field
12. Note that ​κατὰ πίστιν is now highlighted in the Greek
13. Click the Validate button
14. Note that the same errors are displayed in both downloaded validation files

**Comment by mandolyte** [comment]
Here are my notes from this morning. This file is causing quite unbelievable problems. But I cannot reproduce them from scratch.

1. delete my branch at qa.door43.org/translate_test/en_tn/branches 
	cecil.new-tc-create-1
2. login with tc-create-app (local host)
3. org=translate_test
4. resource=tranlation notes
5. language=English
6. file=book of titus

Results:
- first, my session is paused on debugger with an uncaught exception
in 'helpers.js', called from TranslatableTSV.js and useFile.js. Message is:
"TypeError: Cannot read property 'content' of null"
- if I click to let it go on, it seems to act OK.
- if now run validation, no errors are found.
- at this point, my branch is re-created and contains Titus.
- refresh page to return to login page... do not log in yet.
- now in DCS, go to my branch and select Titus in DCS
- click the edit file button
- select all the text and delete it
- paste in text from @koz
- commit directly into my branch
- now login with tc-create and return to this file with the new content
- run validation and I get all the errors that @koz introduced:
```
Priority	Chapter	Verse	Line	Row ID	Details	Char Pos	Excerpt	Message	Location
889	front	intro	2	m2jl	SupportReference		​	Unable to find SupportReference TA link	 translate/​/01.md
851	front	intro	2	m2jl	OrigQuote		undefined	Unable to load original language verse text	
550	front	intro	2	m2jl			undefined	Invalid zero occurrence field when we have an original quote	
194	front	intro	2	m2jl	OccurrenceNote	110	…br>1.␣␣Pau…	Unexpected double spaces	
916	1	1	4	rtc9	OrigQuote			Unable to find original language quote in verse text	
916	1	1	5	xyz8	OrigQuote		εὐσέβειαν​	Unable to find original language quote in verse text	
```
- Now try to correct them
- Cannot find first error at all -- where is it???
- Fixed all the rest of them and for the last one just re-pasted into Origquote field (does not appear to be a valid error).
- click save
- now run validation
- it reports all the same errors, even tho the data has changed.
- close the file and return back to the file
- run validation
- it still reports the same errors (where is it getting the data from!?)
- refresh page to return to login page
- return to the file and run validation again
- it still reports the same errors!?
- delete all databases in indexedDB
- refresh page to return to login page
- return to the file and run validation again
- it still reports the same errors!
- delete all databases, close tab of locally running tc-create, restart with yarn start
- it still reports the same errors
- delete databases, close browser and return to page
- it still reports the same errors

**Comment by cckozie** [comment]
It appears that the problem is caused by something in line 4 (ID = rtc9). I replaced that line with line 4 from the master in qa, then added the " abc abc" extra text to the original quote string as it was in the failing file. Now when the validator is run after fixing that original quote, that problem no longer reported by the validator.

**Comment by cckozie** [comment]
There is another example of this problem in issue #582.

**Comment by cckozie** [comment]
No longer seeing this problem in v1.1.0-rc.1

**Comment by elsylambert** [comment]
Not seeing this issue in translationCore Create - v1.1.0-rc.1.
