### ISSUE TITLE
Hackathon: Update RCLs for Server Side Next.js

### ISSUE THREAD

**Issue by ancientTexts-net** [unfoldingWord/tc-create-app#577]
Hackathon: Update RCLs for Server Side Next.js

**Comment by birchamp** [comment]
@ancientTexts-net add thorough documentation on this with diffs

**Comment by ancientTexts-net** [comment]
gitea-react-toolkit:

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/683ae1f0-64cc-4f22-9d09-6f31d7bb3c88)

**Comment by ancientTexts-net** [comment]
scripture-resources-rcl

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/a81bceae-2892-4920-98ac-ff35871e3043)

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/1567c36a-7a3f-40f5-b793-5c6ef398c8b7)

**Comment by ancientTexts-net** [comment]
datatable-translatable

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/73b62a32-4814-47e0-a953-dd86a7f8961a)

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/ef4f9b33-3965-4378-8463-6b93e6ed5b9a)

**Comment by birchamp** [comment]
@ancientTexts-net have someone review this with you.
