### ISSUE TITLE
Add a unique identifier to tC Create develop builds

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/tc-create-app#586]
As a QA tester I would like develop builds to always have a unique identifier so that I can have greater confidence about when the app has changed.
Currently adding any identifier (e.g. rc number) is done manually so it is possible for new builds to get created and QA not having any way to distinguish that. It would be very helpful to QA if we were always assured of knowing when the develop build is different than what it last was. This is especially important when attempting to determine why we are no longer able to replicate an issue using the same data and apparently the same build of the app. This was the case when attempting to replicate the problem in #575.
Any sort of unique identifier would work for us. Using a timestamp may be helpful for other purposes as well.

Ideally, this would update the RC number. 
UID should show up in the application bar not in the drawer - can be in a reduced font size.

**Comment by RoyalSix** [comment]
@cckozie @elsylambert 
https://5fea650543bf880007015349--tc-create-app.netlify.app/

If you check the side drawer there is now an entry with the unique build number

**Comment by RoyalSix** [comment]
@unfoldingWord/devs I would like to get your opinion on this implementation

**Comment by elsylambert** [comment]
@RoyalSix "Developer makes a change" meaning the new develop build or when the changes are done in one of the RCLs? Does the number change without having to change the rc-build?

**Comment by PhotoNomad0** [comment]
It looks good to me.  Was hard to get my head around at first.  Good work!

**Comment by RoyalSix** [comment]
@elsylambert "Developer makes a change" means anytime new code is committed to github. So it will increment regardless of the type of build. 

But this system is built in a way that if the developers need to reset the number it's very easy to do so by just changing the number to 0 and committing the change to github.

**Comment by birchamp** [comment]
@mandolyte take another look at this to see if we can update the RC number directly.

**Comment by ancientTexts-net** [comment]
Running PR 73 locally gets this error:

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/2f4de4b1-e30f-4a1d-b05c-d201bb3927c9)

**Comment by cckozie** [comment]
Now seeing translationCore Create - v1.1.0-rc.4 build 18-e095e04.

**Comment by elsylambert** [comment]
translationCore Create - v1.1.0-rc.4 build 19-6e50a4c seeing that the build number changes with code change as expected.
