### ISSUE TITLE
The validator incorrectly reports unexpected trailing space(s)

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/tc-create-app#588]
v1.1.0 (develop)
project is at: https://qa.door43.org/translate_test/en_tn/src/branch/tc01-tc-create-1/en_tn_56-2TI.tsv
text file at: [https://app.zenhub.com/files/191973535/e0142393-0d25-4e5b-9078-f2faaf7461f0/download](https://app.zenhub.com/files/191973535/e0142393-0d25-4e5b-9078-f2faaf7461f0/download)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/ac0807ff-c1cd-4f56-a13e-6d26355e7064)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/c97e26ea-505e-4747-b18a-dd38c0b5d10e)

**Comment by RobH123** [comment]
I can see the trailing space in the source file @cckozie : https://qa.door43.org/translate_test/en_tn/blame/branch/tc01-tc-create-1/en_tn_56-2TI.tsv#L35

**Comment by cckozie** [comment]
@RobH123 - Yeah, I'm seeing it there now too. Not sure what's going on here unless it was caused by updating qa from production or misfiring of my tired brain synapses. I'll look into it further.
