### ISSUE TITLE
ResourceLinks Escaped Incorrectly

### ISSUE THREAD

**Issue by ancientTexts-net** [unfoldingWord/tc-create-app#596]
Editing _OccurrenceNote_ in preview (html) mode causes RC links to be escaped incorrectly.

Occurs in PROD (1.0.5)

1. open TN
2. edit OccurrenceNote in preview mode. (Edit anything in the block)
3. click outside of the field (necessary in 1.0.5)
4. toggle preview off
5. NOTE: the rc link syntax is bad now

e.g., 
`“I, John the elder, am writing” (See: [[rc://en/ta/man/translate/figs-explicit]])`

is incorrectly escaped as:
`“I, John the elder, am writing” (See: \[\[rc://\*/ta/man/translate/figs-explicit\]\])`

**Comment by mandolyte** [comment]
This issue reminds of a thought I've had several times over the past few months. Why do we permit editing in both Markdown and HTML? Issues like this on show that bi-directional translations are not lossless... which means we will always be fighting battles like this.

Github, Zulip, etc. only allow you to view the HTML (see preview button on this very input box!). 

If that is the best practice, shouldn't we follow?

@ancientTexts-net @birchamp

**Comment by elsylambert** [comment]
Not seeing this issue in translationCore Create - v1.1.0-rc.3. Able to edit Occurrence Notes without mangling the RC link.
