### ISSUE TITLE
Unable to save after fixing the double spaces in tN

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#597]
translationCore Create - v1.1.0-rc.1
Ran the Validator in 2Jn.
- Got the error message that the text has double spaces.
- Removed the double spaces in Preview mode.
- Save button is not enabled on Blur and hence not able to save.

**Comment by elsylambert** [comment]
Not seeing this issue in v1.1.0-rc.3. Able to remove double spaces and save the changes.

**Comment by cckozie** [comment]
v1.1.0-rc.3
Save is not enabled until on blur, but am not able to save.

**Comment by elsylambert** [comment]
This issue has resurfaced in translationCore Create - v1.1.0-rc.4 build 18-e095e04.  Save is not enabled(Neither on Edit nor On Blur) when double space is removed in Preview mode, hence not able to save.

**Comment by ancientTexts-net** [comment]
Should be available in v1.1.0-rc.6 build 21-ad9123a
https://develop--tc-create-app.netlify.app/

@elsylambert , @cckozie 

Thank you :)

**Comment by cckozie** [comment]
Still unable to save in v1.1.0-rc.6 build 21-ad9123a
https://images.zenhubusercontent.com/191973535/8bfc2e56-2e72-4816-a6ee-ee16624de725/597.mp4

**Comment by ancientTexts-net** [comment]
Should be testable in `translationCore Create - v1.1.0-rc.7 build 22-ebe4a7c`
https://develop--tc-create-app.netlify.app/

**Comment by ancientTexts-net** [comment]
Should be testable in `translationCore Create - v1.1.0-rc.7 build 22-ebe4a7c`
https://develop--tc-create-app.netlify.app/

@cckozie @elsylambert @mandolyte

**Comment by cckozie** [comment]
Looks good in v1.1.0-rc.7 build 22-ebe4a7c
When in markdown mode the Save button is immediately enabled after removing the extra space.
When in preview mode, the Save button is enabled after the on-blur event after removing the extra space.

**Comment by elsylambert** [comment]
Looks good in translationCore Create - v1.1.0-rc.7 build 22-ebe4a7c. Able to save after removing the double spaces..
