### ISSUE TITLE
Requirement: Test server/git for testing develop branch

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#60]
Test server/git for testing develop branch- Currently we are using Production Server for testing.

**Comment by jag3773** [comment]
Setting this to bg.door43.org should work for now. We'll have a develop.door43.org soon which will get auto updates from production periodically.

**Comment by birchamp** [comment]
use environment variables for switching servers on netlify. 

DoD: Able to change which server we're using based on the environment vars.

**Comment by elsylambert** [comment]
Beta-14 Develop build is working on bg server currently. This feature would allow develop build to point to test server i.e bg server and the production build to work on the Production sever i.e git.door43.
As a user on the develop branch, I cant switch the servers to see this working. Can please @klappy or @RoyalSix confirm if this works fine as stated above? if so, I would label it as testedElsewhere and QA Complete it.

**Comment by klappy** [comment]
We can test this once we deploy this issue to Production. So we may have to break a rule of deploying to production prior to this fully being tested :)
