### ISSUE TITLE
Validator reports "Unable to find original language quote in verse text" even though the OrigQuote exactly matches the Hebrew snippet

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/tc-create-app#600]
v1.1.0-rc.1
Project is at: https://qa.door43.org/translate_test/en_tn/src/branch/tcc001-tc-create-1/en_tn_15-EZR.tsv
TSV file at: [https://app.zenhub.com/files/191973535/650ea9ae-0b5b-4140-8234-9c93b3c8ceaf/download](https://app.zenhub.com/files/191973535/650ea9ae-0b5b-4140-8234-9c93b3c8ceaf/download)
Validation file at: [https://app.zenhub.com/files/191973535/3395197f-45ae-4a71-8d2e-71d62cc9cf67/download](https://app.zenhub.com/files/191973535/3395197f-45ae-4a71-8d2e-71d62cc9cf67/download)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/a3a89511-5b9a-4a58-b34a-6e0c7f287a3c)

OrigQuote: 
\u05d5\u05bc\u2060\u05d1\u05b4\u2060\u05e9\u05c1\u05b0\u05e0\u05b7\u05a3\u05ea \u05d0\u05b7\u05d7\u05b7\u0597\u05ea \u05dc\u05b0\u2060\u05db\u05a8\u05d5\u05b9\u05e8\u05b6\u05e9\u05c1\u0599 \u05de\u05b6\u05a3\u05dc\u05b6\u05da\u05b0 \u05e4\u05bc\u05b8\u05e8\u05b7\u0594\u05e1

Snippet: 
\u05d5\u05bc\u2060\u05d1\u05b4\u2060\u05e9\u05c1\u05b0\u05e0\u05b7\u05a3\u05ea \u05d0\u05b7\u05d7\u05b7\u0597\u05ea \u05dc\u05b0\u2060\u05db\u05a8\u05d5\u05b9\u05e8\u05b6\u05e9\u05c1\u0599 \u05de\u05b6\u05a3\u05dc\u05b6\u05da\u05b0 \u05e4\u05bc\u05b8\u05e8\u05b7\u0594\u05e1

**Comment by birchamp** [comment]
@cckozie  is this a dup with #572 but a different text?

**Comment by cckozie** [comment]
@birchamp - I really don't know what is causing the error(s), so I am not sure if it is the same problem. They seemed enough different to me to create separate issues, but I have no objection to combining them if that is preferred.

**Comment by birchamp** [comment]
@RobH123 can you take a look at this?

**Comment by RobH123** [comment]
Those two long hex strings are identical, so it obviously shouldn't produce an error for that. So something else must be going wrong.

Since it's from last year, I wonder if it could be retested @cckozie? Perhaps something has already been fixed somewhere? Ah, but I wonder about the leading space warning just above the highlighted one. Since the quote is from the very beginning of the book/verse, there's no leading space in the original @birchamp also.

**Comment by cckozie** [comment]
@RobH123 @birchamp - I'll retest

**Comment by cckozie** [comment]
@RobH123 @birchamp - In v1.2.0-rc.2 build 28-4717783 the validator is no long reporting this as an error. Closing the issue.
