### ISSUE TITLE
The validator incorrectly reports a leading space in the OrigQuote

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/tc-create-app#601]

**Comment by cckozie** [comment]
v1.1.0-rc.1
Project is at: https://qa.door43.org/translate_test/en_tn/src/branch/tcc001-tc-create-1/en_tn_15-EZR.tsv
TSV file at: [https://app.zenhub.com/files/191973535/650ea9ae-0b5b-4140-8234-9c93b3c8ceaf/download](https://app.zenhub.com/files/191973535/650ea9ae-0b5b-4140-8234-9c93b3c8ceaf/download)
Validation file at: [https://app.zenhub.com/files/191973535/3395197f-45ae-4a71-8d2e-71d62cc9cf67/download](https://app.zenhub.com/files/191973535/3395197f-45ae-4a71-8d2e-71d62cc9cf67/download)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/616ebbe0-e522-4b3b-a190-61dee14547f2)

OrigQuote:
\ud505\ubc05\u6020\ud105\ub405\u6020\ue905\uc105\ub005\ue005\ub705\ua305\uea05\u2000\ud005\ub705\ud705\ub705\u9705\uea05\u2000\udc05\ub005\u6020\udb05\ua805\ud505\ub905\ue805\ub605\ue905\uc105\u9905\u2000\ude05\ub605\ua305\udc05\ub605\uda05\ub005\u2000\ue405\ubc05\ub805\ue805\ub705\u9405\ue105

**Comment by RobH123** [comment]
Cutting the quote from https://qa.door43.org/translate_test/en_tn/blame/branch/tcc001-tc-create-1/en_tn_15-EZR.tsv#L4 and pasting into https://www.fontspace.com/unicode/analyzer#e=INeV1rzigaDXkda04oGg16nXgdaw16DWt9aj16og15DWt9eX1rfWl9eqINec1rDigaDXm9ao15XWudeo1rbXqdeB1pkg157Wttaj15zWttea1rAg16TWvNa416jWt9aU16E, I can see the leading space @cckozie .

**Comment by cckozie** [comment]
@RobH123 - Yeah, I see it there too. Sending my brain in for a checkup:)
