### ISSUE TITLE
Misleading error message from validator for 143 errors

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/tc-create-app#604]
v1.1.0-rc.1
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/0ba285d5-7217-42fa-9e43-ee84150aa05c)

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/6a173053-bfac-4703-92c6-aafb57b83223)

**Comment by birchamp** [comment]
@RobH123 I assume the standard for this is the abbreviation? So should the error read, "Bible book abbreviation is not found in the link"?

**Comment by birchamp** [comment]
@RobH123 do you know if this has been addressed?

**Comment by RobH123** [comment]
Yes @birchamp . Fixed [here](https://github.com/unfoldingWord/uw-content-validation/commit/b4a5a1010d5d68b47e086617a24d8ba2a56612e8).

**Comment by birchamp** [comment]
@cckozie Moving to QA.  @mandolyte Can you confirm that this fix is integrated into the app? If so can you move it to QA app?

**Comment by elsylambert** [comment]
Not seeing this error in translationCore Create - v1.2.0-rc.2 build 28-4717783.
