### ISSUE TITLE
Use latest content-validation library 0.9.2++

### ISSUE THREAD

**Issue by ancientTexts-net** [unfoldingWord/tc-create-app#609]
Use latest content-validation library 0.9.2++

- resolve issues in tc-create-app
- regression test

**Comment by ancientTexts-net** [comment]
See also issue Robert's PR # 71

https://github.com/unfoldingWord/uw-content-validation/pull/71

**Comment by birchamp** [comment]
@ancientTexts-net Does this need to be handled for this sprint?

**Comment by birchamp** [comment]
@mandolyte do you know if we've updated the validation?

**Comment by mandolyte** [comment]
Yes. We are at 1.x now
