### ISSUE TITLE
Ordered & Unordered Bullets together cause formatting issue when editing

### ISSUE THREAD

**Issue by richmahn** [unfoldingWord/tc-create-app#613]
This is from Dima:

```
There is some glitch in Love Article in tWords. 
Screen attached, here is a link to article bible/kt/love.md
Dima
```
![bug in article love](https://user-images.githubusercontent.com/2839925/103697567-160ed600-4f6e-11eb-9ab9-c65a97551678.png)

It appears that even in the English, when it gets to these nested bullets that it messes the layout up.

**Comment by elsylambert** [comment]
It gets fixed into correct format when the Block is toggled to be NOBlocks and the issue reappears when toggled back to Blocks.

**Comment by birchamp** [comment]
@mandolyte is this related to #661?

**Comment by ancientTexts-net** [comment]
related issue:

https://app.zenhub.com/workspaces/tc-create-workspace-5f049cdbfa88090016bf043e/issues/unfoldingword/tc-create-app/661

**Comment by elsylambert** [comment]
translationCore Create - v1.2.1-rc.1 build 50-1bb4a08.
The reported issue is fixed, the source text is not overflowing the target side. But Ordered list shows a different behaviour when Blocks is toggled to NoBlocks. See the screen capture:
https://images.zenhubusercontent.com/191973535/9a28fc2f-475c-4d5c-89c3-aff79d13e16f/ordered_list.mp4

**Comment by ancientTexts-net** [comment]
FYI to compare to PROD:

![markdownOrderedList.gif](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/0d1805f9-6f8a-4052-b8aa-87cfd931b0cb)

**Comment by elsylambert** [comment]
Moved the issue to #858.

**Comment by cckozie** [comment]
Text is not overflowing and rendered correctly (other than Elsy's observations) in v1.2.1-rc.2 build 52-944acd1
