### ISSUE TITLE
Need to let users set validation levels.

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/tc-create-app#618]
Approach:
- add to drawer menu
- use radio buttons for three levels of checks to be filtered: high, medium, low
- high is 800 and above
- medium includes high (600 and above)
- low is essentially all notices (zero and above)
----------------
Default is to be set to high.

**Comment by elsylambert** [comment]
Looks good in translationCore Create - v1.1.0-rc.3.
High- shows up 800 and above
Medium - 600 and above
All- shows all.

**Comment by birchamp** [comment]
@cckozie I added the default as High to the description
