### ISSUE TITLE
Original quote highlighting skips various words

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#62]
Highlighting is skipping some words sometimes.

Jude 1:2  'kai' should be highlighted
Jude 1:3 'tou' 
Jude 1:4 'tou' 

====================
Check highlighting on a BPF basis (3John, Titus, Ruth, Jonah)
Document verses that aren't rendering (reference, word)
Determine patterns for broken highlights
Make issues (for each issue write a test to check if the words are highlighted)

**Comment by elsylambert** [comment]
Ruth 1:4

**Comment by elsylambert** [comment]
Found instances where there are missing highlights in Rut 1:1.
![Missing Highlights](https://user-images.githubusercontent.com/51806180/73758503-ae865000-4738-11ea-95f5-706e4800ee58.png)

**Comment by RoyalSix** [comment]
Need to figure out how to determine what should be highlighted.
If all the words are aligned to the UGNT does that mean I can just look at the raw usfm3 to determine this? 
@klappy @birchamp @jag3773

**Comment by birchamp** [comment]
Proposed approach:
**iteration 1:**
Manually check if highlights are correct - line by line, but can't confirm the ULT and UST are correct.
1. document verses that fail
2. look for patterns and figure out problems.
3. create issues for specific bugs.

**iteration 2 (needs separate issue):**
have Content team check if ULT and UST are correct. They will need to look

**Comment by klappy** [comment]
3 Jn 1:10 `ἐκ`

**Comment by RoyalSix** [comment]
https://create.translationcore.com/

**Comment by RoyalSix** [comment]
Titus:
1:1 - `τῆς`` κατ’ `εὐσέβειαν`

**Comment by klappy** [comment]
@RoyalSix We need to create the associated issues for this so we can add them to this as an Epic/Sprint and estimate them.

**Comment by elsylambert** [comment]
κατ, τοῦ and ἐπ- are the most commonly missed highlights. I observed this pattern in other Greek Books like eph.

**Comment by klappy** [comment]
Should be addressed in `beta.6`

**Comment by elsylambert** [comment]
Verified in beta.6- Titus and 3Jn looks good and highlights in original quotes are fine. Checked Ruth and few other books as well.

Keeping in QA Watch.

**Comment by cckozie** [comment]
Tested in Katalon tCC tN Test Highlighting
