### ISSUE TITLE
When the user deletes text using doubleclick-Delete or inserts text using paste, the Save icon is not enabled until the onblur event

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/tc-create-app#622]
Issue:
---
The save icon should be enabled after every change. 

DoD:
---
Any change to the text enables the save button.

Details:
---
v1.0.5 and v1.1.0-rc.3
This is still a problem in v1.1.0-rc.4 build 19-6e50a4c, and it forces the user to click outside of the field when pasting in the original language quote.

[https://app.zenhub.com/files/191973535/d6206818-926d-484f-bc76-736d22eceaad/download](https://app.zenhub.com/files/191973535/d6206818-926d-484f-bc76-736d22eceaad/download)

**Comment by ancientTexts-net** [comment]
I suspect markdown-translatable is firing the event on KEYPRESS.  This event will not register CONTROL KEYS (including CTRL+V, Backspace, Delete, etc.).  Instead, we need to fire the event on KEYUP.

**Comment by birchamp** [comment]
This may be related to the bug in #622.

**Comment by elsylambert** [comment]
Not seeing this issue in translationCore Create - v1.4.0-rc.2 build 96-14c4cc5.
