### ISSUE TITLE
Content validator : notice disabling failing 

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#627]
More [ ]( ) links than valid Bible links - this should not be displayed in the csv file.

**Comment by birchamp** [comment]
@elsylambert is the same as uw-content-validation#122 ?

**Comment by elsylambert** [comment]
@birchamp Yes, the same as  uw-content-validation#122.

**Comment by birchamp** [comment]
closing this as it's a duplicate
