### ISSUE TITLE
Use Repo Icon for Resource

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/tc-create-app#63]
We have repo icons defined in DCS and it seems like the GLTS should use those for the icons of the resources.  e.g. currently the app is pulling the USER/ORG icon and not the REPO icon:

<img width="671" alt="Screen Shot 2020-01-28 at 3 31 48 PM" src="https://user-images.githubusercontent.com/107731/73302973-8d2ade80-41e3-11ea-900b-3ea934a0e2dd.png">

But, see the icon associated with the ta repo at https://git.door43.org/unfoldingWord/en_ta as an example:

<img width="316" alt="Screen Shot 2020-01-28 at 3 34 11 PM" src="https://user-images.githubusercontent.com/107731/73303034-a764bc80-41e3-11ea-9fac-8ce86cfae3a7.png">

**Comment by klappy** [comment]
Should be addressed in Alpha.27

**Comment by elsylambert** [comment]
Verified in alpha-28.Icons are changed and looks good for the Resources

**Comment by elsylambert** [comment]
Repo icons for the Resources should be available on the header when the Resources are opened.

**Comment by klappy** [comment]
@birchamp Do we want to fail this one or create a new issue for what we found during sprint review. I noticed there was one more location, I hate for this to be failed because of my OCD :)

**Comment by klappy** [comment]
App bar now displays repo avatar in Beta.4

**Comment by elsylambert** [comment]
Looks good in Beta4. 
@birchamp  The original icon file is a little blurred that makes the Avatar even more unclear. Need to have nice clear icons in future.
