### ISSUE TITLE
Hyperlinks []( format being changed

### ISSUE THREAD

**Issue by ancientTexts-net** [unfoldingWord/tc-create-app#633]
Grant Ailie found a problem with tC Create automatically changing `[](...)` hyperlinks
For example you can see the issue in Ezra 1:3

DOD: Hyperlinks will NOT be automatically changed by tC Create

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/19a170ab-eeeb-428e-a31a-113e5c25e764)

**Comment by ancientTexts-net** [comment]
I believe the root cause is that the ORIGINAL EZR file has the invalid link.

compare Ezra 3:8 (ID = ckj4)
This link works fine in tC Create.
![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/a05fe999-0c24-4e96-aeca-1c9645866e85)

See Ezra 1:3 for invalid hyperink:
![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/5219cd62-630e-4329-bf62-4d9a014b3243)

**Comment by cckozie** [comment]
v1.1.0-rc.4 build 19-6e50a4c
I am unable to test because both well formed and badly formed links give a 404 type error when clicked.

**Comment by elsylambert** [comment]
translationCore Create - v1.1.0-rc.4 build 19-6e50a4c.
the link is not changed by tcCreate as reported. Now the link is displayed correctly but it does not link properly to the verse which is written up in

**Comment by elsylambert** [comment]
Based on our discussion with Zach, I am moving this issue to QA done. The link problem will be tracked/handled by #679.
