### ISSUE TITLE
Add ids to the CV radio buttons

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/tc-create-app#634]

**Comment by cckozie** [comment]
This is what Katalon is seeing. It looks like the combination of name, type, and value would uniquely identify the radio buttons, but I'm not seeing a unique id field.
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/b65f4ca6-2baa-41a6-ac55-952d7b1b41a1)

**Comment by mandolyte** [comment]
Looks like the "id" ended up on a parent <label> element.

[image: image.png]

Here is the "high" element expanded. To test, do you need to identify the
<input> element?
[image: image.png]


Cecil

**Comment by elsylambert** [comment]
Medium and Above--
![Screen Shot 2021-01-29 at 12.22.31 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/37b6c01c-7409-4ee4-b979-4f1864512d8c)
High--
![Screen Shot 2021-01-29 at 12.22.10 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/2d0c563b-c7a5-439e-ae2e-0b290e5f57bf)
All--
![Screen Shot 2021-01-29 at 12.21.38 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/559debe9-85d0-4f64-8af2-2070efc65f5a)

**Comment by cckozie** [comment]
Discussed with the devs so they better understand what we're seeing.
