### ISSUE TITLE
Allow QA to test the final production build

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#635]
Currently the workflow requires a new build for production. This means that the production build is not what QA tested.  We need to find a way to either use the commit hash as the build number or restrict access to the production build until it's ready to be released.

**Comment by birchamp** [comment]
@klappy @ancientTexts-net Can this be handled in Netlify? A production build that uses the production server but not fully released so QA can look at it first.

**Comment by ancientTexts-net** [comment]
meeting witih @richmahn & Jaap-Jan

discussed current DCS/gitea environments & ways to provide what Kos/Elsy need

Spreadsheet:
https://docs.google.com/spreadsheets/d/1nY023IJa1sZZWulp5EO4ed8iY6f7aIQSb8Q_vzVgg4s/edit?ts=60af92d1#gid=0

Notes
![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/efc986a5-17b2-4f36-816d-2f85c99cc991)

**Comment by ancientTexts-net** [comment]
@elsylambert @cckozie 

https://stage--tc-create-app.netlify.app/

- current "pre-production" build (release build codebase -- not RC)
- uses PROD data

**Comment by elsylambert** [comment]
Verified https://stage--tc-create-app.netlify.app/

 - uses Prod (git.door43.org)- works as expected.
- Build version is incremented from develop which is a known problem currently.
- Live site is unaffected by this change-as expected.

Looks good at this point as it serves the purpose for QA to test pre-release build.

**Comment by cckozie** [comment]
v1.2.1 build 54-23bc2b8
I concur with Elsy's comment above.

**Comment by ancientTexts-net** [comment]
♥ thanks Elsy & Kos

**Comment by elsylambert** [comment]
@ancientTexts-net reported issues when merging PR from Staging to Production. This issue is partiality solved in terms of allowing QA to test pre-production and making the final production release.

**Comment by ancientTexts-net** [comment]
here's the diff of the netlify builds
nothing major in the packages section

we could compare the ZIPS if we want

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/909ec6b8-8300-442a-9c34-0aa50cfe9bfd)

**Comment by ancientTexts-net** [comment]
@elsylambert @cckozie 
Ready for testing, please!  Apologies

STAGE is fixed and there's a new branch release 
`STAGE` has `v1.2.1` using `git.door43`
`v1-2-1` branch release is using `qa.door43`

https://stage--tc-create-app.netlify.app/

https://v1-2-1--tc-create-app.netlify.app/

**Comment by ancientTexts-net** [comment]
on standup, 
agreed to spend [4] hours diagnosing 
- what was root cause (compare ZIPS)
- is there an easy way to deploy ZIPS to netlify without rebuilding ?

**Comment by birchamp** [comment]
@ancientTexts-net try a commandline diff tool

**Comment by elsylambert** [comment]
This works fine. QA is able to test with Production data on Staging server.
