### ISSUE TITLE
CV should not report "Resource container link should have '*' language code"

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#637]
As per my conversation with Robert,"* "instead of "en" notices are still not being disabled properly. We should not see those error messages in the Validation file.

**Comment by RobH123** [comment]
Can anyone confirm what version of the CV package this is failing on? (I thought this was fixed on v1.0.1 but maybe not???)

**Comment by RobH123** [comment]
I think from [here](https://github.com/unfoldingWord/tc-create-app/blob/develop/package.json#L32) which @mandolyte helpfully pointed me to, I can see that it's not yet using v1.0.1 where this is hopefully fixed.

**Comment by elsylambert** [comment]
Not seeing this error report in translationCore Create - v1.1.0-rc.4 build 18-e095e04. Looks good.

**Comment by cckozie** [comment]
Looks good in v1.1.0-rc.4 build 18-e095e04
