### ISSUE TITLE
CV reports errors - unknown book names due to misspelled book names in the program data file

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#638]
![Screen Shot 2021-01-11 at 1.40.46 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/ae530ef3-a9d9-491e-badd-f8ff50306c2c)

**Comment by ancientTexts-net** [comment]
Robert says It would have been incorporated in v1.0.2 released 16 Jan. (See the Versions tab here.)
https://www.npmjs.com/package/uw-content-validation

**Comment by ancientTexts-net** [comment]
This is pushed as a WIP PR
so it won't be merged yet

but preview is here 

https://deploy-preview-697--tc-create-app.netlify.app/

**Comment by elsylambert** [comment]
Preview looks good. Not seeing the error. Thanks @ancientTexts-net

**Comment by elsylambert** [comment]
Not seeing this error in translationCore Create - v1.2.0-rc.2 build 28-4717783.

**Comment by cckozie** [comment]
Errors not showing in v1.2.0-rc.2 build 35-01cd274
