### ISSUE TITLE
MD Content not displaying all target content

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/tc-create-app#64]
When the target MD content exceeds the number of blocks or sections from the source, they are not displayed.

If there is more source blocks all blocks will be displayed and non-existing targets will be empty as expected. However, if there are more target blocks, the blocks are not displayed past the rendered source blocks.

A possible approach is to base the number of blocks on the highest number of either source/target and render the other side with empty content.

**Comment by klappy** [comment]
Partially addressed via workaround with Issue #2 .

**Comment by mandolyte** [comment]
Some notes and question:

Question: in markdown terms, what is a "block"? what is a "section"? @klappy 

I noticed in [demo page](https://markdown-translatable.netlify.app/#/Translatable?id=translatable-1) that when I add an extra level one with content to the end of translation pane (right side), I can see the extra content only when both of the following are true: Expanded option is selected and section view is selected. In different words, 
- the extra content is not visible when collapsed
- the extra content is not visible when expanded and block view is on

Just be sure that the source is used as basis of block view, I added another section to the source and the extra content became visible in block view.

**Comment by klappy** [comment]
This is challenging to recreate in the app but theoretically can happen.
There is a sample "A More Complex Example":
https://markdown-translatable.netlify.app/

The last section would not display unless this was fixed. Before the fix there had to be source content for the section and block in order for it to display.

**Comment by elsylambert** [comment]
Tested at Markdown-translatable RCL. Extra section at the Target section looks good.
