### ISSUE TITLE
Scroll to top

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#65]
Scroll to top for pagination (check useEffect to watch props if needs to scroll to top)
Switching books should scroll to the top

- pagination
- changing books

**Comment by klappy** [comment]
Two implementations:

tC Create App:
- /scr/components/translatable/Translatable.js
  - useEffect watching all input props, then scroll to top.

DataTableTranslatable:
- pagination
- filter change
- onSearch change? (not currently accessing this, the dependency does)

**Comment by klappy** [comment]
Good job on the DatatableTranslatable RCL scrolling on events. 
Since the MarkdownTranslatable doesn't appear to have events that need scrolling, the only remaining scrollToTop functionality needed is for changing files at the App level.

**Comment by klappy** [comment]
@RoyalSix DatatableTranslatable RCL changes have been published to NPM as v0.7.1 and ready to use in the app when you make the PR for the scrolling on file changing.

**Comment by elsylambert** [comment]
Verified in v0.9. beta-4. Scroll to Top is working fine on pagination and while switching books.
