### ISSUE TITLE
Add OBS Study Questions in TSV

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#661]
Add support for OBS Study Questions in TSV
https://git.door43.org/unfoldingword/en_obs-sq (currently newformat branch)

**Comment by elsylambert** [comment]
translationCore Create - v1.1.0-rc.4 build 19-6e50a4c.
The source text Answers overflows to the target side.
![Screen Shot 2021-01-29 at 1.24.52 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/4789898f-f7d9-461b-8812-aa40f6c8056c)

**Comment by mandolyte** [comment]
Findings:
1. In HTML mode, with blocks turned on, the text overflows and does not wrap within the cell.
2. In HTML mode, the numbered lists do not increment.
3. This resource type (obs-sq) uses a tab character to indent the answer under the question. However, a tab character cannot be entered by tc-create; we may need to do some data migration and re-training of users before implementing.
4. In markdown, three spaces at the beginning of a line will indent like a tab. If all tabs are converted to three spaces, then:
- Preview (HTML mode) with no-blocks on looks good.
- Preview with blocks almost looks good; it only fails to indent the answer under the question.
- Markdown mode with blocks or no-blocks looks OK.

@elsylambert @ancientTexts-net @birchamp

**Comment by BincyJ** [comment]
removed it from 1.1 build . Blocked for stakeholder definition

**Comment by BincyJ** [comment]
With TSV Impact, should this be prioritized at this time? Need confirmation  @birchamp

**Comment by birchamp** [comment]
TSV has been completed for this.

**Comment by birchamp** [comment]
@RobH123 is there going to be a CN release version for the TSV for OBS-SQ?

**Comment by RobH123** [comment]
@birchamp I think Larry S has to be the one to decide that -- maybe ask on Zulip?

**Comment by birchamp** [comment]
@birchamp need to release in TSV

**Comment by birchamp** [comment]
@mandolyte is there a way to have unpublished files show up for edit mode and fail for translate mode because the published source doesn't exist?

**Comment by birchamp** [comment]
@mandolyte yes we should test this.

**Comment by elsylambert** [comment]
translationCore Create - v1.4.0-rc.2 build 96-14c4cc5.
Not seeing OBS SQ in the Resource list: en_obs-sq.
![Screen Shot 2021-11-10 at 11.10.11 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/adbd5ee2-8476-453c-ba09-12e38343ed16)

**Comment by elsylambert** [comment]
translationCore Create - v1.4.0-rc.2 build 96-14c4cc5.
Seeing endless spinner on the blank screen but no errors in the console for OBS-tQ.![Screen Shot 2021-11-10 at 10.56.18 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/525e6a32-0e1d-4b39-ac63-344282a8e0a5)

**Comment by elsylambert** [comment]
translationCore Create - v1.4.0-rc.3 build 104-85b41fb. Response field has to be in default view and header is missing written separately in #1101.

**Comment by elsylambert** [comment]
Looks good in translationCore Create - v1.4.0-rc.4 build 108-41a72cb.
