### ISSUE TITLE
Material UI component name change

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/tc-create-app#662]
Deprecation needs to be handled.

![image.png](https://images.zenhubusercontent.com/5e8cb99214ac08760f0cb72b/ffe3a386-69d4-4908-a9ab-abd26a268888)

**Comment by mandolyte** [comment]
NOTE: this is used by SectionTranslatable in the markdown-translatable package.

**Comment by ancientTexts-net** [comment]
Per deprecation notice at:
https://material-ui.com/api/expansion-panel/

**Comment by birchamp** [comment]
used by markdown sections.

**Comment by ancientTexts-net** [comment]
@cckozie @elsylambert 

FYI, for testing:

You can see the OLD name in PROD:
![2021-04-07 12_13_56-Work-UnfoldingWord-2021 - VMware Workstation 16 Player (Non-commercial use only).png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/eed97e07-914f-4eac-8ac2-0d226c8d486a)

and the NEW name in DEVELOP:
![2021-04-07 12_11_46-Work-UnfoldingWord-2021 - VMware Workstation 16 Player (Non-commercial use only).png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/3c18adf7-c73b-4800-89e8-930a3dec485d)

**Comment by cckozie** [comment]
v1.2.0-rc.3 build 28-c60492b
I'm not seeing any problems caused by this update.

**Comment by elsylambert** [comment]
Not seeing any issues by this change in translationCore Create - v1.2.0-rc.3 build 28-c60492b.
