### ISSUE TITLE
Add OBS-TQ

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#666]
Allow the user to translate TranslationQuestions for OBS https://git.door43.org/unfoldingWord/en_obs-tq

**Comment by elsylambert** [comment]
Looks good in translationCore Create - v1.1.0-rc.6 build 21-ad9123a. Except for the font sizes not seeing any issues.

**Comment by cckozie** [comment]
Looks good in v1.1.0-rc.7 build 22-ebe4a7c
