### ISSUE TITLE
Rebrand GLtS to tC Create

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/tc-create-app#67]
Rename:
- [x] Repo
- [x] Netlify
- [x] subdomain
- [x] package.json
- [x] readme/documentation
- [x] manifest.json
- [x] Browser Tab Title

-----
Don't include in this issue to consider done:
- [ ] Links from posts
- [ ] redirects

**Comment by elsylambert** [comment]
@klappy Please post the new link to the app.

**Comment by klappy** [comment]
Here is the develop deployment:
https://develop--tc-create-app.netlify.com

Here is the production deployment:
https://create.translationcore.com

**Comment by klappy** [comment]
@birchamp There are two items that left undone from this issue. Redirects and updating links on posts. 

Do we know which posts need updating? 
With redirects, the way I setup a new separate app in Netlify, it won't let me setup redirects anymore.

Are we okay with closing this issue without those two items being checked off?

**Comment by elsylambert** [comment]
Looks good in Beta-2.
I do not have information on the posts either.

**Comment by klappy** [comment]
@elsylambert, it appears as though we are good to go on this issue. The remaining issues will be addressed separately.
