### ISSUE TITLE
Run Time error on using use-deep-compare-effect

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/tc-create-app#674]
This NPM component now throws an error if only primitives are in the dependency list.

The error is for one or more useEffect() functions (4 total) used in gitea-react-toolkit 's useFile.js.

**Comment by ancientTexts-net** [comment]
@elsylambert @cckozie 

In this case, the whole app would crash with error about `use-deep-compare-effect with primitives`

We do not believe this happens any more (build 20-936fafa)

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/f2cad9c1-df05-491e-8ddf-03a15af27180)

**Comment by elsylambert** [comment]
translationCore Create - v1.1.0-rc.4 build 20-936fafa works fine without crash.
