### ISSUE TITLE
Remove OBS Study Question resource

### ISSUE THREAD

**Issue by BincyJ** [unfoldingWord/tc-create-app#684]
Only the markdown resources of OBS (tN, tQ, SN) to be included in the related. OBS Study questions to be removed.

**Comment by mandolyte** [comment]
I believe we decided to leave the pure markdown OBS resource types. The only one having issues is the study questions which is in some formatted markdown that tc-create cannot support (uses indentation blocks that can only be done in markdown mode)

**Comment by cckozie** [comment]
@birchamp - These are the OBS resource in v1.1.0-rc.6 build 21-ad9123a. Are those the ones we want?
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/b66f4efb-c254-4959-a6d3-db1010945b25)

**Comment by elsylambert** [comment]
translationCore Create - v1.1.0-rc.6 build 21-ad9123a. en_obs-sq OBS Study questions is removed as expected. The other resources which uses Markdown format looks good and can be part of 1.1.0 Release.

**Comment by BincyJ** [comment]
@cckozie the issue requirement has been update. Let me know if any further action needed. Thanks!
