### ISSUE TITLE
Create and Implement helpers for Edit/Branch workflow

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/tc-create-app#71]
# Steps
1. Check requirements to see if Edit/Branch workflow is needed.
    - Create helper for the logic.
      - Language matches source repo.
      - User has permissions to source repo.
2. Conditionally set Target repo based on above.
    - if true (new convention)
      - The target owner will be the same as the source (organization).
      - The target repo to use will be the same as the source.
      - The branch will use the convention `USER-tc-create-1`.
    - if false (existing convention)
      - The target owner will be the user logged in.
      - The target repo name will be `LANGUAGE_RESOURCE`.
      -  The branch will be `master`

Step two writeup is probably longer in description than the actual code for it :laughing:

**Comment by elsylambert** [comment]
Works as expected in beta 10.
