### ISSUE TITLE
Display toolbar on scroll up for TSVs

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#717]
The toolbar should be displayed when the user scrolls up on a TSV.

Scrolling down the toolbar disappears.

![tC Create 2021-03-16 09-36-21.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/70d834a1-fe38-4abb-86b5-68c774df5530)

Scrolling up makes it appear.
![tC Create 2021-03-16 09-36-50.png](https://images.zenhubusercontent.com/5cf53901e39e5f33e3e129fa/a5add12e-5d14-40ad-9d08-ceb29953b6ba)

**Comment by birchamp** [comment]
needs def @birchamp

**Comment by ancientTexts-net** [comment]
how does this look please?

@birchamp 
@elsylambert 
@klappy 
@elsylambert 
@cckozie 

![717-scrollbar.gif](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/9345c1fa-a18c-4de2-8e49-9951c357b7a6)

**Comment by elsylambert** [comment]
@ancientTexts-net looks good to me.

**Comment by cckozie** [comment]
Are we willing to give up that much real estate to fix this problem? 
Why does tsv use a different Save toolbar than md?

**Comment by birchamp** [comment]
@ancientTexts-net I see the blue bar is permanent, but you can't have the toolbar with the save button hidden while scrolling down until the user scrolls up?

**Comment by mandolyte** [comment]
@birchamp are you wishing for both the app bar and the toolbar to scroll off the top _when scrolling up_ and the re-appear one at a time when the user scrolls down?

This would be similar to how my Android phone (v11) works.

**Comment by birchamp** [comment]
@ancientTexts-net @mandolyte  I've posted screens of what our goal is.  Sounds like we may not be able to do that.

**Comment by ancientTexts-net** [comment]
![scrollbars-2.gif](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/55120a78-7d7d-4d8d-afd2-24a0a637df7c)

current status:

@birchamp @BincyJ @elsylambert @cckozie @mandolyte

**Comment by ancientTexts-net** [comment]
PR for this is included in other issue:
https://app.zenhub.com/workspaces/tc-create-workspace-5f049cdbfa88090016bf043e/issues/unfoldingword/tc-create-app/236

**Comment by cckozie** [comment]
@birch - I can't find the final decision of the required behavior in this issue, so I want to verify that the Save icon bar should always remain in view in tsv files.

**Comment by birchamp** [comment]
Yes that's correct. It's an improvement over the previous behavior even though it wasn't exactly what we wanted.

**Comment by cckozie** [comment]
Words as expected in v1.1.1-rc.3 build 44-bde198f

**Comment by elsylambert** [comment]
translationCore Create - v1.1.1-rc.3 build 44-bde198f.
Save toolbar is no longer hidden by the blue top bar and is visible while scroll up/down. Works as expected.

**Comment by cckozie** [comment]
Added Katalon test for this issue to tCC tA Test Block Quotes and Sections
