### ISSUE TITLE
BSA Propogate OnClick from Verse up to Book View

### ISSUE THREAD

**Issue by ancientTexts-net** [unfoldingWord/tc-create-app#719]
BSA needs to trigger a user action based on "onClick" on a `Verse` object.

1. propogate `reference` object down from Book --> down to the `Verse` object
2. implement a `referenceSelectedContext` to manage state for the selected reference
3. wire up onClick to set the referenceSelectedContext state
4. implement a demo (Verse.md)

DoD: the Verse.md demo can do "something" with the referenceSelectedContext state (e.g., display an alert) on onClick on a verse.

This work was developed live in a group session with GeCraft.

**Comment by elsylambert** [comment]
@ancientTexts-net Please add more details on how this can be tested in the app.

**Comment by elsylambert** [comment]
@ancientTexts-net Please add the RCL link to be tested.

**Comment by ancientTexts-net** [comment]
@elsylambert @cckozie 
to test:

I. test "VERSE" component
https://scripture-resources-rcl.netlify.app/#/Verses%20?id=verse

1. click verse
Verify: popup alert shows.

2. click verse again
Verify: popup does NOT show (since verse selection doesn't change).

---

II. test "VERSES" component
https://scripture-resources-rcl.netlify.app/#/Verses%20?id=verses-1

1. click a verse
Verify: popup alert shows.

2. click same verse again
Verify: popup does NOT show (since verse selection doesn't change).

3. click a DIFFERENT verse
Verify: popup alert shows NEW verse.

.

**Comment by cckozie** [comment]
I am seeing the expected behavior based on the tests documented above.

**Comment by elsylambert** [comment]
Tested the above mentioned tests on the RCL and found to be working as expected.
