### ISSUE TITLE
Create and Implement button to create PR on DCS

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/tc-create-app#72]
Described in more detail from @jag3773's request:
https://github.com/unfoldingWord/tc-create-app/issues/61#issuecomment-583072586

# Steps
- Move current "delete action" link to whole chip link for Target File (right).
- Change "delete action" icon to something new.
- Change "delete action" link to `https://git.door43.org/OWNER/REPO/compare/master...USER_BRANCH`.
- Only make "delete action" link work if Edit/Branch workflow is used.

# Question to be answered:
- Need UX design
  - Where do we want the button
  - What will the button look like
  - Keep in mind that there will be another button to review the current branch status (if behind master).

**Comment by elsylambert** [comment]
Beta-8. It gives error 500 when Branch is compared with the Master.

**Comment by elsylambert** [comment]
Looks good in Beta 10.
