### ISSUE TITLE
Create and Implement button to compare branch with master

### ISSUE THREAD

**Issue by klappy** [unfoldingWord/tc-create-app#73]
Decribed in more detail from comment:
https://github.com/unfoldingWord/tc-create-app/issues/61#issuecomment-583087467

# Steps
- Move current "delete action" link to whole chip link for Source File (left).
- Change "delete action" icon to something new.
- Change "delete action" link to `https://git.door43.org/OWNER/REPO/compare/USER_BRANCH...master`.
- Only make "delete action" link work if Edit/Branch workflow is used.

**Comment by elsylambert** [comment]
<img width="1792" alt="Screen Shot 2020-03-20 at 11 22 18 AM" src="https://user-images.githubusercontent.com/51806180/77178251-3207c080-6a9d-11ea-88d9-03738be6151b.png">
Got this error when I tried to compare my branch.

**Comment by elsylambert** [comment]
Looks good in Beta-10.
