### ISSUE TITLE
The icon bar is significantly higher in tsv files than in md files

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/tc-create-app#742]
Make the TSV Save Toolbar the same height as the MD Save Toolbar.  Or VERY close to it.

v1.2.0-rc.2 build 28-4717783
It looks like the bar is ~ 108 pixels high when in md files and 144 pixels high when in tsv files.
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/c3bb148a-968b-4968-acd0-162b32397a6d)

**Comment by ancientTexts-net** [comment]
The PR for this issue belongs to related issue:
https://app.zenhub.com/workspaces/tc-create-workspace-5f049cdbfa88090016bf043e/issues/unfoldingword/tc-create-app/236


See screenshot here:  toolsbars are the same size now:

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/ad045e1a-0809-43b6-8429-4fc55ded854c)

**Comment by cckozie** [comment]
I am still seeing the same bar heights in v1.1.1-rc.3 build 44-bde198f

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/d5c15ee9-9c28-48d5-856b-d082fcee62c3)

**Comment by elsylambert** [comment]
Looks good in translationCore Create - v1.1.1-rc.5 build 46-0da716b

**Comment by cckozie** [comment]
Add Katalon test for this issue to tCC tN Test Moving Rows
