### ISSUE TITLE
Fetch source files from Door43-catalog 'published' repo

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#756]
This issue was covered in #882

Currently, tCC opens the files in the master branch of the unfoldingWord organization. GL teams want to work from the published English text which has a specific version.

The source files should be pulled from the door43-catalog organization for every supported resource. 
- [ ] TWL - Latest release from: https://git.door43.org/unfoldingWord/en_twl
- [ ] TA - https://git.door43.org/Door43-Catalog/en_ta
- [ ] TW - https://git.door43.org/Door43-Catalog/en_tw
- [ ] TN - https://git.door43.org/Door43-Catalog/en_tn
- [ ] TQ - https://git.door43.org/Door43-Catalog/en_tq
- [ ] OBS - https://git.door43.org/Door43-Catalog/en_obs
- [ ] OBS TQ - https://git.door43.org/Door43-Catalog/en_obs-tq
- [ ] OBS TN - https://git.door43.org/Door43-Catalog/en_obs-tn
- [ ] OBS SN - https://git.door43.org/Door43-Catalog/en_obs-sn

DoD: The 'source side' of the app displays the latest published in door43 catalog instead of the Master files for all supported resources.

**Comment by BincyJ** [comment]
Need to explore the and design solution.

**Comment by mandolyte** [comment]
@ancientTexts-net Thought I'd help with this spike by searching for the string `unfoldingword` in our code base. Turns out that I was probably too worried. Here is one that may need to change:

In GRT, `repositories.js`:
```js
export async function fetchResourceManifests({username, languageId}) {
  let manifests = {};
  const _resourceRepositories = resourceRepositories({languageId});
  const resourceIds = Object.keys(_resourceRepositories);
  const promises = resourceIds.map(resourceId => {
    const repository = _resourceRepositories[resourceId];
    const _username = ['ugnt','uhb'].includes(resourceId) ? 'unfoldingword' : username;
    return fetchManifest({username: _username, repository})
  });
  const manifestArray = await Promise.all(promises);
  resourceIds.forEach((resourceId, index) => {
    manifests[resourceId] = manifestArray[index];
  });
  return manifests;
};
```

And of course that one place that definitely needs to change in tc-create itself is `state.defaults.js`:
```js
const config = {
  authentication: {
    server: SERVER_URL,
    tokenid: appPackage.name,
  },
  repository: {
    urls: [
      SERVER_URL + '/api/v1/repos/unfoldingword/en_ta',
      SERVER_URL + '/api/v1/repos/unfoldingword/en_tw',
      SERVER_URL + '/api/v1/repos/unfoldingword/en_tn',
      SERVER_URL + '/api/v1/repos/unfoldingword/en_tq',
      SERVER_URL + '/api/v1/repos/unfoldingword/en_obs',
      SERVER_URL + '/api/v1/repos/unfoldingword/en_obs-tq',
      SERVER_URL + '/api/v1/repos/unfoldingword/en_obs-tn',
      SERVER_URL + '/api/v1/repos/unfoldingword/en_obs-sn',
    ],
  },
};
```

**Comment by birchamp** [comment]
Create a single variable that stores the source location. All references need to point to this variable.

**Comment by birchamp** [comment]
This is blocked until we can confirm that we can get the latest tagged release via Catalog Next features.

**Comment by ancientTexts-net** [comment]
NOTE: In immediate term, TWL will come from unfoldingWord org (latest release)

**Comment by birchamp** [comment]
Do we wait for a catalog next RCL or do we fetch these files from door43-catalog?
