### ISSUE TITLE
SPIKE [12]: Changing source version

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#758]
Default source version should be latest published if nothing is specified in the manifest.
* Users want to know which version **each book** was translated from - not at the resource level. 
* Users want to see the source side from the version that it was translated from.  
* Admins want to be able to change the source version. 

What are the effects of switching source versions?  Would it cause more merge conflicts? Source vs Target
Can it be done with the current catalog or do we have to wait until catalog next? Yes, tC can do this.
Could we lock them to a particular version per book? if so, what mechanisms will be needed? changes to the manifest?
How can we book by book (TSV) track what source version was used for the translation? 
UX suggestions? How does the user change source versions?

**Comment by ancientTexts-net** [comment]
- READ source manifest --> WRITE version to target manifest
- UI considerations (to change/upgrade) (NOTE: spike for "diff" view is considered in # 759 )

**Comment by ancientTexts-net** [comment]
https://git.door43.org/api/v1/repos/unfoldingword/en_tn/releases

**Comment by birchamp** [comment]
@ancientTexts-net do you have documentation to add to this?

**Comment by ancientTexts-net** [comment]
TODO: "per book" admin setting

**Comment by ancientTexts-net** [comment]
https://docs.google.com/document/d/1S7CChjQBY83C_O_i7z7QM6s1PDje_c4aZbxMJMNdgoU/edit

**Comment by ancientTexts-net** [comment]
![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/19e33707-04ce-4685-af37-b189c6925108)

**Comment by ancientTexts-net** [comment]
Search for Versions:
- https://qa.door43.org/api/catalog/v5/search?owner=ru_gl

Entry includes "new" fields from manifest:
- https://qa.door43.org/api/catalog/v5/entry/ru_gl/ru_tn/V91

**Comment by ancientTexts-net** [comment]
compare chat about this spike

https://unfoldingword.zulipchat.com/#narrow/stream/209457-SOFTWARE--.20UR/topic/tc-create-app.23758

**Comment by ancientTexts-net** [comment]
![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/560c0be3-0a50-4885-b9e8-a50252d0a0be)

**Comment by ancientTexts-net** [comment]
FYI Gitea supports comparing TAG to BRANCH 
by comparing the tag's last COMMIT to the BRANCH name)

e.g.,

https://bg.door43.org/unfoldingWord/en_tn/compare/18055bbbd6ff00bfe830c3e8ba6a2c6657d55c37...master

**Comment by BincyJ** [comment]
@ancientTexts-net please add issues to close out the spike

**Comment by ancientTexts-net** [comment]
Spike Questions:
- What are the effects of switching source versions? Would it cause more merge conflicts? Source vs Target  
	- ❌ RISK of creating more conflicts: 
		(See "Merge Conflicts" below)
	- NOTE: See "4 phases" above.
	- NOTE: Current scope does not include diff/compare.
- Can it be done with the current catalog or do we have to wait until catalog next? 
	- ❌ If we want to filter the "Versions" list, this (optional) feature will require DCS upgrade.

- ✔Could we lock them to a particular version per book? if so, what mechanisms will be needed? changes to the manifest? 
- ✔How can we book by book (TSV) track what source version was used for the translation?  
	- Suggested changes to manifest.yaml is OK: compatible with current DCS & Catalog Next API.
	- See "NOTES: Per Book Admin Setting," below

- ✔UX suggestions? How does the user change source versions?
	- (See screenshot below for suggested UI.)
	- Recommended (decided?) to filter the list of VERSIONS for the current selected file (see "Deriving published file revisions")

---

NOTES: "Per Book" Admin Setting
- manifest.yaml can be extended without breaking DCS or Catalog Next:
	![[Pasted image 20210623125255.png]]
	![[Pasted image 20210623125317.png]]
- Catalog Next will return FILE source version,
	but does NOT return REPO source version:
	![[Pasted image 20210623125122.png]]
	
NOTES: Upgrade Target
- NEW Records:
	- Compare rows by ID
	- Any new source rows, insert into target.
	- Will naturally float to end of file.
- DELETED Records: 
	- Compare rows by ID.
	- Any target rows that do NOT exist in new souce, "FLAG FOR DELETE"
	- ❓ TBD: ?? How do we flag for delete?
- MODIFIED Records: 
	- ❓ Get list of ROWS modified between versions (use DIFF to compare TAGS -- see below.)
	- Flag any affected target rows as modified.
	- ❓ TBD: ?? How do we flag as modified?
	
NOTES: Merge Conflicts
- MODIFIED records may introduce additional merge conflicts.
- If many rows are modified,
	& if "modified" status is stored in the TSV.

NOTES: Deriving published file revisions (Dependency)
- Cecil/Rich can provide a  Releases list, filtered by file name.
- https://docs.google.com/document/d/1hgnbzUyEoiNgoFj173jDXx3OqFKyftdcwzYl1YwAck4/edit

---

Links: DCS / Catalog-Next:
- Search for Versions:
	https://qa.door43.org/api/catalog/v5/search?owner=ru_gl

- Entry includes "new" fields from manifest:
	https://qa.door43.org/api/catalog/v5/entry/ru_gl/ru_tn/V91

- DCS Compare TAG to BRANCH
	https://bg.door43.org/unfoldingWord/en_tn/compare/18055bbbd6ff00bfe830c3e8ba6a2c6657d55c37...master
- DCS Compare TAG to TAG
	https://bg.door43.org/unfoldingWord/en_tn/compare/v47...v48



---

Links: Zulip Chats:
- Chat about this spike:
	https://unfoldingword.zulipchat.com/#narrow/stream/209457-SOFTWARE--.20UR/topic/tc-create-app.23758
- Chat about "Deriving published file revisions"
	https://unfoldingword.zulipchat.com/#narrow/stream/209457-SOFTWARE--.20UR/topic/Deriving.20published.20file.20revisions

---

Screenshots
	![Pasted image 20210623121721.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/f88dc89e-27a5-4bde-af33-f30bc1d3872f)

.

**Comment by ancientTexts-net** [comment]
Stories:

Render Default Source Version ("Phase 2")
https://app.zenhub.com/workspaces/tc-create-workspace-5f049cdbfa88090016bf043e/issues/unfoldingword/tc-create-app/908

Choose Source Version (Phase 3)
https://app.zenhub.com/workspaces/tc-create-workspace-5f049cdbfa88090016bf043e/issues/unfoldingword/tc-create-app/907

Upgrade Source Version (Phase 4)
https://app.zenhub.com/workspaces/tc-create-workspace-5f049cdbfa88090016bf043e/issues/unfoldingword/tc-create-app/915
