### ISSUE TITLE
Add TWL resource

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#760]
See the spike here: tc-create-app#410

Users should be able to add and remove TW articles from a passage of scripture. 

Display the TWL TSV and the associated scripture. Give them all of the same functions as a TN TSV file has.  Displaying the TW article itself is outside of the scope of this issue. 

DoD: Users can edit, add, and remove records in a TWL resource.

**Comment by ancientTexts-net** [comment]
only problem is with tWL name

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/d06f2f2d-47e1-4329-83ca-30564112ff51)

**Comment by cckozie** [comment]
v1.2.0-rc.1 build 26-371f3c3

When opening TWL projects the rows per page is set to 10 instead of 25 like in TN projects.

**Comment by ancientTexts-net** [comment]
FYI #1:

Manifest contains a sort index:

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/5083748c-e8a7-454a-bcc6-b347029996f6)

**Comment by birchamp** [comment]
Problem 1 (file sort order) above has been broken out to #796

**Comment by cckozie** [comment]
tWL projects open with row/page set to 25 in v1.2.0-rc.3 build 28-c60492b

**Comment by elsylambert** [comment]
translationCore Create - v1.2.0-rc.3 build 28-c60492b.
Editing, adding and removing rows is working fine for the tWL resource.
