### ISSUE TITLE
The content validator hangs

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/tc-create-app#764]
v1.1.1-rc.3 build 44-bde198f
Open any tN project and click on the validator icon

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/47bb11b8-5219-49d4-9245-ec7e27f27f41)

**Comment by ancientTexts-net** [comment]
Thank you @cckozie 

FYI @mandolyte 
I see eror `checkTN_TSVText` does not exist

**Comment by cckozie** [comment]
The validator works correctly in  v1.1.1-rc.5 build 46-0da716b
