### ISSUE TITLE
Login screen Enhancements

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#77]
After the user enters Username and password, the page should go to next page/Language page instead of clicking on the next button. The red Logout button is confusing to the user.

Maintain same blue color of button.

**Comment by klappy** [comment]
https://github.com/unfoldingWord/gitea-react-toolkit/pull/25/commits/6485f42741b3bcbaa2756cead9799c58f3bf01d1

Included in PR:

**Comment by klappy** [comment]
Should be available on `beta.9` and above.

**Comment by elsylambert** [comment]
Verified in Beta-10. Works as expected. The red Logout button is now in Blue. Looks good.
When username and password are entered the page logs the user in and moves to the next page.
