### ISSUE TITLE
Scroll to new row after add/delete

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#78]
- Create a generated id on the row components (bookId, chapter, verse, id) computedIndice?
- When adding a new row, use the generated id to scroll to
- When deleting a row, use the row index to determine previous row index to get the generate id to scroll to.

**Comment by klappy** [comment]
Testable via `1.0.0-beta.1`

**Comment by elsylambert** [comment]
Not seeing the changes in translationCore Create - v1.0.0-beta.4. The page does not scroll to the new row after adding.

**Comment by klappy** [comment]
testable via beta.6

**Comment by ancientTexts-net** [comment]
@RoyalSix @elsylambert @BincyJ 

I am merging the PR for this issue.  But i'm not sure the scroll-to on REMOVE works as described?
Maybe an issue for QA discussion?

**Comment by elsylambert** [comment]
Not seeing the changes in translationCore Create - v1.1.0-beta.1. The page scrolls to top when a new row is added.

**Comment by elsylambert** [comment]
@RoyalSix @ancientTexts-net Please verify if the changes were merged.

**Comment by RoyalSix** [comment]
The changes were not there, sorry about that

**Comment by ancientTexts-net** [comment]
@RoyalSix please let me know if I can do anything in the review process??
Unless klappy's available now & you prefer him to review?

Thanks  ya'll

**Comment by elsylambert** [comment]
@ancientTexts-net  @RoyalSix Can you please add the link to RCL for this issue?

**Comment by elsylambert** [comment]
Tested at RCL:https://datatable-translatable.netlify.app/#/DataTable

Scroll to new row works fine.
Adding a separate issue for FILTER ON issue.

**Comment by ancientTexts-net** [comment]
Testable in `v1.0.0-beta.7`

https://deploy-preview-188--tc-create-app.netlify.app/

Features in this build:
- #148 Add resource
- #78 Scroll to new row after add/delete
- #171 Unable to save file in tW, tA, and OBS
- #120 Save action: app  needs to refresh the save action

.

**Comment by elsylambert** [comment]
Scroll to new Row works fine in https://deploy-preview-188--tc-create-app.netlify.app/.

Does not work with filter On written separately in #

**Comment by ancientTexts-net** [comment]
Testable on `develop`!  `v1.0.0-beta.7`

https://develop--tc-create-app.netlify.app/

Features in this build:

#148 Add resource
#78 Scroll to new row after add/delete
#171 Unable to save file in tW, tA, and OBS
#120 Save action: app needs to refresh the save action

**Comment by elsylambert** [comment]
Verified on translationCore Create - v1.0.0-beta.7. Scroll to new row works fine.
