### ISSUE TITLE
TSV parser RCL

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#788]
The goal of this RCL is to have a standardized parser for our TSVs. 

DoD:
---
Once this is integrated into the application TNs should function the same as before.

**Comment by mandolyte** [comment]
Spec to comply with is: https://en.wikipedia.org/wiki/Tab-separated_values

**Comment by birchamp** [comment]
@mandolyte check with @mannycolon to see how he's opening both 9 column and 7 column TNs in gatewayEdit.

**Comment by mandolyte** [comment]
## Links
uW post by Robert Hunt which calls out the spec to follow:
https://forum.door43.org/t/parascriptural-tab-separated-value-format-specification-v2/870

The spec itself is described in this article:
https://en.wikipedia.org/wiki/Tab-separated_values

The IANA standard:
https://www.iana.org/assignments/media-types/text/tab-separated-values

## Basic Operation

First, the parser must support lossless conversions to TSV. The data in memory may contain tab characters, newlines, etc. But these are not permitted in the "as stored" format. Here are the conventions (from the Wikipedia article):
```
   \n for newline,
   \t for tab,
   \r for carriage return,
   \\ for backslash.
```

Note that the above are two characters, *not* escaped single characters.

### On Read: string to 2D array

*input*: a string containing the TSV file content
*output*: a 2D array of values
*exception*: if any parsing errors, an error will be thrown containing all errors found

The input file to be converted from TSV to a two dimensional array will be processed as follows:
- the file must provided as a string
- the string will be split into an array based on the newline character (an EOL of CR-LF will not be supported)
- this array will be then read one row at a time and each row split by the tab character
- the first row will determine the number of columns expected in all the rows.
- each column value will altered per lossless conventions above. For example, changing all occurrences of backslash-t to a tab character.
- then the columns will be added to output array
- if the number of columns in the row do not match the first row, then an error message will be generated containing the:
	- the row number (zero based)
	- the number of columns found (could be more or less than expected)
	- the number of columns expected
	- the content of the row (with commas substituted for tabs)
	- an explanatory message
	- the error message will be added to an array of error messages
- after the file is processed, 
	- if there were any parsing errors, an exception will be thrown
	- otherwise, the output 2D array is returned

### On Write: 2D array to string

*input*: a 2D array
*output*: a TSV compliant string
*exceptions*:
- if input is not a 2D array (nx1 is allowed)
- if a row does have the same number of columns as the first row
- if a cell does not contain a string; for example, a cell may not be an object or an array

The 2D array will be processed as follows:
- the number of columns in the first row is noted
- the type of each column must be a string; if not then an error message is generated containing:
	- the row number (zero based)
	- the column containing the data that is not a string
	- an explanatory message
	- the error message will be added to an array of error messages
- if the number of columns does not match the first row, then an error is generated containing:
	- the row number
	- the number of columns found and the number of columns expected
	- an explanatory message
	- the error message is added to the array of error messages
- the value in each column is altered per lossless conventions
- the columns are joined to make a string, with a tab character as the field delimiter and a newline character as the record separator.
- the string for the row is added to the output string
- after the 2D array is processed
	- if there were any conversion errors, an exception will be thrown
	- otherwise, the output string is returned

## Library Design

- There will be no React UI/X in this library.
- Styleguidist will be used to demonstrate each of the following:
	- String to 2D Array
		- a normal valid parsing case
		- a case having rows that are too long and too short
		- all cases will contain values requiring lossless conversion processing
	- 2D Array to String
		- a normal valid conversion
		- a case having non-string data
		- a case with rows too long and too short
		- all cases will contain values requiring lossless conversion processing

**Comment by mandolyte** [comment]
@ancientTexts-net @birchamp @PhotoNomad0 @mannycolon @klappy 
Above post is a write up for the TSV parser module.

At present, I don't see any reason to make this asynchronous; nor any reason to provide any React UI/X components. Thus I plan to do model the Styleguidist work after the "core" demo in [uw-word-count](https://unfoldingword.github.io/uw-word-count/#!/Core).

Any feedback welcomed!

**Comment by mandolyte** [comment]
After some experience in using the code in the demos, I've decided to return an object that will contain both the expected data and errors. The "errors" will be minimalistic, allowing the calling code to deal them as they wish (in the language they wish). The errors will be either pairs or triplets of integers that precisely point to the error(s).

I will edit the above design spec to reflect this change.

**Comment by klappy** [comment]
returning an object of data and errors makes sense and aligns with other patterns that we've used.

```json
{
  data: [...rows],
  errors: [...errors]
}
```

The way I would expect to use it would be a custom hook: 

```js
const { state: { data, errors}, actions } = useTSV({ input, delimiters: { row, cell }});
```

As long as the input and delimiters trigger parsing again, the state should update for the consumer.

**Comment by mandolyte** [comment]
@klappy  -- I'm a bit conflicted about trying to make this TSV parser capable of accepting custom delimiters. uW has a very specific spec to follow and how it works is not how you'd want a CSV parser to work.

But then we run into the issue of putting uW specific code into our RCLs, which we want to avoid. Indeed you want to go further and avoid any data manipulation in components.

So how about we approach this way:
- import the new tsv parser into tc-create
- pass parsing functions to datatable. For example: `<DataTable parser={tsvActions} />` where tsvActions is a set of functions we want DataTable to use. I think there are less than half a dozen functions we need to provide it. I'll list them in the next post.

**Comment by birchamp** [comment]
@mandolyte I agree with your thinking here. With components we need to be considering reusability even over uW functionality.

**Comment by mandolyte** [comment]
Finally tried a round-trip test, wherein:
- I edit a 7col TN file and then back out the change, leaving the file unchanged from the original. Then after saving, the file in my branch should be the same as the one in master branch.
- It has several failures: 
   1. Something is converting new lines to `<br>`; this needs to be eliminated. Probably in the markdown component.
   2. Somehow newlines are getting created and passed thru. Thus any note with new line characters is becoming multiple rows on the server side.

**Comment by elsylambert** [comment]
Works as expected in translationCore Create - v1.4.0-rc.4 build 108-41a72cb with all the TSV resources .
