### ISSUE TITLE
Handle Biblical sort order for repos with a sort order in the manifest

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#796]
New TSVs don't have a sort order in the  filename anymore. Files listed in the stepper or side menu should be listed in Canonical order as specified in the manifest. If there isn't an order specified then it should be alphabetical.

**Comment by ancientTexts-net** [comment]
@mandolyte Thank you for review comments.

Ready again: added demo + refactored.

**Comment by ancientTexts-net** [comment]
ready for testing

https://develop--tc-create-app.netlify.app/
translationCore Create - `v1.2.0-rc.4 build 33-43fd9f5`

**Comment by cckozie** [comment]
v1.2.0-rc.4 build 33-43fd9f5
I'm seeing alpha sort order for twl's even though the manifest does supply the sort order. What am I missing?
![image](https://user-images.githubusercontent.com/8171759/115630978-97466a80-a2ca-11eb-844f-4b3a16289edc.png)

![image](https://user-images.githubusercontent.com/8171759/115631132-dd033300-a2ca-11eb-9565-dde505efc4df.png)

**Comment by elsylambert** [comment]
Not seeing the change as per the description in the issue in translationCore Create - v1.2.0-rc.4 build 33-43fd9f5.
The manifest does have the sort order but the TWL resource shows books in alphabetical order.

**Comment by ancientTexts-net** [comment]
ready to RE-test

https://develop--tc-create-app.netlify.app/

**Comment by elsylambert** [comment]
Looks good in translationCore Create - v1.2.0-rc.5 build 34-ab649d5. Seeing the biblical sort order as per the manifest.

**Comment by cckozie** [comment]
In v1.2.0-rc.5 build 34-ab649d5 I am now seeing the correct sort order for tWL.
