### ISSUE TITLE
Determine MD standard for Bold Italic 

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#80]
AND remove custom code in order to revert to library default. 

What is the editor default? 
*** vs **_

**Comment by birchamp** [comment]
take out custom code and ask Larry if that represents what they want.  If the default doesn't represent the MD correctly then make a new issue.

DoD:  bold italic matches what content team expects.

**Comment by RoyalSix** [comment]
The content team will be using ```***``` for bold italic

**Comment by RoyalSix** [comment]
@elsylambert nothing to test here

**Comment by birchamp** [comment]
@RoyalSix ```**_``` is the default for content now. **_test_**

**Comment by klappy** [comment]
@RoyalSix Did you mean `**_`? that's what was said during the meeting.
