### ISSUE TITLE
Sort the filter dropdowns alphabetically

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#801]
Issue:
---
Text items in dropdowns for the filter should be alphabetical. The component is supposed to do this by default but the items aren't sorted. 

DoD:
---
Text items in the filter dropdowns are in alphabetical order.

**Comment by mandolyte** [comment]
Production 1.5.1 shows alphabetical order:
![image](https://user-images.githubusercontent.com/1289437/178503402-6604958c-d6a3-4559-97cc-614d218548cd.png)

Has this been done?
@birchamp

**Comment by jincypjose** [comment]
yes this issue has been done.

**Comment by elsylambert** [comment]
Works fine in translationCore Create - v1.5.1 build 158-a763788.
