### ISSUE TITLE
On Demand validation for TWL

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#809]
Issue:
---
When the user has a TWL TSV open they should be able to run a full validation on the TWL.  The intention here is that validating TWL works the same way validating TNs does.

DoD:
---
The user can run a validation check on TWLs the same way they do with the TN TSVs. 

Details:
---

**Comment by elsylambert** [comment]
Not seeing the Content validator button on the header bar in translationCore Create - v1.4.0-rc.2 build 96-14c4cc5. Seems like this change is missing in the build.
![Screen Shot 2021-11-22 at 9.59.51 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/deb2bc15-756c-4fa3-bd37-3b790664bdca)

**Comment by elsylambert** [comment]
translationCore Create - v1.4.0-rc.3 build 104-85b41fb.
@mandolyte  The Validation file has some columns showing  as undefined, rowID and Verse. It is hard to locate the errors in the file. This screenshot is for Exodus.
![Screen Shot 2021-12-13 at 6.46.16 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/fd84b6aa-1550-4ee9-9208-91cbe21c628e)
[https://app.zenhub.com/files/191973535/b656b4c0-cff9-4559-bf94-7867ba21250f/download](https://app.zenhub.com/files/191973535/b656b4c0-cff9-4559-bf94-7867ba21250f/download)

**Comment by mandolyte** [comment]
@elsylambert what org were you using for the above CV?

I used unfoldingWord and only got this:
![image](https://user-images.githubusercontent.com/1289437/146017003-eec10492-b624-40f6-95da-9f53f8eefb39.png)

**Comment by elsylambert** [comment]
translationCore Create - v1.4.0-rc.3 build 104-85b41fb. Tested after deleting my old branch and CV looks goon on tWLs.
