### ISSUE TITLE
Pasting inserts line breaks that can't be removed immediately

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#839]
~~**Note**: This needs to be tested after Preview editing has been disabled. #871~~ 
This was tested and it is a problem in raw markdown mode.

tC Create has the following behavior that should be removed: when something is pasted into the edit field (from anywhere), it adds line breaks. In order to remove those line breaks, the user has to click out of the field and then back in again, then can proceed to delete the line breaks. That adds a lot of time to the edit process.  Doing a 'unformatted paste' does not add the line break.

DoD:
---
Pasting in text does not add a line break unless the line break is in the clipboard. 

Details:
---
From https://unfoldingword.zulipchat.com/#narrow/stream/207526-tools/topic/tC.20Create.20App.20.28GLtS.29/near/236361042

**Comment by elsylambert** [comment]
For reference and definition of how it works currently #444.

**Comment by jincypjose** [comment]
Findings- 
While clicking the perview button for editing markdown.
-  if its unordered list, and after that in new line we add > and type a sentence.The line breaks get added it adds Blockquote tag first
- if we add > and type a sentence after a sentence.It remains same it doesnt while we click preview for normal text(in some files)
- if we add > and type a sentence after a sentence ending up with : it adds \ (in some files)
- in most of the findings ( > ) adds line break

**Comment by jincypjose** [comment]
i think,i Have found something that is related.The grid over here is adding new line.
![Screenshot from 2021-11-25 14-19-01](https://user-images.githubusercontent.com/66897554/143410273-e68d2037-f57e-43c6-96c0-8ece77b81115.png)

 when i am copy pasting the **Hello** __world__ it is taking new line.
![Screenshot from 2021-11-25 14-27-30](https://user-images.githubusercontent.com/66897554/143411368-172aa736-d234-4e7e-80df-9c45bfe9f470.png)
And when i am removing grid with div
![Screenshot from 2021-11-25 14-31-16](https://user-images.githubusercontent.com/66897554/143411406-9ef0d0ac-8149-4812-bef4-672df3691e2a.png)
i can copy paste in same line

![Screenshot from 2021-11-25 14-33-18](https://user-images.githubusercontent.com/66897554/143411624-4582b371-f7c3-475e-aee0-8b338bcd6d2b.png)
This is the same behaviour which tc create has.Grid has bandwidth of 12 which is taking the whole new line

**Comment by mandolyte** [comment]
### Reproducing the problem

1. Open a TA document (nice in some ways because it puts a blue border around "blocks")
2. Turn off sections
3. Turn off blocks
4. Copy a few words from the middle of a paragraph on the source/left side
5. Paste into the target/right side in the middle of a paragraph
6. Before:
![image](https://user-images.githubusercontent.com/1289437/164238788-d4e3a6f0-a866-4798-a032-e60ae45e8458.png)
7. After:
![image](https://user-images.githubusercontent.com/1289437/164238990-f09bbf76-aee0-4024-a672-9d188c4a23f8.png)
8. Unicode viewer shows:
![image](https://user-images.githubusercontent.com/1289437/164239434-10ea05d7-6dcf-4e4a-8fd3-fd5999f26bbd.png)

**Comment by mandolyte** [comment]
The pasted text is pre-pended with a CRLF (Hex 0D and Hex 0A).

This will cause a new block to be created with our current markdown processor.

**Comment by mandolyte** [comment]
**When does it work properly?**
- Always works correctly in HTML mode 
- In markdown mode, only works correctly if shift-control-V is used 

**When does it fail?**
Only in markdown mode using Ctrl-V (which includes "formatting" of source)

**Comment by mandolyte** [comment]
Not a helpful article: 
https://support.google.com/docs/thread/95597915/how-do-i-change-the-default-hotkey-ctrl-v-to-paste-plain-text-without-formatting?hl=en

**Comment by mandolyte** [comment]
Change to markdown-translatable, file `src/components/block-editable/BlockEditable.js`.
From:
```js
const handleCutPaste = () => {
    if (actions && actions.setIsChanged) {
      actions.setIsChanged(true);
    }

    if (actions && actions.setIsAutoSaveChanged) {
      actions.setIsAutoSaveChanged(true);
    }
  };
```

to:
```js
  const handleCutPaste = (event) => {
    const pastedData = event.clipboardData.getData('text/plain');
    event.preventDefault();
    document.execCommand("insertText", false, pastedData);
    if (actions && actions.setIsChanged) {
      actions.setIsChanged(true);
    }

    if (actions && actions.setIsAutoSaveChanged) {
      actions.setIsAutoSaveChanged(true);
    }
  };
```

**Comment by elsylambert** [comment]
Looks good in translationCore Create - v1.4.3 build 147-d089b2c.
