### ISSUE TITLE
UST view missing from Parallel Scripture viewer before the app crashes

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#84]
To replicate this Issue: I scrolled through the book of Acts to check and validate the highlighting in the scripture viewer. After a while of moving to next page and scrolling up and down, noticed that when the page goes to next, the UGNT, ULT and UST column view is disturbed meaning that the column width changed for ULT and it shrunk to 20 % of the row while UGNT and UST stayed 40%each. Upon more scrolling, UST was gone for some of the verses And then after a few seconds the app crashed.

![image.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/20f22ea9-7ff6-4b01-a25f-2fa988f21be4)

Instead of crashing, tCC should inform the user:
This verse is not formatted so it can be displayed in this app. The verse number may be missing or a verse range.

**DoD**: If verse is missing, it's handled without crashing.

**Comment by elsylambert** [comment]
Noticed that even though the UST viewer is not lost in some cases, the app crashes after following the steps in Comment 1.

**Comment by klappy** [comment]
Looks like there is a verse bridge in the UST for 1:24-25. There is a good chance that this could be the root of the issue as we haven't worked on supporting verse bridges yet.

**Comment by birchamp** [comment]
@Elsy Litson <elsy.lambert@unfoldingword.org> can you add an enhancement
issue for verse bridges, if there isn't one, and describe/link this bug in
the description?

**Comment by elsylambert** [comment]
#85 will serve as an enhancement for this required feature.

**Comment by mandolyte** [comment]
@klappy @birchamp This may be more difficult than it seems. Below is the JSON for the verse bridge. The bridge is simply missing and the two verses are empty. Thus what tC Create shows is correct (per the JSON, anyway). This implies that the `usfm.js` package will need work first.
```json
        "24": {
            "verseObjects": [
                {
                    "type": "text",
                    "text": "\n"
                }
            ]
        },
        "25": {
            "verseObjects": [
                {
                    "type": "text",
                    "text": "\n"
                }
            ]
        },
```

**Comment by klappy** [comment]
Should be testable in `1.0.0-beta.4`

**Comment by elsylambert** [comment]
Not seeing the issue in translationCore Create - v1.0.0-beta.5. The app does not crash when the verse is missing in one of the Resources.
