### ISSUE TITLE
Supporting Verse Bridges

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#85]
Verse Bridges caused an issue reported in #84.

 there is a verse bridge in the UST for Acts 1:24-25. This caused the app to crash.

**Comment by klappy** [comment]
Should be testable in `1.0.0-beta.4`

**Comment by elsylambert** [comment]
Looks good in translationCore Create - v1.0.0-beta.5. Verse span is displayed in scripture pane when there is a verse bridge. eg. Luke 1:54-55.
<img width="1522" alt="Screen Shot 2020-06-16 at 6 02 01 PM" src="https://user-images.githubusercontent.com/51806180/84833268-ed88b400-affc-11ea-9ea7-5c169cb9bf7c.png">

**Comment by mandolyte** [comment]
@BincyJ I believe this should close issue #84

**Comment by BincyJ** [comment]
@mandolyte #84 needs to be modified. Birch and I will revise and move it through the next few sprints.

**Comment by BincyJ** [comment]
Since demoed. Closing this issue.
