### ISSUE TITLE
Release 1.2.1

### ISSUE THREAD

**Issue by BincyJ** [unfoldingWord/tc-create-app#851]
#### Prepare Staging 
- [x] PR to remove RC from the version number
 - [x]  create release branch for version 1.2.1 from develop (QA DATA)
- [x] Create staging Netlify link (PROD Data)
#### QA Release and Staged 
 - [x]  Ping QA that release branch for version 1.2.1 is ready for testing 
- [x] Release notes are drafted
- [x] QA approves release notes
 - [x] QA gives go-ahead to release to production
#### Release and Publish
  - [x] PR from release branch for version 1.2.1 to Master
  - [x] Ping QA that production release is released
  - [ ] Final Go ahead  from QA to notify the users of the new release
  - [x] tag release on Github v1.2.1
  - [x] publish release note
  - [x] Announce on forum.door43.org https://forum.door43.org/t/tc-create-1-x-release-notes/661

**Comment by ancientTexts-net** [comment]
v1.2.1-rc.1 build 50-1bb4a08
https://develop--tc-create-app.netlify.app/

**Comment by BincyJ** [comment]
- Need to inform network contacts of the impact to GLs
- Forum post outlined with the steps GLs need to follow to make the changes.
All tN impacted by this release. 
NT- Luke, Eph, 1 Timothy, Titus, Acts.
OT - Ruth, Nehemiah, Exodus, Esther and Jonah

**Comment by ancientTexts-net** [comment]
@mandolyte @birchamp @BincyJ 
https://github.com/unfoldingWord/tc-create-app/blob/f13aff8b0a873abf2c61ec68b81803fbeba6299f/src/components/translatable/TranslatableTSV.js#L174

I believe this is the code needed to fix 1.2.1 release

**Comment by ancientTexts-net** [comment]
problems when netlify rebuilt 1.2.1

fixed:
https://github.com/unfoldingWord/tc-create-app/pull/931/files

---

STAGE is fixed and there's a new branch release like @**Manny Colon** taught us today!
`STAGE` has `v1.2.1` using `git.door43`
`v1-2-1` branch release is using `qa.door43`

https://stage--tc-create-app.netlify.app/

https://v1-2-1--tc-create-app.netlify.app/

**Comment by ancientTexts-net** [comment]
Due to holiday, deferred until Tuesday

**Comment by elsylambert** [comment]
v 1.2.1 is live and looks good.

**Comment by ancientTexts-net** [comment]
@birchamp @BincyJ @mandolyte 

Do we need to update this template with instructions covering what to do with the ISSUES tagged for each release?
Elsy moved it to QA DONE.  But do we CLOSE the issues?  or wait until demoed?  

I think we usually wait, but should we add it to the checklist?

**Comment by birchamp** [comment]
The process of demoing and closing should be done at the end of the sprint.
