### ISSUE TITLE
Warning Prompt if the user leaves the app without saving first

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#868]
Reported by Jane Bussard:
- The user loose their work if they accidentally close the browser tab.

Requirement : Need a warning prompt/pop-up modal if the user leaves the app without saving.
- when the user closes the browser

**Comment by ancientTexts-net** [comment]
Compare:
![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/5cd2e6ae-94c3-4c90-bb9a-d6cd95967f02)

**Comment by elsylambert** [comment]
Looks good in translationCore Create - v1.3.0-rc.4 build 71-fb4011c. Works fine when user leaves the page/ switches files without saving the working file.
