### ISSUE TITLE
Fix Selection Logic Errors In Highlighting Titus & 3 John

### ISSUE THREAD

**Issue by RoyalSix** [unfoldingWord/tc-create-app#87]
This also includes writing tests for the issues fixed

Titus:
1:1 - `τῆς` κατ’ `εὐσέβειαν`
1:2 - ἐπ’ `ἐλπίδι ζωῆς αἰωνίου`
1:3 - τοῦ `Σωτῆρος ἡμῶν, Θεοῦ`
1:4 - `Χριστοῦ Ἰησοῦ` τοῦ `Σωτῆρος ἡμῶν`
1:5 - `ἵνα` τὰ `λείποντα ἐπιδιορθώσῃ`
1:9 - `τῇ διδασκαλίᾳ` τῇ `ὑγιαινούσῃ`
1:12 - `τις ἐξ αὐτῶν, ἴδιος` αὐτῶν `προφήτης`

2:2 - `ὑγιαίνοντας τῇ πίστει,` τῇ `ἀγάπῃ,` τῇ `ὑπομονῇ`
2:10 - `τὴν διδασκαλίαν` τὴν `τοῦ Σωτῆρος ἡμῶν, Θεοῦ, κοσμῶσιν`
2:13 - `καὶ ἐπιφάνειαν τῆς δόξης` τοῦ `μεγάλου Θεοῦ` καὶ `Σωτῆρος ἡμῶν, Ἰησοῦ Χριστοῦ`
3:4 - `ὅτε` ἡ `χρηστότης καὶ` ἡ `φιλανθρωπία ἐπεφάνη τοῦ Σωτῆρος ἡμῶν, Θεοῦ`
3:4 - `ὅτε` ἡ `χρηστότης καὶ` ἡ `φιλανθρωπία ἐπεφάνη τοῦ Σωτῆρος ἡμῶν, Θεοῦ`
3:6 - `οὗ ἐξέχεεν` ἐφ’ `ἡμᾶς πλουσίως`
3:6 - `διὰ Ἰησοῦ Χριστοῦ,` τοῦ `Σωτῆρος ἡμῶν`
3:7 - `κληρονόμοι γενηθῶμεν,` κατ’ `ἐλπίδα ζωῆς αἰωνίου`
3:13 -`σπουδαίως` πρόπεμψο (content issue) πρόπεμψο does not exist in the verse

**Comment by klappy** [comment]
Should be addressed in `beta.6`

**Comment by elsylambert** [comment]
Looks good in beta 6.
