### ISSUE TITLE
Catalog Next Package - Initialization

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/tc-create-app#874]
This issue covers the initial setup of the package plus the Catalog Next (CN) initialization feature.

DoD: 

- [ ] Repo catalog-next-toolkit created
- [ ] Styleguidist demos of package initialization
- [ ] Unit Tests

**Comment by mandolyte** [comment]
**Description of Initialization Features**

The CN component requires initialization when the application starts. This initialization will proceed in the background, so that app is not required to wait until it is done. 

The initialization parameters are:
- SERVER: this points to the copy of DCS to use. Default will be 
`https://qa.door43.org`; and for production: `https://git.door43.org`.
- OWNER: this is the owner of the resources. The default is 'unfoldingWord'. 
- LANGID: this provides the language to be used in identifying resources. Default will be `en`.
- RESOURCES: this is a comma delimited list of resource IDs. The complete list is:
'ta', 'tw', 'twl', 'tn', 'tq', 'obs', 'obs-tq', 'obs-tn', 'obs-sn', 'obs-sq'. 
- Original Language Resources: The Greek and Hebrew published content will be included as a resource. Since they are fixed in ownership and language, they require special treatment. The repos are:
   - unfoldingword/hbo_uhb (at this writing, the latest published version is v2.1.19)
   - unfoldingword/el-x-koine_ugnt (at this writing, the latest published version is v0.20)
- STAGE: this is the value for CN component which determines the release level to work with. It must be one of the following: 'latest', 'preprod', 'prod', 'draft'. The default is 'latest'.
- APIVERSION: this may be hard coded for now to be `api/catalog/v5`.

The demo will simply show the latest production release tag for each resource. This is a very simple demo showing that the CN API is functioning and is being correctly used.


**Technical Requirements**

- Will use a headless design approach and will exclude any React UI components
- The demo will be segregated into a different folder and excluded from the published NPM component. See https://github.com/unfoldingWord/uw-content-validation/tree/master/src for how this was done for the `uw-content-validation` package.
- Consider use of Typescript to benefit from static typing and long term maintainability. For how to setup Styleguidist with Typscript, see this example and its references: https://github.com/mandolyte/typescript-styleguidist-tester

The demo will allow manual updates to the essential parameters and then will show the correct tags for each resource in a simple text list.

**Comment by mandolyte** [comment]
@BincyJ @birchamp 
**Questions:**
1. Should the Original Languages always use the highest prod release? (I think "yes")
2. Should the tag parameter be optional and, if not specified, default to use the highest tag? (I think "no", but see below for implications)
3. Should this API enforce the entanglement of language and resource? (I think "yes"). In other words:
	- if language is specified first, only show resources which exist with that language
	- if resource is specified first, only show languages which exist with that resource
	- this devolves to having two API searches, one for each way

*On the tag being optional:* I doubt there is a use case for a GL team to prefer the highest production release. Instead, they want to point to a release and stick with it until they intentionally want to switch. 

The upshot of this is that this component can never just go off and pre-load the resources. The app must always direct which resources are to be used, including the case of the "sticky" tag.

This will simplify the API some at the cost of complicating the UI/X.

Let me know as soon as possible your answers to the above questions. Thanks!

**Comment by ancientTexts-net** [comment]
@mandolyte @birchamp @BincyJ 
@cckozie @elsylambert 

If we set source version PER BOOK, does that risk continuity when the GL publishes?

For example, let's say the English team says something like "starting in tN v98, every conjunction has a translator note" (or something)
If SOME books are sourced from an OLDER version, the final product would be inconsistent with "NEWER" books

**Comment by birchamp** [comment]
@ancientTexts-net 
 **So here's the problem:**

1. GL team translates Titus TN from en_tn v. 43
2. uW announces that Mark TN is released in en_tn v.44 
3. uW also made a few corrections to Titus TN
4. GL team wants to translate the latest Mark TN (with v.44 as the source)
5. GL team wants to check their translation of Titus TN (translated from v.43) 
6. GL team checker marks Titus TN as wrong because he's looking at the v.44 source.

**Comment by mandolyte** [comment]
This issue is closed since it is superseded by user requirements.
