### ISSUE TITLE
Remove the confusing message "Columns with 50%+ unique values will not be duplicated." from the add row dialog.

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/tc-create-app#898]
Issue:
---
"Columns with 50%+ unique values will not be duplicated." is confusing to the user.  Remove the text from the dialog.

DoD:
---
The text "Columns with 50%+ unique values will not be duplicated."  is no longer displayed on the add new row dialog.

Details:
---
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/59e52f11-8b40-4b98-bcde-1c610c0b114d)

**Comment by elsylambert** [comment]
From Perry Oaks: "I don't understand the purpose of that modal. There is nothing to choose. Why display it? It just makes the user click twice instead of once."

Although, this modal is informational in terms of which all columns have copied data from the parent row(except the ID), if it is not much value to the user and they get to reduce one click, we should consider removing it. Thoughts?

**Comment by elsylambert** [comment]
translationCore Create - v1.3.0-rc.3 build 69-dfb8e27.
The add row modal looks Rectangular like this: 
![Screen Shot 2021-07-26 at 5.41.12 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/8c47a98f-0611-41c2-9263-c19f2835fd88)

It would be better if this modal can be consistent in Size with the Delete row modal.

**Comment by birchamp** [comment]
@mandolyte it looks like the modal is determining some sort of autowidth.  Can you make it have a minimum width more consistent with other modals?

**Comment by ancientTexts-net** [comment]
@elsylambert @mandolyte 

OK if I assign this to myself please

**Comment by ancientTexts-net** [comment]
@**Elsy L** 

 v1.3.0-rc.4 build 70-7dfd6f5

 https://develop--tc-create-app.netlify.app/

Thank you :smile: 
I think this is the last 1.3 build?  Latest QA Fail --> FIXES from # 898

CC: @**Birch** @**Bincy Jobby** @**Cecil New**

**Comment by elsylambert** [comment]
![Screen Shot 2021-08-24 at 1.50.41 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/747b7264-1f28-46be-9da8-4a7b368fc6f7)

With Organization unfoldingword, language selection drop-down shows "No languages found" along with the other languages.

**Comment by elsylambert** [comment]
Looks good in translationCore Create - v1.3.0-rc.4 build 70-7dfd6f5.
