### ISSUE TITLE
SPIKE: Exposing published file revisions

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/tc-create-app#901]
Today files are changed ("revised") and are published in a release. But since releases are a snapshot of the master branch, a release version has not relationship to a revision of a file in the release.

However, the revision chain of a file can be derived by examining the SHA value for each file across all releases. For background:
- on Zulip: [link](https://unfoldingword.zulipchat.com/#narrow/stream/209457-SOFTWARE--.20UR/topic/Computing.20Source.20File.20Versions/near/242820977)
- on personal notes: [link](https://git.door43.org/cecil.new/journals/src/branch/master/research/Repo%20Version%20vs%20File%20Versions.md)

There is a collaboration thread on Zulip where problems and solutions are discussed:
[link](https://unfoldingword.zulipchat.com/#narrow/stream/209457-SOFTWARE--.20UR/topic/Deriving.20published.20file.20revision/near/243020062)

**Comment by richmahn** [comment]
A release doesn’t necessarily have to be from the master branch but usually is. Could be from a totally new branch. This shouldn’t matter as to should just be concerned about diffs between releases rather than commits.

**Comment by mandolyte** [comment]
Note: the Zulip thread has a lot of information and discussion of edge cases. This post will be updated to have a link to a document where the Spike findings are written up.

**Comment by mandolyte** [comment]
Here are the issues arising from this spike:

- https://github.com/unfoldingWord/dcs/issues/325
- https://github.com/unfoldingWord/dcs/issues/326
- https://github.com/unfoldingWord/dcs/issues/327

These address the creation/maintenance of a file revisions table, the API to make the content of said table to applications, and the possible integration of Content Validation into the Release Process.

@richmahn @birchamp @BincyJ
