### ISSUE TITLE
App crashes with a gray blank screen when attempting to open a tQ file

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/tc-create-app#914]
@cckozie commented on [Thu Jun 24 2021](https://github.com/unfoldingWord/gateway-edit/issues/248)

v1.3.0-rc.1 build 54-949db8c
I was attempting to open tQ's on test_org, Russian, Titus 1:1 

![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/3cd8e0f0-1936-4626-a94f-fd11a43b429a)

**Comment by birchamp** [comment]
@elsylambert Can you reproduce this in https://develop--tc-create-app.netlify.app/ ?

**Comment by elsylambert** [comment]
Verified in translationCore Create - v1.3.0-rc.1 build 59-7013259 on July 9th, 2021.
Not seeing the app crash on test_org for TQs. I am able to open and view the following source and target side files on DCS(Clicking on the Article from the chip in tccreate.)
- https://qa.door43.org/unfoldingword/en_tq/src/tag/v25/tit/01/01.md.
- https://qa.door43.org/test_org/ru_tq/src/branch/ElsyLambert-tc-create-1/tit/01/01.md
