### ISSUE TITLE
Load autosave data on open

### ISSUE THREAD

**Issue by ancientTexts-net** [unfoldingWord/tc-create-app#919]
Issue:
---
The app should load from IndexedDB or some permanent local storage.

When the user is loading autosaved data upon opening a file, the app should detect & warn me if my file changed on DCS and my local autosave data is stale.  In this case, user should have the options Save / Discard / Cancel.  SAVE: will overwrite DCS with my current autosave content.  DISCARD: delete my stale autosaved data.  CANCEL: abandon the current action (e.g., switching files, opening file).

DoD:
---
When opening a file, the user is prompted to save or discard autosave data if it is older than the user's file on DCS. 
Also includes Styleguidist demo for the RCL. Provide proper documentation.

Issue:
---
See notes in spike:

https://app.zenhub.com/workspaces/tc-create-workspace-5f049cdbfa88090016bf043e/issues/unfoldingword/tc-create-app/867

**Comment by ancientTexts-net** [comment]
@mandolyte 
For now, I have left a lot of `console.log()`.

I can remove these after review, please.  Thanks.

**Comment by ancientTexts-net** [comment]
testing notes from issue:

https://app.zenhub.com/workspaces/tc-create-workspace-5f049cdbfa88090016bf043e/issues/unfoldingword/tc-create-app/867

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/f685d894-bf50-4bb7-8273-5a29f7576a07)

**Comment by ancientTexts-net** [comment]
1. open TSV or MD file
2. edit the file
3. onblur: mouse out of current edit block (?not necessary?)
4. disable Internet (use FIDDLER2 or turn off wifi?)
5. try to save (--> verify friendly error message)
6. close browser
7. ENABLE Internet
8. open tC Create; open same file you were editing before
9. verify: autosaved content is displayed
10. save file
11. close browser / open file: verify saved content is correct

**Comment by ancientTexts-net** [comment]
Autosave Case #1:

1. open TSV or MD file
2. edit the file
3. onblur: mouse out of current edit block (?not necessary?)
4. close browser (and/or close tab?); verify friendly error message
5. open browser & visit same file as before: verify auto-saved content is available
(alternate #5: open a DIFFERENT file & edit.  THEN open the original file in step #1. Verify autosaved content for file #1 is correct)

**Comment by elsylambert** [comment]
Scenario 2:
DCS USER BRANCH CHANGED (IN "ANOTHER SESSION" - simulated by deleting branch)

⚠ NOTE: this test also simulates an important scenario:
If MASTER was updated in DCS, the GL team should DELETE user branches... (gatewayAdmin?)
(or they could merge into --> user branches, for example...
But the point is that the USER BRANCH changed outside the app and we need to notify the user.)

using DEVELOP url:

logged in with org unfoldingWord and resource tN and language English
selected book of Jude
made an edit and saved it
In QA DCS ⚠😊 DELETE the user branch.
Close tCC and OPEN to the AutoSaved file.
selected Jude again
VERIFY: the user is prompted to KEEP/DISCARD.

**Comment by elsylambert** [comment]
translationCore Create - v1.4.0-rc.5 build 111-7f5491d. Sometimes not seeing the Modal prompting for Keep/Discard changes. I saw this prompt once as shown in the screenshot below:
![Screen Shot 2021-12-27 at 11.29.12 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/4e7f446f-11b2-41fa-98e7-50e0d00b499d)

Please see the error in the console when I am not seeing the Prompt, after I delete me user branch in DCS.
![Screen Shot 2021-12-27 at 11.35.46 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/3745344a-23ae-420f-9688-641978662a24)

**Comment by elsylambert** [comment]
translationCore Create - v1.4.0-rc.5 build 111-7f5491d.
When there is a newer version on DCS i.e the user branch is stale/old data, I am seeing the prompt message with the options to Discard/keep the autosaved file.
If Discard is chosen, I see a fresh file opened from the DCS. If Keep is chosen, I see that the autosave data is preserved and upon saving the file again, the current changes are saved in the DCS user branch.
