### ISSUE TITLE
Detect prior autosave content & warn

### ISSUE THREAD

**Issue by ancientTexts-net** [unfoldingWord/tc-create-app#921]
Issue:
---
Prior to an autosave event, the app should detect & warn me if my file or branch changed on DCS and my local autosave data is stale.  In this case, user should have the options Save / Discard / Cancel.  SAVE: will overwrite DCS with my current autosave content.  DISCARD: delete my stale autosaved data.  CANCEL: abandon the current action (e.g., switching files, opening file).
DoD:
---
Changing a file or deleting a branch on DCS and then performing an autosave event within the app will prompt the user to update their data. 
Also includes Styleguidist demo for the RCL.  Provide proper documentation.

Details:
---
See notes in spike:

https://app.zenhub.com/workspaces/tc-create-workspace-5f049cdbfa88090016bf043e/issues/unfoldingword/tc-create-app/867

**Comment by ancientTexts-net** [comment]
Scenario 1: 
HAPPY PATH :)

using DEVELOP url:

1. Deleted branch (to be sure of clean starting point)
1. logged in with org unfoldingWord and resource tN and language English
1. selected book of Jude
1. made an edit, but did not save
1. turned off wifi
1. close
	- clicked the "x", I got a popup warning that my changes are not saved
	- clicked cancel on popup
	- tried to save
	- got popup saying that changes could not be saved
	- The save button was deactivated at this point
1. Turned wifi back on
1. refreshed page and it returned to logon page
1. logged as before and selected book of Jude

VERIFY: auto-save content is displayed.

---

Scenario 2: 
DCS USER BRANCH CHANGED (IN "ANOTHER SESSION" - simulated by deleting branch)

using DEVELOP url:

1. logged in with org unfoldingWord and resource tN and language English
1. selected book of Jude
1. made an edit and saved it
1. went to QA DCS and deleted the branch I just updated/created in app, clicked the "x" to return to select resource
1. selected Jude again

VERIFY: the auto-save content is there 

---

Scenario 3: 
DCS USER BRANCH CHANGED (IN "ANOTHER SESSION" - simulated by editing directly on DCS)

using DEVELOP url:

1. logged in with org unfoldingWord and resource tN and language English
1. selected book of Jude
1. made an edit and saved it
2. close tC Create
1. went to QA DCS and edited the same file -- in the USER'S BRANCH.
1. open tC Create; open the same file:


VERIFY: the app prompts you to DISCARD or KEEP the autosaved file.

1. Discard: The file is closed. VERIFY: open the file again and it should show your server content.
1. --OR-- Keep.  Then edit and save your file in tC Create.  Then open tC Create and open the same file.  VERIFY: the newly saved content is shown.


---

Scenario 4:
TWO FILES

using DEVELOP url:

1. logged in with org unfoldingWord and resource tN and language English
1. selected book of 1 JN
1. made an edit ... DO NOT SAVE
1. select book of 2 JN
	VERIFY: 2 JN looks OK
1. make an edit .... SAVE 2 JN
1. selected book of 1 JN
	VERIFY: prior auto-save content for 1 JN is correct.


.

**Comment by ancientTexts-net** [comment]
@jincypjose @Joel-C-Johnson @mandolyte 
@elsylambert 
@birchamp  @BincyJ  

here are updated test notes please!  Thanks!

**Comment by ancientTexts-net** [comment]
@jincypjose @Joel-C-Johnson @mandolyte 
@elsylambert 
@birchamp  @BincyJ  

FYI this is the DEPLOY PREVIEW

but I don't think we do QA here.  we will review & merge for QA from the DEVELOP branch ok?  Thanks!!

https://deploy-preview-1116--tc-create-app.netlify.app/

**Comment by ancientTexts-net** [comment]
@jincypjose 

THANK YOU -- HUGE help :))))

does this work?

- PRs are ready for review:
- But I will fix the bug for SCENARIO #2 above
- if you review in REVIEWABLE,
  then it will only prompt you to review my NEW COMMITS later 👍👍

**Comment by ancientTexts-net** [comment]
@Joel-C-Johnson @jincypjose @mandolyte 

the only changes were 
- removed those comments that @jincypjose  and I saw while testing on 12/23
- made the spelling consistent ("autosave" or capitalized AutoSave;  but NOT auto-save /etc)

THANK YOU EVERYONE FOR HELPING ❤️

**Comment by ancientTexts-net** [comment]
@elsylambert 

FYI the latest test notes are "HERE" (in the ISSUE for # 921)
Since # 921 is the latest PR for the app

TEST NOTES:
https://app.zenhub.com/workspaces/tc-create-workspace-5f049cdbfa88090016bf043e/issues/unfoldingword/tc-create-app/921

TEST LINK: (develop)
https://develop--tc-create-app.netlify.app/

CC:
@jincypjose @Joel-C-Johnson @mandolyte 
@birchamp @BincyJ

**Comment by ancientTexts-net** [comment]
@Joel-C-Johnson @jincypjose 
@mandolyte 

- gitea-react-toolkit styleguidist:
  AutoSave demo

  GOAL = demonstrate how to use the RCL
  with the new "onLoadCache" / "onSaveCache" features.


- Existing demo:
  https://gitea-react-toolkit.netlify.app/#/File%20CRUD?id=filecontext

  This is a good demo.  We can copy and make a new demo.
  Implement onLoadCache={} and onSaveCache={} in the new demo.

- Basic implementation:
  Implement (1) load cache; (2) save cache
  "new" props for FileContextProvider

  Use this function signatures:
  signatures:
    const _onLoadCache = async ({authentication, repository, branch, html_url, file}) ...
	onLoadCache return value:
	looks like the `file` prop.
		object like {}
	But, here, you can change content to "simulate" loading from cache.
    const _onSaveCache = ({authentication, repository, branch, file, content}) ...

  https://github.com/unfoldingWord/tc-create-app/blob/2612f8ae7b080196bbe4e01ac0facb5b8405f493/src/App.js#L204
  (APP code, just for reference.)


- Load Cache: 
  - Display with console.log
  - return hard-coded value

- Save Cache:
  - Display with console.log

- NEXT:
  - GOAL = how can we make the demo INTERACTIVE??
    actually "DO" something :))))

  - ?? Check box??
  - ?? Text box for "cached content"
	(or hardcode it ??)
	e.g.,
	<input type="text" id="cacheContent" value="This is my cache"/>
  - onLoadCache:
    - if demo "cached content" input textbox is EMPTY, return null
    - if input textbox has content, return that content.
  - GOAL = demo onLoadCache, but without actually using storage (local storage).


- Does the styleguidist do STORAGE??
  NO!

  STORAGE is implemented by each APP (not the RCL)
  https://github.com/unfoldingWord/tc-create-app/blob/develop/src/core/persistence.js
  No need to test this in styleguidist.

- SAMPLE OBJECT

{
html_url: 
	'https://qa.door43.org/unfoldingWord/en_tn/src/branch/ZachPennington-tc-create-1/en_tn_65-3JN.tsv', 
	filepath: 'en_tn_65-3JN.tsv', 
	sha: '7e19ceb70f0eea58513bf123d8aaa1c2579dbfc0', 
	timestamp: "Mon Dec 27 2021 09:00:32 GMT-0600 (Central Standard Time)", 
	content: 'testing',
  filepath: "en_tn_65-3JN.tsv"
}


.

**Comment by elsylambert** [comment]
Tested all the four scenarios and found to be working as expected. For Scenario 4, found that the changes not saved prompt message is over ridden by Auto save written separately in #1122.
Looks fine in translationCore Create - v1.4.0-rc.5 build 111-7f5491d.

**Comment by ancientTexts-net** [comment]
THANK YOU @elsylambert

**Comment by ancientTexts-net** [comment]
```
[⚠] Your file was locally autosaved on 1/5/2021, 9:11:52 AM, 
but the server file is newer (1/5/2022)

Do you want to keep or discard the autosaved file?

	[Keep Local AutoSaved File]	[Keep Server File]
---

Details >>
---
AutoSaved file: 
Checksum: d84b3f2983f6a908e64304e56022ed480ccd6e87

Server file (newer): 
Checksum: 28e6268e2379ab0c4d2ad7ed3298adfc704af0c9


```

**Comment by ancientTexts-net** [comment]
@birchamp @BincyJ

**Comment by birchamp** [comment]
@ancientTexts-net can we get autosave added to the styleguidist demo
