### ISSUE TITLE
Navigate to chapter verse in TSV

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#927]
Issue:
---
Users want to be able navigate to the chapter and verse quickly and easily so they don't have to page in order to get back to where they were or fix the specific issue they are working on

DoD:
---
Users can jump directly to a chapter and verse in a TSV (both TN and TWL).

Details:
----
This could be done with a special search function, or with a filter.   To do this well, we'll need to implement #928, but it is not a blocker.

**Comment by elsylambert** [comment]
@Joel-C-Johnson Can you please add a screenshot or steps to Navigate to a chapter/verse?

**Comment by Joel-C-Johnson** [comment]
@elsylambert 
Now users can jump directly to a chapter and verse in a TSV (both TN and TWL). This is done inside the filter option.
Here are the steps,
#### In TN
1. Login to tc-create-app.
2. Select any organisation.
3. Select Resource "en_tn"
4. Select any book.
5. On the top right corner click on the filter option and you can see the updated chapter and verse field inside it.
![Chapter-Verse](https://user-images.githubusercontent.com/25791348/143254506-628e1b69-fa83-42ac-adfc-a13c5e1554fc.png)


### In TWL
1. Login to tc-create-app.
2. Select any organisation.
3. Select Resource "en_twl"
4. Select any book.
5. On the top right corner click on the filter option and you can see the updated field "reference" inside it.
![reference](https://user-images.githubusercontent.com/25791348/143260578-ac128c97-477f-4d15-9127-ff2cf0e8ca85.png)
