### ISSUE TITLE
Search, filters and new row should stay on the current record when they're cleared

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#928]
Issue:
---
When a user clears the search or the filter, they want to remain on the current record that's in view instead of being returned to the top of the file.

DoD:
---
When the user clears the search bar, or resets the filter the user is kept on the same record they were on.

**Comment by ancientTexts-net** [comment]
@birchamp  @BincyJ  -- @Joel-C-Johnson just finished #927
should he work on #928 too ?
