### ISSUE TITLE
Edit Original Quotes makes the page to scroll to top when the filter is ON.

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#93]
1. Open a book in tN and use the filter to go to a specific chapter.
2. Edit the Original Quote  section and hit enter.
3. The page moves to the Top.

**Comment by RoyalSix** [comment]
markdown translatable

**Comment by klappy** [comment]
Should be addressed in `beta.11`

**Comment by elsylambert** [comment]
Issue is resolved in beta-13. Not seeing the page scroll to top when filter is ON.
