### ISSUE TITLE
SPIKE: Handle RTL languages

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#930]
When the user chooses a language that is RTL tC Create needs to handle it properly.

Who can test this? (send out an invite on OCE?)
What are the typical performance expectations?
What has RUN done on this? Font support? Font Sizing?
What are the usual bug/problems/fixes for RTL? (ie. bouncing cursor)
What RTL BPs/resources do we have on Door43?

**Comment by PhotoNomad0** [comment]
RTL languages:


Right-To-Left Languages

The two most well-known right to left languages are Arabic and Hebrew, which share a common linguistic ancestor in the Aramaic alphabet. Persian, Sindhi and Urdu all use adapted forms of the Arabic alphabet. Azeri, Kurdish, Azerbaijani, Rohingya, Fula, N’ko, Syriac and Maldivian are also right-to-left languages.

**Comment by PhotoNomad0** [comment]
Note: Released RTL resources:

https://git.door43.org/catalog?tab=&sort=newest&q=ar%5C_
https://git.door43.org/catalog?tab=&sort=newest&q=ur%5C_
fa
https://git.door43.org/catalog?tab=&sort=newest&q=fa%5C_

**Comment by PhotoNomad0** [comment]
Note: Unreleased RTL resources:

https://git.door43.org/explore/repos?tab=&sort=recentupdate&q=ar%5C_
https://git.door43.org/explore/repos?tab=&sort=recentupdate&q=ur%5C_
https://git.door43.org/explore/repos?tab=&sort=recentupdate&q=fa%5C_

**Comment by jincypjose** [comment]
1. Who can test this? 
 - Users who uses languages like Arabic, Urdu and other languages which can be written in RTL can test(Maybe need to fill in more for clarity)
2. What are the typical performance expectations?
 some of the UI expectations are
 - Scroll bar should be at left of the editor
 - Should auto detect right or left language
 - Editor should be handling the mixture of right and left languages
 - Undo should work for RTL
 
5. What are the usual bug/problems/fixes for RTL? (ie. bouncing cursor)
 - Cursor shouldn't be jumping around
 - Cursor should be stable

@birchamp  3rd is for the person you mention RUN

**Comment by birchamp** [comment]
https://git.door43.org/fa_gl/fa_obs/src/branch/master/content. - may be a good place to start

**Comment by birchamp** [comment]
@jincypjose test a simple text area by setting the RTL direction.  
We need to determine:
What happens when a RTL element has English text in it already?
What happens when the user types a RTL language while the English is still there
What happens when the English is replaced?
What happens when RTL language is typed but then the user needs to switch to English?

**Comment by jincypjose** [comment]
1.when i was testing in a common editor i observed if RTL has english text already in the field for eg: arabic is the language we are going to type into, it matters if the english text is in the middle or in between arabic words there would be no changes in the direction.But when the english text was at the beginning the editor was auto detecting the language and was changing the direction for eg: when i typed english and then arabic(the editor was auto detecting the direction of first language which is english and was keeping the same direction for arabic which is LTR).
2. So for second one my observation would be same as first one.
3. when i was replacing English with arabic it worked normal(as we know the difference would be the direction and the cursor where it will be placed.so, for english in RTL the cursor would be at the beginning).
4.we can type english in RTL but the difference would be the cursor as a mentioned above also i observed, when i typed an english sentence and tried characters like(.,+*&^%$#() etc..) was getting placed at the beginning. Works normal for letters and numbers.
