### ISSUE TITLE
Show all available languages within an organization in the language choice drop down

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#932]
Issue:
---
While tC Create is primarily targeted to GLs, users want to translate **whatever language** repositories they have set up in their organization.  If their repositories are named correctly, then the user should be able to chose that language (specified in the repo name) and resource combination regardless of the GL/OL status of the language. 

DoD:
---
tC Create will allow users to choose any of the languages that are specified in the repository name in repositories within their DCS organization.

Details:
---
http://td.unfoldingword.org/exports/langnames.json is the list of languages and their codes that tC Create uses. It can be viewed here: https://td.unfoldingword.org/uw/languages/. This issue is related to #887. OrigL languages should be filtered from the list.

**Comment by mandolyte** [comment]
The Catalog Next implementation has conveniently provided some extra attributes in the JSON return values when using certain Gitea API calls. In particular, it is very easy to see all languages used in an organization using this API.

This:
https://qa.door43.org/api/v1/orgs/unfoldingword

returns the following. Note the "repo_languages" attribute.
```json
{
   "id":613,
   "username":"unfoldingWord",
   "full_name":"unfoldingWord",
   "avatar_url":"https://qa.door43.org/user/avatar/unfoldingWord/-1",
   "description":"",
   "website":"https://unfoldingword.org",
   "location":"",
   "visibility":"public",
   "repo_admin_change_team_access":false,
   "repo_languages":[
      "el-x-koine",
      "en",
      "fr",
      "hbo"
   ]
}
```

@richmahn As I recall, the languages shown are the union of:
1. manifest entries in the resource repos.
2. resource repos following standard naming conventions with a language prefix.

**Can you confirm?**

@richmahn Question 2: Is there any validation done for the language codes shown in the list? For example, if there was a repo named `snd_ta` (Elvish), would you display it in the list of repo languages?

**Comment by mandolyte** [comment]
@richmahn I notice that https://qa.door43.org/api/v1/orgs/ru_gl shows both English and Russian. But I don't see any repos that "look" like English.

Do you know why it is showing?

**Comment by mandolyte** [comment]
@richmahn Looking at the BCS results and I decided to take a look at the manifest for kn_tn.

It shows:
```yaml
language:
--
  | direction: 'ltr'
  | identifier: 'kn'
  | title: 'Kannada'
```

It only shows 'en' under the source attribute. I would say that showing the language id for the source should not be done... Thoughts?

**Comment by richmahn** [comment]
@mandolyte Yes, that is correct that even repos without a manifest.yaml file will be used to derive org languages if they are properly formatted with <lang>_<repo> and the <lang> is in the tD lang JSON file.

**Comment by richmahn** [comment]
Validation done here: https://github.com/unfoldingWord/dcs/blob/main/modules/dcs/languages.go#L22

**Comment by richmahn** [comment]
@mandolyte It is the hi_tw that is still set as English:

https://qa.door43.org/translationCore-Create-BCS/hi_tw/src/branch/master/manifest.yaml#L21

**Comment by richmahn** [comment]
Languages: http://td.unfoldingword.org/exports/langnames.json

**Comment by mandolyte** [comment]
@birchamp I think this issue supersedes 887. But since I began the work under 887, please leave it open so that the PR doesn't look funny. 

Perhaps close this one and replace the issue content in 887?

**Comment by mandolyte** [comment]
Closed with above post in mind.
