### ISSUE TITLE
Unblock access to td.unfoldingword.org (cors policy)

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/tc-create-app#933]
for tc-create to access the languages JSON at [link](https://td.unfoldingword.org/exports/langnames.json) we need to tweak the CORS policy (see error below)

```
Access to fetch at 'https://td.unfoldingword.org/exports/langnames.json' 
from origin 'http://localhost:3000' has been blocked by CORS policy: 
No 'Access-Control-Allow-Origin' header is present on the requested resource.
 If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

@jag3773 feel free to re-assign to Jaap-Jan (I was unable to identify his Github account).

This issue just exists to serve as a tracker and dependency of issue 887

**Comment by yakob-aleksandrovich** [comment]
The issue should have been fixed. Can you please test?

**Comment by mandolyte** [comment]
Verified! Thanks.
