### ISSUE TITLE
Collaborate on uW Dev Workflow

### ISSUE THREAD

**Issue by ancientTexts-net** [unfoldingWord/tc-create-app#936]
follow up from Manny's training: help update the uW Dev Workflow document in a way that works for "all"apps

**Comment by ancientTexts-net** [comment]
replied to Manny on 6/30

---

I tried to take what you showed us and describe the tC Create process.
I tried to make a view short rules to describe the details:

this is just a ROUGH DRAFT

Simple Rules:
1. Follow the git workflow.
2. Avoid semver filters for internal libraries.
3. (TBD: RELEASE process)
4. (TBD: ? what's the best way to provide QA with prod DATA?)
	- Birch suggested this detail can wait?


Can we reword rules like this to cover PART of our process?

PART 1: DEV to RC:

- Developer: create **feature branches** containing a single feature
- Developer: **PR ** --> to develop (linking the PR to a single GitHub/Zenhub issue)
    - Developer: Verify Netlify deploy-preview for **all** PRs?
    - Reviewer: Verify Netlify deploy-preview for **all** PRs? (quick happy path)
    - Reviewer: review/collaborate/approve/merge
- Reviewer: PR --> to **version branch** (merge immediately?) :question: is this how to do it?
    - Reviewer: create version branch if necessary
    - Reviewer (or IT?): configure **netlify ** for version branch
         - (:question:  not sure if we need all reviewers to also have access to netlify?)

PART 2: RELEASE:
- Modeled in this issue:
	https://app.zenhub.com/workspaces/tc-create-workspace-5f049cdbfa88090016bf043e/issues/unfoldingword/tc-create-app/851
- TODO: should we describe THAT process in simple rules?
- :question: do we PR from VERSION BRANCH --> MASTER ?

.

**Comment by ancientTexts-net** [comment]
updated https://docs.google.com/document/d/1ntgc3AY9EaR3zjaJRvCSMQKr7D8VRFs_rddy05GBVvQ/edit#

**Comment by birchamp** [comment]
@ancientTexts-net yes for the collab week
