### ISSUE TITLE
Occurrence -1 does not work as intended

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#94]
Highlighting with occurrences  does not work with the repeated words.
- also does not highlight if it has ellipsis.

**Comment by RoyalSix** [comment]
- [  ] Write tests for the broken functionality
- [  ] Identify broken logic/implementation
- [  ] Create fix and test with ui, document code
- [  ] Fix unit test

**Comment by elsylambert** [comment]
Test case: Highlights to show when there are multiple occurrences of a word.
for eg. Judges 1:3 has two occurrences of Simeon. when the OriginalQuote is copied and pasted, the highlight does not show currently , neither does the Occurrence show up.

**Comment by klappy** [comment]
Should be addressed with build 8.

**Comment by RoyalSix** [comment]
This behavior should now give no highlights

**Comment by RoyalSix** [comment]
Verified on https://develop--tc-create-app.netlify.com/

**Comment by elsylambert** [comment]
Beta-13. This works as expected. By having an ellipsis and -1 does not highlight.
