### ISSUE TITLE
Disable "Compare Master" on the Source Side Chip for Translation mode

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#940]
translationCore Create - v1.3.0-rc.1 build 54-949db8c
Translation Mode: when the Source side is coming from the Published version, the "Compare Master"  button on the Source side chip has to be removed or disabled. Currently it gives 500 error.
![Screen Shot 2021-06-25 at 11.28.44 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/5ae57393-fe73-4576-b46c-d1b6d74691da)

DoD:
---
The compare master button on the source side is disabled in Translation Mode

**Comment by ancientTexts-net** [comment]
to reproduce this bug,

choose TRANSLATE_TEST repo
select another language (translation notes -> TITUS ,  in RUSSIAN)
click chip: should get error

**Comment by ancientTexts-net** [comment]
strange: it WORKS with this file:
`translate_test` / `en_tn` / `2JN`

TBD: questions:
- why does it work with 2JN here?
- what URL is it building to compare?  (what are the 2 branches/repos it wants to compare?)
- is it a FILE EXISTS issue?  
   --OR-- is it building the wrong URL?

**Comment by ancientTexts-net** [comment]
I am NOT SURE if this is part of the problem:
But @Joel-C-Johnson  this answers your questions about " how can there be missing files?"

See screenshot:

In the TARGET repo,
User branch might ADD a NEW file
but the new file is MISSING from the target MASTER branch

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/a9c33bc5-380e-4950-a50c-8313aeba1990)

**Comment by ancientTexts-net** [comment]
...but then why does it fail for TITUS in Spanish ??

**Comment by ancientTexts-net** [comment]
also, to answer the other question,

I think:
SOURCE always comes from /unfoldingWord/ org
TARGET is the org you choose in the stepper

**Comment by ancientTexts-net** [comment]
TRANSLATION MODE == means the TARGET repo is different from SOURCE repo

EDITOR MODE == means the TARGET is /unfoldingWord/ repo

**Comment by ancientTexts-net** [comment]
![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/8454b625-66c6-4b25-83c3-5f8dad3526fe)

**Comment by ancientTexts-net** [comment]
here's the problem...

and I think solution is:

1. set `sourceCompareLink` (only????) to NULL
2. correctly render the left (SOURCE) chip (DO NOT SHOW the BUTTON & DO NOT HAVE ONCLICK LINK if `sourceCompareLink` is null

![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/e7005720-a3fa-4e04-b414-83a75d89683e)

**Comment by ancientTexts-net** [comment]
@Joel-C-Johnson @jincypjose 

Great job debugging!
Great work finding how to remove the link!


A few options?
- Disable the chip: 
  (problem: middle "link" (compare file) is disabled too??)
- OnDelete = null
  (problem: alignment issue)
- OnDelete => alert()
  (problem: alert() assumes brower-based.
   OK: since this code is in the APP.
   problem: the button is still there.)

For now, let's revert the formatting changes, OK ?
- we can prettify / lint if we need LATER,
- but good to keep formatting & bug fixes in a different PR please.

**Comment by elsylambert** [comment]
Looks good in translationCore Create - v1.4.0-rc.5 build 111-7f5491d. Not seeing error on Compare Master button in Translation mode as it is disabled and shows a info tool tip.![Screen Shot 2021-12-27 at 11.49.38 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/c0bf1201-321b-4add-af2b-2cd8c51e7e4c)
