### ISSUE TITLE
SPIKE [0]:Highlighting issue in Hebrew Text

### ISSUE THREAD

**Issue by elsylambert** [unfoldingWord/tc-create-app#95]
- Is this due to how string comparisons are done in Hebrew? 
*Possibly normalizing the string to NFC prior to the text comparison could resolve the issue.
The UNICODE report may be of some value: https://unicode.org/reports/tr15/#Canonical_Equivalence*
- Should this be an RCL that has swappable rulesets? Maybe string punctuation tokenizer.
- Map out what's needed to execute this. 

Highlighting issue in Hebrew Text :
 In Ruth,  some of the Hebrew words are not highlighted.

This should be the part of Highlighting issue Epic #62

**Comment by jag3773** [comment]
This might have been fixed by the content changes in https://git.door43.org/unfoldingWord/hbo_uhb/pulls/526.  Please retest.

**Comment by elsylambert** [comment]
Spacing issue in content was fixed after the changes. However there are still highlighting missing in few verses.
