### ISSUE TITLE
Add Study Questions TSV as a source

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#953]
Issue:
---
the https://git.door43.org/unfoldingWord/en_sq repository should be listed as a source text for English. _Note_: Currently (7/9/21) there are no releases of this repo.  Once a release is made other languages should be able to translate from it. If there are no releases then there will not be any source text. The warning should read, "No source text has been released for this resource, please choose a different resource." After clicking 'ok', the user should be returned to the resource list.

DoD:
---
English users (at a minimum) can choose Study Questions as a resource and edit it (edit mode). If there's no released text then users in translate mode should be warned after they choose a language.

**Comment by elsylambert** [comment]
translationCore Create - v1.4.0-rc.2 build 96-14c4cc5.
Not seeing the Study Questions resource in the list: en_sq
![Screen Shot 2021-11-10 at 11.10.11 AM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/94c31d28-c4c8-41b2-9584-0880c85d5568)

**Comment by elsylambert** [comment]
translationCore Create - v1.4.0-rc.3 build 104-85b41fb
![Screen Shot 2021-12-13 at 6.27.04 PM.png](https://images.zenhubusercontent.com/5d02efb2f425650e637abe10/c4ecc68c-b770-4b21-a1e6-70126cfef38d)

**Comment by BincyJ** [comment]
@mandolyte , can you check this issue? Would it require major effort to fix this issue?

**Comment by mandolyte** [comment]
Worked on it today and will continue. You can find chatter about it on
discord

**Comment by elsylambert** [comment]
Looks good in translationCore Create - v1.4.0-rc.4 build 108-41a72cb.Study questions works fine in Translation mode.
