### ISSUE TITLE
Update Validator to latest

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#957]

**Comment by elsylambert** [comment]
@mandolyte Please add the reference to the issues/changes updated to the latest validator. Thanks.

**Comment by mandolyte** [comment]
Below are all the linked issues. This list comes from the PR for v2.1.5, which is:
https://github.com/unfoldingWord/uw-content-validation/pull/177 (they can be seen on the lower right side of page under the heading "Linked Issues". I only see one that might be of interest to tc-create at this time (which only uses the validator for tN resources). It is a test to ensure that the language code of the resource matches the language code in the manifest.

For example, consider the manifest for the TWL repo for es-419:
https://qa.door43.org/Es-419_gl/es-419_twl/src/branch/master/manifest.yaml
The manifest has this:
```yaml
language:
--
  | direction: 'ltr'
  | identifier: 'en'
  | title: 'English'
```
The identifier 'en' is incorrect. It should be es-419.

The other issues address other resource types.


Full list of linked issues:
- [Check for unwanted spaces before footnotes](https://github.com/unfoldingWord/uw-content-validation/issues/168)
- [OrigL checks don't seem to fail on extra space in x-tw field](https://github.com/unfoldingWord/uw-content-validation/issues/165)
- [Detect ugly leading zeroes in Scripture display links](https://github.com/unfoldingWord/uw-content-validation/issues/161)
- [Handle out-of-memory error better](https://github.com/unfoldingWord/uw-content-validation/issues/160)
- [Ensure that booknames can have a space in them](https://github.com/unfoldingWord/uw-content-validation/issues/156)
- [Check OrigL relation entries in the manifest](https://github.com/unfoldingWord/uw-content-validation/issues/180)
- [Ensure that the new TWLs are now in the DEFAULT checks](https://github.com/unfoldingWord/uw-content-validation/issues/181)
- [Demo shows "No files checked"](https://github.com/unfoldingWord/uw-content-validation/issues/182)
- [Check that USFM has a \mt field](https://github.com/unfoldingWord/uw-content-validation/issues/184)
- [Check that language code in manifest matches the one in the repo name](https://github.com/unfoldingWord/uw-content-validation/issues/185)

**Comment by elsylambert** [comment]
Looks good in translationCore Create - v1.3.0-rc.4 build 71-fb4011c.
