### ISSUE TITLE
SPIKE: Investigate paste issues

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/tc-create-app#996]
Is #444 (paste as plain text) broken? 
Define #839 (paste adds line breaks).

Document your findings here, but add issue-specific information to the individual issues.

**Comment by jincypjose** [comment]
Have added findings for #839 in that issue - its (>) which is adding line breaks while editing in markdown it is adding Blockquote tag first

**Comment by ancientTexts-net** [comment]
following :)
